fishtest/fishtest/templates/tests_view.mak
Correct a typo in spsa test view.
=> Correct typo

fishtest/fishtest/api.py, worker/worker.py
as otherwise new worker will not be rolled out to existing clients and new thread option handling won't work.
Thanks to Alfred for the spot.
=> Update worker version (API) 

fishtest/fishtest/templates/tests_run.mak
See discussion at https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/0FUC8uqOGo4
=> Increase LTYC to 100+1

fishtest/fishtest/templates/tests_run.mak
100+1 is just taking too long to be practical.
=> Change LTC to 60+0.6

fishtest/fishtest/rundb.py
This patch adds some server-side sanity checking on reported spsa games in rundb.py::update_task().
Specifically, it disallows two behaviors:
* spsa games have just completed, but this task has no games completed.
* spsa games have just completed, but this task has no _new_ games completed.
The sanity checks are not perfect, in the sense that ideally we'd make sure 'spsa' and 'stats', as reported, are in sync, but this would add complexity since 'stats' totals games across the lifetime of a task, whereas the counters in 'spsa' reset with each set of parameters.  As such, my feeling is that if a worker is so broken that such a test is needed, we have other problems on our hands?
Anyway, the above tests should at least prevent the present anomalous behavior as assessed in the following …
=> sanity check number games versus number spsa games

fishtest/fishtest/api.py, worker/games.py, worker/worker.py
Combination of several worker updates which have been informally approved by @glinscott but left open for quite some time in order to combine them into a single commit.
=> Worker update

fishtest/fishtest/api.py, worker/games.py, worker/worker.py
in times of failure due to high load.
This overlaps with https://github.com/glinscott/fishtest/pull/150
but has slightly different characteristics
=> Add random delays to communication to server

worker/games.py
This patch reduces upload traffic by 1/(2N) for an N-core worker
by only adding the params for the last game in an SPSA-batch of
2N games.
=> Reduce SPSA upload traffic

fishtest/fishtest/views.py
without any new framework dependencies.
I am a bit in doubt over the cache time, started with 5 seconds, now it's 2 seconds, could even be 1 second
=> Add a cache for the Tests view

fishtest/fishtest/rundb.py, fishtest/utils/index.py
Reverts glinscott/fishtest#166
=> Revert "Revert "add index on tasks.pending to speed up query of new tasks""

fishtest/fishtest/rundb.py
The update_task() function in rundb.py makes several calls to run.save() during [execution], which means that partially updated run data is visible to other processes in the database.
This change removes the intermediate calls and only executes one save() at the end of the function when the whole of the update has finished. To enable this, the stop_run() function is modified so that it can either read and save the run being stopped from/to the database, or update the data in memory if a "run" object is passed in.
Hopefully this will stop some odd effects where inconsistent data is sometimes displayed on fishtest [and also reduce the load on the server].
=> Remove extra calls to run.save() from update_task()

fishtest/fishtest/rundb.py
Limit impact of request_task API on throughput
=> Limit concurrent expensive request_task API

fishtest/fishtest/rundb.py
Record less for > 20 parameters runs and limit max size
=> Optimize the stored SPSA parameters

fishtest/fishtest/rundb.py
for
https://github.com/glinscott/fishtest/commit/a56517123249f736dc862f2d1dfdc3e7a09ae7ef
=> Python 2.6 fix

fishtest/fishtest/rundb.py, fishtest/fishtest/views.py
The idea is simple, there is no need to read Run data more than once from MongoDb, because we are the only one updating.
The only exceptions are
- request_task, which executes a MongoDb query that modifies the database, so
the Run data cache is invalidated.
- scavenge.py (new internal implementation for active Runs in this PR)
- update_users.py (does not write Run data)
This PR will also reduce the write frequency from update_task which is executed hundreds of times each second and overwrites the data it has just written a few milliseconds earlier. These writes are now buffered and a buffer is flushed every second.
In addition rewrite and speedup request_task by executing the selection logic in Python.
=> Cache and buffer Run data

fishtest/fishtest/rundb.py
Improve long interval between sprt overview updates
=> Fix periodic flush

fishtest/fishtest/rundb.py
Still troubles with big spsa, limit history more
=> Adjust spsa history limits

worker/games.py
Remove the download of the engine binaries:
- the central engines builder is not used anymore
- there are simple instructions to install a compiler in windows and linux workers
=> Remove the download of engine binaries

worker/games.py
Add a cleanup function to the worker, such that obvious problems with opening books are fixed.
Still to do: add some check for signature or hash.
=> Rough fix for empty book problem

worker/games.py
This reverts commit ccfae576fa0ae40e0fa3ada6510e46e817fbf15d.
=> Revert "Rough fix for empty book problem"

.travis.yml, setup.py, test_worker.py
Let me open this to check whether I understood how to set up travis.
=> First go at CI

fishtest/fishtest/views.py
Needs testing on the Dev server
=> Fix double listing of recently finished run

README.md
Add the banner with the Travis status to the Readme.md
=> Add Travis Build Status to Readme.md

fishtest/fishtest/rundb.py, fishtest/fishtest/templates/run_table.mak, test_server.py
and a proper stop() to rundb.
Also some minor tweaks to the Travis test.
=> Add hyperlink to hardy.uhasselt.be/Toga/live_elo

fishtest/fishtest/__init__.py, fishtest/fishtest/actiondb.py, fishtest/fishtest/templates/actions.mak, fishtest/fishtest/templates/tests_view.mak, fishtest/fishtest/templates/user.mak, fishtest/fishtest/userdb.py, fishtest/fishtest/views.py
Block/Unblock users and show eMail information
=> Add User Management for approvers

fishtest/fishtest/rundb.py
A request_task call takes about 150ms (7 per second).
The worker randomizes calls in a 1 to 30s interval.
With 200 workers or more the request queue might consume
all threads, so limit concurrency to 4 requests.
=> Limit request_task concurrency

fishtest/development.ini, fishtest/fishtest/userdb.py, fishtest/fishtest/views.py, fishtest/run_all_tests.py, fishtest/setup.py, fishtest/tests/test_rundb.py, fishtest/tests/test_users.py, fishtest/tests/util.py
- Add test iterator for server tests
- test /signup and /login
- Fix Tasks worker summary spelling: with 1 coreS
- prevent creating a user with an existing name
- update development.ini
=> Add a few pyramid tests and some minor fixes

fishtest/fishtest/views.py
minor nit.. make clear the job is submitted to the queue, will get active (start) later.
=> Improve message

fishtest/fishtest/rundb.py, fishtest/fishtest/views.py
=> Retire auto approval

fishtest/fishtest/templates/base.mak, fishtest/fishtest/templates/elo_results.mak, fishtest/fishtest/templates/run_table.mak, fishtest/fishtest/templates/tests_view.mak, fishtest/fishtest/views.py
Followup to https://github.com/glinscott/fishtest/pull/225
- Make the box variable size and as small as possible without overflow
- Add some more info to Pending runs (SPRT bounds)
- Link to Live ELO page for SPRT runs
=> Various changes to games result box

fishtest/fishtest/rundb.py
This is open for discussion. If anyone is a fan of the current code I'd like
to hear why it is useful.
When a worker disconnects from fishtest because of errors
and reconnects without being restarted (it gets a new ID
on restart) it is handed it's old job, unless it was
already assigned to another worker.
This situation is rare and the logic requires scanning all
tasks handed out.
https://github.com/glinscott/fishtest/pull/186 increased
the speed by remembering active task for each worker,
but this information is lost on a fishtest reboot.
Benefit from the current code is minimal so retire it.
=> Retire worker reconnect logic

fishtest/fishtest/__init__.py, fishtest/fishtest/api.py, fishtest/fishtest/static/html/live_elo.html, fishtest/fishtest/static/js/live_elo.js, fishtest/tests/test_rundb.py
These JSON APIs make it possible to write new (HTML) apps
without the need to parse the HTML output of fishtest.
In addition rewrite the Live ELO page to use these APIs with a lot of support from Michel Van den Bergh.
=> Add active_runs and get_run APIs

fishtest/fishtest/views.py
Fix error on approve/modify test when not logged in
After login return to the main page.
Without this fix:
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)
=> Fix error on modify/approve test when not logged in

fishtest/fishtest/__init__.py, fishtest/fishtest/templates/pending.mak, fishtest/fishtest/views.py, fishtest/utils/scavenge.py
Show users which never started a worker or created a test on the pending page.
Add periodic cleanup to scavenge.py
See https://github.com/glinscott/fishtest/pull/234
=> List idle users and periodic cleanup

fishtest/fishtest/actiondb.py, fishtest/fishtest/rundb.py, fishtest/fishtest/templates/actions.mak, fishtest/fishtest/views.py, fishtest/tests/test_rundb.py, fishtest/tests/test_users.py, fishtest/tests/util.py
This is an alternative for https://github.com/glinscott/fishtest/issues/237
Allow searching on action type and/or username.
Also clean up some named parameter white space issues.
=> Add search to actions

fishtest/fishtest/views.py, fishtest/tests/test_run.py
In addition jump to the created test page
instead of the home page after creating a test.
Should also fix https://github.com/glinscott/fishtest/issues/247
=> Enter commit info into test info field when left blank

fishtest/fishtest/templates/tests_run.mak, fishtest/fishtest/views.py, fishtest/tests/test_run.py
Small cosmetic addition to previous PR
=> Add hint and strip info field

fishtest/setup.py
=> Add numpy to setup.py

fishtest/fishtest/rundb.py
by not computing the summary when it is not stored.
Also remove some old optimization code which does no
longer make sense after the introduction of the run cache.
=> Cleanup SPSA calculation

fishtest/fishtest/userdb.py
Found while stress testing with pypy
=> Fix race condition in get_pending()

fishtest/fishtest/views.py
=> Remove default STC from fill, as suggested in #248

worker/games.py, worker/test_worker.py
This is an emergency fix for the problems caused by a mistake by me.
Since at the moment I am not able to fresh install on a VM, I will check whether I can test it on the dev server, or I hope somebody can check this quickly.
=> Fix for empty items download

fishtest/fishtest/userdb.py
because threads are waiting for lookups > 50% of the time
See http://vmprof.com/#/48225b9c-d12c-4d14-96ce-bed6442eeaea?id=1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,2&view=flames (before this PR and #261 update_task takes almost 30% of the time)
and
http://vmprof.com/#/0c662771-0c65-4f67-bcc4-8483b546f2ff?id=1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,3&view=flames (now 10% of the time)
=> Cache MongoDb user lookups

fishtest/fishtest/rundb.py, fishtest/fishtest/views.py
and release the semaphore
Should reduce the impact of transient errors, but does not fix the root cause.
See #277 
Note that diff looks impressive, but "git diff -w" shows that only a "try/except" was added...
=> Catch exception when building Overview

fishtest/fishtest/rundb.py
and cache non dirty runs for 60s (was 10s)
See  #277
=> Reduce mongodb write pressure

fishtest/fishtest/views.py
=> Fix error for stop/delete when not logged in

fishtest/fishtest/rundb.py
between update_task and request_task.
This prevents SPSA tasks with 251/250 played,
because SPSA workers will always play 2*concurrency games
and request_task overwites the
return {'task_alive': task['active']}
from update_task, causing one more game to be played.
=> Fix race on task['pending']

fishtest/fishtest/templates/user.mak
=> Add link to user tests on Profile page

fishtest/fishtest/templates/user.mak, fishtest/fishtest/views.py
=> Show more info on user profile page

fishtest/fishtest/views.py
=> Fix LTC tag for generated test info

fishtest/fishtest/views.py
Without this fix stopping and restarting run by 'modify' will fail to complete unfinished tasks.
See: http://tests.stockfishchess.org/tests/view/5b003e690ebc5914abc12641
=> Make incomplete chunks pending on modify

fishtest/fishtest/templates/run_table.mak
and add username mouse-over popup
See #304
=> Usernames from 2 to 3 characters

fishtest/fishtest/api.py, worker/games.py
This will reduce the message size and speedup request_task API.
=> Drop task list from request_task

worker/games.py, worker/test_worker.py
=> Fix worker empty book download

fishtest/fishtest/templates/run_table.mak
=> Break long words in table info

fishtest/fishtest/views.py
=> Limit num_games to max 1000000

worker/test_worker.py, worker/updater.py, worker/worker.py
Should fix https://github.com/glinscott/fishtest/issues/368
=> fix restart name conflict

fishtest/fishtest/api.py
Force the workers update in fishtest
=> Raise worker version to 69 (server side)

AUTHORS, fishtest/utils/scavenge.py
=> Update AUTHORS and disable scavenge_users() until fixed

fishtest/fishtest/views.py
Should fix #324 
Needs some testing, @Rocky640 could you test this on https://dfts-0.pigazzini.it/tests when @ppigazzini confirms it can be tested?
=> Fix https://github.com/glinscott/fishtest/issues/324

fishtest/fishtest/models.py, fishtest/fishtest/userdb.py, fishtest/fishtest/views.py, fishtest/setup.py
Fix also multiple appends to this group.
See https://github.com/glinscott/fishtest/pull/390#issuecomment-529240655
And fix Travis build by Python 2.7 compatible numpy/scipy
=> Remove unused admins group code and fix Travis build

fishtest/fishtest/views.py
instead of relying on some auto_purge actions
See #395
=> Immediately stop runs

fishtest/utils/purge_pgn.py
Skip runs older than 30 days
See also https://github.com/glinscott/fishtest/pull/393#issuecomment-534154127
=> Optimize purge_pgn.py

fishtest/fishtest/views.py
This was broken by
https://github.com/glinscott/fishtest/pull/392
and should fix #400
=> Handle users which are not logged in

fishtest/fishtest/templates/tests_run.mak
=> Update bounds when clicking STC/LTC buttons

fishtest/start.sh, fishtest/start_dev.sh, fishtest/utils/backup.sh
Use UTC, fix sh style, remove pointless cd command, improve comment.
=> Improve sh scripts

fishtest/fishtest/templates/tests_view.mak, fishtest/fishtest/views.py
remove test for obsolete worker version
remove redundant line for tests_stop()
leading 0's for Played (better sorting)
=> Small cleanups

fishtest/fishtest/templates/run_table.mak, fishtest/fishtest/templates/tests.mak
So one does not have to visit the individual test page
=> Show number of cores for active tests

fishtest/fishtest/templates/users.mak
Align numeric columns to right for easier readibility.
=> Align numeric columns to right.

fishtest/fishtest/views.py
Use blue instead of green for passed simplifications
=> Use blue instead of green for passed simplifications

fishtest/fishtest/views.py
=> Fix blue colouring for non sprt tests

fishtest/production.ini
Setup Pyramid according to [The Pyramid Community Cookbook](https://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/deployment/nginx.html).
=> Setup Pyramid to work with nginx

fishtest/utils/backup.sh
Update the backup script to work with Ubuntu 18.04 and python virtual environment.
=> Update the backup process for Ubuntu 18.04

fishtest/fishtest/api.py, fishtest/fishtest/templates/base.mak, fishtest/setup.py, worker/games.py, worker/worker.py
Should fix #133 issue:
Mixed Content: The page at 'https://dfts-0.pigazzini.it/tests' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.8.3.js'. This request has been blocked; the content must be served over HTTPS.
=> Replace jquery http source with https and make worker https ready

fishtest/setup.py
boto is the AWS python interface required for the backup process.
Merge after https://github.com/glinscott/fishtest/pull/383 to avoid conflict.
=> Add boto package to fishtest setup

worker/worker.py
See #412 
@noobpwnftw I have not tested this, but it could be as simple as this?
Is this sufficient and could you test it?
=> exit on existance of signal file

fishtest/utils/move2old_runs.py
Move runs to "old_runs" when older than 100 days
See https://github.com/glinscott/fishtest/pull/433
=> Add a script to copy runs to old_runs

fishtest/fishtest/rundb.py
See https://github.com/glinscott/fishtest/pull/437#issuecomment-557878608
=> Speedup machines MongoDb query

fishtest/fishtest/templates/tests_view.mak
Eg: http://tests.stockfishchess.org/tests/view/511c69688f0c3e39b391362e
=> Handle some 2013 runs without 'worker_info'

fishtest/fishtest/views.py
Prevent sqrt of negative number or divide by zero.
=> Prevent sqrt of negative or divide by zero.

fishtest/utils/test_queries.py
Enhance test_queries.py to include explains and to test hints.
=> Enhance test_queries.py to include explains and to test hints

fishtest/utils/create_indexes.py
First go at a script to recreate the indexes in the fishtest db.
=> Script to create indexes.

fishtest/fishtest/userdb.py
=> Retire unused 'old_user_cache' MongoDb collection

fishtest/fishtest/rundb.py
Suggested by @ppigazzini 
See https://github.com/glinscott/fishtest/pull/455
=> Small speedup of SPSA by removing unneeded code

fishtest/utils/create_indexes.py
Already dropped it by hand on prod because it is no longer needed
=> drop deleted index on runs

fishtest/fishtest/api.py
Force the workers update in fishtest
=> Raise worker version to 70 (server side)

fishtest/utils/create_indexes.py
See https://github.com/glinscott/fishtest/pull/444#issuecomment-562833654
=> Drop another MongoDb index

fishtest/fishtest/rundb.py
Clip a value in a range using an if statement instead that a double function calls.
Drop some if statements and rewrote the rounding code as an oneliner.
The new rounding code has the same probabilistic behavior of the old code, results are equal if mirroring the random variable (but the code in that case will be a little slower).
Code simplification removing unnecessary variables.
=> Small SPSA speedup with several code improvements

fishtest/utils/create_indexes.py, fishtest/utils/test_queries.py
=> Fix create_indices for Python 3

fishtest/fishtest/templates/base.mak, fishtest/fishtest/views.py
=> Red color when pending users

fishtest/fishtest/templates/signup.mak
Update the public key after the owner change.
Private key updated by hand.
=> Update reCAPTCHA public key

fishtest/fishtest/views.py
Extend to matrix operations the original idea by @xoto10
=> Fix "divide by zero" warnings improving chi2 computation for unusual cases

fishtest/fishtest/views.py
See https://github.com/glinscott/fishtest/pull/373
=> favicon.ico and robots.txt independent from CWD

worker/games.py, worker/test_worker.py
Switch to new repo and download zipped books.
To be tested after the merging of these PRs https://github.com/official-stockfish/books/pull/1 https://github.com/official-stockfish/books/pull/2.
Anyway it's working fine with my up to date books repo.
=> Switch to new books and binaries repo

fishtest/fishtest/templates/tests_stats.mak
Note that here WL really means WL+LW.
If p5[0..2] are the pentanomial probabilities and d
is the draw ratio then the probability of DD is equal to
dd=d-(p5[1]+p5[3])/2.
The probability of WL is then equal to
p[2]-dd.
=> On the raw stats page give estimates for the DD and WL probabilities.

fishtest/fishtest/templates/tests_stats.mak
Took me a while to find the draw ratio. Explicitly use the term.
=> Clarify 'distribution' in auxiliary stats.

fishtest/fishtest/templates/tests_run.mak
To be tested after the merging of these PRs official-stockfish/books#1 official-stockfish/books#2.
It's working fine with my up to date books repo.
=> Set new book default

fishtest/fishtest/static/html/SPRTcalculator.html, fishtest/fishtest/static/js/calc.js, fishtest/fishtest/static/js/sprt.js, fishtest/fishtest/templates/base.mak
In this way it becomes easier to maintain.
The SPRT calculator has been updated to use logistic Elo. Moreover some input validation was added.
=> Import the javascript SPRT calculator by Henri Wiechers in Fishtest.

fishtest/fishtest/static/html/SPRTcalculator.html, fishtest/fishtest/templates/tests_stats.mak
The new version of the SPRT calculator is here. 
http://hardy.uhasselt.be/Toga/SPRTcalculator.html
Feel free to comment.
=> Add explanations to the SPRT calculator.

fishtest/fishtest/views.py
=> Write database after purge

fishtest/fishtest/static/html/SPRTcalculator.html, fishtest/fishtest/static/js/calc.js, fishtest/fishtest/static/js/sprt.js, fishtest/fishtest/templates/base.mak
Google Charts are already used at other places in Fishtest and people are familiar with it.
The latest version can be found here.
http://hardy.uhasselt.be/Toga/SPRTcalculator.html
=> Rewrite the SPRT Calculator using Google Charts.

fishtest/fishtest/views.py
Lower the p-value to limit the numner of autopurge with the high throughput of the framework.
=> Lower p-value to 0.001

fishtest/fishtest/views.py
```
modify: priority changed from -1 to 0,throughput changed from 100 to 50
```
should have a space after ','
=> Fix bad formatting for multiple modifications

fishtest/fishtest/api.py, fishtest/fishtest/templates/tests_view.mak, fishtest/fishtest/views.py
=> Add simple purge (audit) log

fishtest/fishtest/stats/LLRcalc.py, fishtest/fishtest/stats/stat_util.py, fishtest/fishtest/templates/tests_stats.mak
Cleanups of SPRT handling in stat_util.py.
Remove a bit of code duplication.
Use """ """ style doc strings.
Document the LLR approximations we use in the raw_stats page.
=> Various stats tweaks.

fishtest/fishtest/__init__.py, fishtest/fishtest/actiondb.py, fishtest/fishtest/api.py, fishtest/fishtest/models.py, fishtest/fishtest/rundb.py, fishtest/fishtest/stats/brentq.py, fishtest/fishtest/userdb.py, fishtest/fishtest/views.py, fishtest/tests/test_run.py, fishtest/tests/test_rundb.py, fishtest/tests/test_users.py, fishtest/tests/util.py
=> Various cleanups (pylint)

fishtest/fishtest/rundb.py
Flush buffers on signals and
Reduce log warnings:
Jan 30 17:03:07 tests pserve[31906]: 2020-01-30 17:03:07,583 WARNI
[waitress.queue][MainThread] Task queue depth is 10
Jan 30 17:03:07 tests pserve[31906]: 2020-01-30 17:03:07,612 WARNI
[waitress.queue][MainThread] Task queue depth is 10
Jan 30 17:03:07 tests pserve[31906]: 2020-01-30 17:03:07,660 WARNI
[waitress.queue][MainThread] Task queue depth is 1
Jan 30 17:03:07 tests pserve[31906]: 2020-01-30 17:03:07,660 WARNI
[waitress.queue][MainThread] Task queue depth is 2
Jan 30 17:03:07 tests pserve[31906]: 2020-01-30 17:03:07,677 WARNI
[waitress.queue][MainThread] Task queue depth is 2
=> Reduce queueing when MongoDb is under load and flush buffers on signals

worker/games.py
This was suggested by @vondele at fishcooking.
=> Keep the trinomial and pentanomial frequencies in sync (worker change).

fishtest/fishtest/rundb.py, fishtest/fishtest/stats/stat_util.py, fishtest/fishtest/views.py
This will hopefully fix the occasional loss of overshoot data.
=> Make it so that the sprt object is only updated in a single location.

fishtest/utils/create_indexes.py
To speed up queries, especially for non existing users
=> Add index on username to actions

fishtest/fishtest/templates/tests_run.mak
add single click SMP options.
8 threads, 5+0.05, 64Mb
8 threads, 20+0.2, 256Mb
fixes https://github.com/glinscott/fishtest/issues/384
Untested.... copy&paste from similar code around, would need a careful check.
No so urgent either.
=> Single click SMP tests

fishtest/fishtest/templates/tests_view.mak
@vondele this is an update to the "Master diff" link in the actions sidebar section for pending tests as you suggested here: https://github.com/glinscott/fishtest/pull/558#issuecomment-610022442
The client will check the diff between the base branch of the submitted test and official Stockfish master. If there's no difference, it shows a green success message. Otherwise, a red error message.
---
If there's no difference between the base branch and official Stockfish master:
---
If the base branch doesn't match official Stockfish master:
=> Show result of comparing base branch with master on pending tests

fishtest/fishtest/views.py
Should fix #579 
@linrock You moved the setting of the button states from client-side cookie inspection to server side.
This PR patches up the server cached state, but what is/was the reason to moving this server side?
EDIT: @linrock If you think it's better to restore the old client-side handling instead of this PR or have other suggestions, please let me know.
=> Handle Show/Hide cookies for cached content

fishtest/fishtest/templates/run_table.mak, fishtest/fishtest/templates/run_tables.mak, fishtest/fishtest/views.py
@ppigazzini this should fix https://github.com/glinscott/fishtest/pull/591#issuecomment-613667898
=> Fix finding and setting failed runs

fishtest/fishtest/templates/tests_view.mak
see https://github.com/glinscott/fishtest/issues/590#issuecomment-613887787
=> Fix "javascipt" typo

fishtest/utils/delta_update_users.py, fishtest/utils/update_users.py
`delta_update_users.py` runs every 15 minutes. Using `skip` for mongodb collections is inefficient and CPU-intensive for iterating through large collections. It's much more efficient to use range queries on an indexed field.
See https://docs.mongodb.com/manual/reference/method/cursor.skip/#using-range-queries
A quick benchmark on a $5 VPS:
Before:
```
Num runs processed: 74887
Successfully updated 1200 users
real	1m46.332s
user	0m22.695s
sys	0m0.744s
```
After:
```
Num runs processed: 74887
Successfully updated 1200 users
real	0m19.514s
user	0m15.732s
sys	0m0.397s
```
=> Iterate through runs using range queries in delta_update_users.py

fishtest/fishtest/actiondb.py, fishtest/fishtest/api.py, fishtest/fishtest/rundb.py, fishtest/fishtest/userdb.py, fishtest/tests/test_rundb.py
Fixes most of those pymongo warnings when running tests, as seen here https://github.com/glinscott/fishtest/pull/589#issuecomment-613717674
a few of the warnings are fixed in https://github.com/glinscott/fishtest/pull/574 so i won't fix them here to avoid a merge conflict
=> Fix some pymongo deprecation warnings

worker/updater.py, worker/worker.py
Also raise worker version to 74 worker side
=> Fix timestamp for python2 (raise version to 74)

fishtest/fishtest/templates/tests_run.mak
As suggested by @snicolet in https://github.com/glinscott/fishtest/pull/572#issuecomment-615969657
---
=> Center header text on 'create new test' page

fishtest/fishtest/templates/base.mak, fishtest/fishtest/views.py
error messages across the site will show up as red as suggested by @vondele in https://github.com/glinscott/fishtest/pull/572#issuecomment-615124753
---
=> Show error messages in red instead of green

fishtest/utils/delta_update_users.py
Should fix https://github.com/glinscott/fishtest/issues/605
See https://github.com/glinscott/fishtest/issues/605#issuecomment-617153470
=> Fix cpu stats calculation without a slowdown

fishtest/fishtest/helpers.py, fishtest/fishtest/templates/tests_view.mak
Otherwise the diff is always blank since the test and base branches are the same.
=> Link to master diff for SPSA runs

fishtest/utils/purge_pgn.py
=> Fix order for purging PGNs

fishtest/fishtest/api.py
Guard against slow or unavailable flag server
See https://github.com/glinscott/fishtest/issues/553#issuecomment-619777152
=> Limit concurrent flag queries

worker/games.py
Worker changes to allow batching.
A new quantity "batch_size" is defined.
In principle batch_size is the number of games that have to be completed by the worker before an update is sent to the server. However for sprt and numgames tests it is actually twice the number of completed game pairs.
batch_size for sprt is communicated by the server. The reason is that for the sprt algorithm to be theoretically correct all workers have to use the same batch size.
For other tests batch_size is currently set by the worker to twice the number of games it is capable of running concurrently.
This is equal to the number of cores reserved for the worker, divided by the number of threads used by the engines.
=> Worker changes to allow batching.

fishtest/fishtest/api.py
Update all workers to version 75 before merging
https://github.com/glinscott/fishtest/pull/627
=> Raise worker version to 75 (server side)

fishtest/fishtest/api.py
Code cleanup https://github.com/glinscott/fishtest/pull/657
=> Raise worker version to 76 (server side)

fishtest/fishtest/rundb.py, worker/worker.py
=> Limit worker API usage

fishtest/fishtest/userdb.py
See https://github.com/glinscott/fishtest/issues/674
=> Change default machine limit to 16

fishtest/fishtest/rundb.py
Speedup by dropping tasks from unfinished_runs query
See #677
=> Query for unfinished_runs with only the id attribute

fishtest/production.ini
@ppigazzini prevents filling up the log.
=> Less logging: no task queue warnings

fishtest/fishtest/helpers.py, fishtest/fishtest/views.py, worker/games.py, worker/worker.py
avoids rare cases where 7 is not enough.
Fixes https://github.com/glinscott/fishtest/issues/688
=> Use 10 digits of the sha

fishtest/fishtest/templates/tests_view.mak
fix a mised case in the templates.
=> Use 10 digits of the sha. Part 2.

fishtest/fishtest/views.py
=> Add error check for time control

worker/worker.py
Should fix EDIT:  https://github.com/glinscott/fishtest/issues/685
Also reduce some line lengths to less than 80 chars
@ppigazzini I tested this with python 2 and 3 workers, but not with a PGN containing non-utf8 characters. Perhaps you can create one with a particular Windows setting? If not then it's OK for me to commit and let @kotenok2000 test?
=> Strip non utf-8 characters from PGN files

fishtest/fishtest/templates/signup.mak, fishtest/fishtest/views.py
triggered by a message on fishcooking: https://groups.google.com/g/fishcooking/c/41mKxgCwzc0/m/TSN7VxU6BgAJ and after having seen multiple duplicate registrations.
=> Improve signup message

fishtest/fishtest/views.py
=> Handle longer (> 7 digits) bench signatures

fishtest/fishtest/views.py, fishtest/utils/compact_actions.py
to save a LOT of space
Should fix #710
=> Remove tasks from run data in actions

worker/games.py
This is mainly meant for SPSA tunes. It is easy to set up an SPSA tune incorrectly so that in fact no tuning is done.
Note: to make this work I had to redirect stderr of cutechess-cli to stdout. I assume this is harmless but it should be kept in mind.
=> Try to stop test after a cutechess warning

fishtest/fishtest/api.py, fishtest/fishtest/views.py
Supports https://github.com/glinscott/fishtest/pull/722
=> Add failed flag for runs

fishtest/fishtest/api.py
Should fix https://github.com/glinscott/fishtest/issues/721#issuecomment-659642277
=> fix strip_run()

worker/games.py
- Open the standard streams in text mode and retire the encode function
- Redirect the stdout to devnull
- Close the stderr
- Keep the python 2.x compatibility
=> Improve the subprocess usage

fishtest/fishtest/__init__.py, fishtest/fishtest/actiondb.py, fishtest/fishtest/api.py, fishtest/fishtest/rundb.py, fishtest/fishtest/templates/actions.mak, fishtest/fishtest/templates/base.mak, fishtest/fishtest/templates/nn_upload.mak, fishtest/fishtest/templates/nns.mak, fishtest/fishtest/views.py, fishtest/utils/create_indexes.py
See #733 
@ppigazzini Note that I added a new index for `nns` in `create_indices.py`
=> NN upload/download support

fishtest/fishtest/templates/nns.mak, fishtest/fishtest/templates/tests_run.mak
Minor updates to NN code:
- Align NN downloads right
- Monospace font for NN
- Smarter new test buttons
Should close #704 and #741
=> Minor NN Updates and fix test buttons

fishtest/fishtest/views.py
=> test params for SPSA (> 0)

fishtest/fishtest/api.py, fishtest/fishtest/rundb.py, fishtest/fishtest/templates/tests_view.mak, fishtest/tests/test_rundb.py, worker/games.py
=> Send ARCH to server

worker/games.py, worker/test_worker.py
Download net before building, copy from cache if possible
=> Prepare for PGO builds with hybrid bench

fishtest/fishtest/views.py
=> Handle upload timeouts/retries

fishtest/fishtest/rundb.py, fishtest/fishtest/templates/nns.mak, fishtest/fishtest/views.py
=> Update NN database with usage

fishtest/utils/delta_update_users.py
Last active is not updated for users not active last 30 days
=> Fix last active

fishtest/fishtest/rundb.py
Use update_one to prevent overwriting downloads updates
=> Rewrite update_nn

fishtest/fishtest/rundb.py, fishtest/fishtest/views.py
Implements https://github.com/glinscott/fishtest/issues/770
=> Show Net info for tests

worker/games.py
adjust to master makefile with avx512 vnni
Non-urgent worker change
=> Detect vnni targets

fishtest/fishtest/__init__.py, fishtest/fishtest/rundb.py, fishtest/fishtest/stats/LLRcalc.py, fishtest/fishtest/stats/brownian.py, fishtest/fishtest/stats/sprt.py, fishtest/fishtest/stats/stat_util.py, fishtest/fishtest/util.py, worker/games.py
black --exclude worker/requests .
isort --profile black --skip worker/requests .
black, version 20.8b1
isort, version 5.4.2
=> Use latest black and isort to reformat code

worker/games.py
each worker uses a unique subset of the opening book, which is randomized with a consistent seed on all workers.
fixes https://github.com/glinscott/fishtest/issues/478
Needs a recent cutechess (1.2).
=> Use unique openings

worker/games.py, worker/updater.py, worker/worker.py
Make the worker code more consistent using only the format method to formatting
the strings.
=> Use the string format method

fishtest/fishtest/rundb.py
Currently many Paused tests have cores > 0.
This PR should fix that.
=> Set cores to "0" for pending runs

fishtest/fishtest/views.py
Fix #815 for now.
Maybe add paging/search later.
=> List 500 NN entries

fishtest/fishtest/rundb.py, fishtest/fishtest/static/js/application.js, fishtest/fishtest/templates/base.mak, fishtest/fishtest/templates/nns.mak, fishtest/fishtest/views.py
@vondele As a followup to #816 some quick paging. Not sure if we really need this, `/users` is more than 1000 entries and works fine too, but better safe than sorry.
@ppigazzini I did some creative testing of this. You could lower page_size by hand on dev to 100 for testing....
=> Add NN paging and show/hide non default nets

fishtest/fishtest/rundb.py
=> Make flush cache more robust and fix pentanomial

fishtest/fishtest/rundb.py
Fix a race condition the right way
and increase cache timeout from 60s to 300s because we have various timers ticking every 60s, so we might sometimes free a cache entry and reload it immediately.
=> Fix race condition, cache cleanup and obsolete Mongo API calls

server/fishtest/rundb.py
See https://github.com/glinscott/fishtest/pull/832#issuecomment-715900620
=> Delay scavenge on boot

worker/games.py, worker/worker.py
See https://github.com/glinscott/fishtest/pull/836#issuecomment-716122229
=> Replace sys.exit() by os._exit() to stop heartbeat

test_server.sh, test_worker.sh
Updating this script since the server directory was renamed from `fishtest` to `server`
=> Fix test_server.sh to use new server directory

worker/worker.py
See discussion at https://github.com/glinscott/fishtest/pull/838
=> Add --fleet/--use_all_cores worker option

server/fishtest/rundb.py
=> Flush task info

server/fishtest/api.py, worker/worker.py
See https://github.com/glinscott/fishtest/issues/851#issuecomment-723424511
=> Add unique_key for failed_task API call

worker/worker.py
check that gcc is >= 7.3
fixes https://github.com/glinscott/fishtest/issues/859
=> gcc version check

server/fishtest/api.py, worker/games.py, worker/worker.py
=> Show worker UUID and handle heartbeat exception

server/fishtest/templates/tests_run.mak
start from 1000 in steps of 1000. Useful for some very quick tests.
=> Allow finer control on num games tests

server/fishtest/templates/tests_stats.mak
Display the batch size on the raw statistics page.
Add the LLR jumps to the raw statistics page.
This is something I wanted to do for a long time already. Sometimes a test finishes with an LLR of >3 (without it having been purged). We can now check if this is reasonable.
It was only tested locally with an SPRT test.
=> More stats auditing.

README.md
See the [official documentation](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge)
=> Add Actions workflow status badge

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/stats/sprt.py, server/fishtest/stats/stat_util.py, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/tests/test_users.py, server/utils/compact_actions.py, server/utils/purge_pgn.py, worker/worker.py
`black --exclude=worker/requests .`
`isort --profile black --skip worker/requests .`
=> Reformat code with black and isort

server/fishtest/api.py, worker/worker.py
Also raise worker version and trigger workers update
=> Show complete python version

server/fishtest/api.py, worker/games.py, worker/worker.py
Search only in the first subfolder level.
Also raise the workers version and trigger the workers update.
Fix #889
=> Fix "src/" folder search

AUTHORS
=> Update authors list as March 29, 2021

AUTHORS
=> Update authors list as Aprile 10, 2021

worker/worker.py
Trigger heartbeat thread exit on exceptions.
=> Stop the heartbeat when stopping the worker

AUTHORS
=> Update authors list as June 03, 2021

server/fishtest/views.py
Functionally equivalent. In preparation for some future changes to the signup function
=> Improve readability

AUTHORS
=> Update authors list as June 20, 2021

worker/games.py
noob reports 20% slowdown compared to avx2
=> Disable AVX512 for now.

server/fishtest/templates/base.mak
The invite link used is from here https://github.com/official-stockfish/Stockfish/issues/2345
=> Add Discord link

server/fishtest/templates/base.mak
Also update the link pattern for other googlegroups.
=> Updated the History link to new tests results googlegroups

AUTHORS
=> Update authors list as June 26, 2021

server/fishtest/static/css/theme.dark.css, server/fishtest/static/js/application.js
Some contrast adjustments of dark mode.
=> Adjustments of dark mode

README.md
Markdown from "Create status badge" under "..." menu, see
https://github.com/glinscott/fishtest/actions/workflows/main.yaml
=> Update GitHub workflow status badge

server/fishtest/templates/machines_table.mak, server/fishtest/util.py
Show only the first UUID group of hex digits
=> Show the worker UUID in machines/tasks tables

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/stats/LLRcalc.py, server/fishtest/stats/sprt.py, server/fishtest/stats/stat_util.py, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/tests/test_users.py, server/utils/compact_actions.py, server/utils/delta_update_users.py, server/utils/purge_pgn.py
black server
isort --profile black server
=> Reformat server code with black and isort

worker/worker.py
Passwords with % can now be handled on terminal. Fixes #79
=> Fix password parsing with configparser

AUTHORS
=> Update authors list as August 4, 2021

server/fishtest/templates/base.mak
Also shorten the name of the NNUE-PyTorch repo
=> Add link to Books repo

worker/games.py
Reverts glinscott/fishtest#992
=> Revert "Stop the test after failing to setup an engine"

server/fishtest/templates/tests_run.mak
Switches to a new book by Stefan Pohl: UHO_XXL_+0.90_+1.19.epd
See
https://github.com/official-stockfish/books/commit/63b0f2095923d98d4dcb6d7b0ee79404f83c4270
See discussion and tests in
https://github.com/official-stockfish/Stockfish/issues/3323
=> Update to a new default book

server/fishtest/templates/base.mak
Make the defaults for the SPRTcalculator compatible with the new book.
=> Make the defaults for the SPRTcalculator compatible with the new book.

server/fishtest/util.py
Currently the chi2 test assumes that the games in a task are independently drawn from a trinomial distribution. This assumption is no longer valid for an unbalanced book. This is very visible from the p-values which are often > 99%. Under the null hypothesis p-values should be uniformly distributed.
Since currently the ww and ll frequencies will be too small for the chi2 test to be valid, we coalesce them with the wd and ld frequencies.
The main test page still shows the trinomial wdl frequencies. This will be addressed in a separate PR.
=> Correct the chi2 p-value computation for an unbalanced book.

server/fishtest/templates/tests_view.mak
Show the pentanomial frequencies on the main test page.
=> Show the pentanomial frequencies on the main test page.

worker/games.py
This enables the use of asymmetric TC in the worker. This is potentially useful for book testing. 
Of course this PR is non functional change as long as the server does not give appropriate instructions to the worker.
The server changes will be included in a separate PR.
=> Enable asymmetric TC in worker.

server/fishtest/static/css/theme.dark.css, server/fishtest/static/js/application.js, server/fishtest/templates/elo_results.mak
Closes https://github.com/glinscott/fishtest/pull/1008
=> Dark mode refinements

server/fishtest/api.py, worker/games.py, worker/worker.py
=> Report the name of the worker when stopping a run

server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/templates/tests_view.mak, server/fishtest/util.py, server/tests/test_api.py, server/tests/test_rundb.py, worker/games.py, worker/worker.py
We start with an empty task list and create new tasks as needed.
This incorporates #1020. 
There is now an attempt to create tasks which take about 15 minutes to complete.
I did some limited local testing (randomingly starting and stopping workers).
=> Dynamic tasks

server/fishtest/rundb.py
Bugfix! I broke Joona's algorithm :frowning_face: 
Resorting is important because the task queue is only regenerated every minute.
The resorting was accidentally deleted in the commit "dynamic_tasks".
=> Resort the task queue after a task has been assigned.

server/fishtest/rundb.py
Bugfix: the current code (like the old code) may not pick up changes of `run["cores"]` due to finished tasks.
More precisely: if a cached version of `task_runs` is not sorted at the beginning of `request_task()` its first entry may be a run which does not have the lowest value of `run["cores"]/run["itp"]` because it may be that since the last call to `request_task()` one or more tasks in other runs finished (handled in `update_task()`).
Also some cosmetic changes around the `request_task()/update_task()` code.
=> Sort "task_runs" at the correct place.

server/fishtest/rundb.py
Currently there is the issue that high core workers always get the same run while their residual keeps steadily rising.
This is not good. We want a good hardware mix for every test.
This PR moves the last run seen by the worker to the end of the queue.
Not live tested.
=> Try to find a new run for a worker in request_task().

server/fishtest/rundb.py
In master "request_task()" is a large for loop which contains a large if. We get rid of the if. This makes the code much more readable.
The new structure is
```
run_found=False
for run in self.task_runs:
if excluding_condition1:
continue
if excluding_condition2:
continue
...
run_found=True
break
if not run_found:
return
(now create a new task for the run that was found)
```
This should be a non-functional change.
=> Document and refactor request_task.

server/fishtest/templates/tests_view.mak
Not live tested (I don't have the old tests).
=> Write "-" for the worker name for workers without worker_info.

server/fishtest/__init__.py, server/fishtest/views.py, server/setup.py
Used these two references to figure out the new APIs. I didn't find any useful upgrade guides otherwise:
- [pyramid sessions reference](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/sessions.html)
- [pyramid.security API reference](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/security.html)
Fixes https://github.com/glinscott/fishtest/issues/887
=> Upgrade pyramid from 1.10 to 2.0

server/fishtest/rundb.py, server/fishtest/util.py, server/fishtest/views.py
The computation of bad_workers is now done inside purge_run(), where it logically belongs.
As a side effect of the refactoring it is now easy to have different purging criteria for auto purging and manual purging.
As a proof of concept we have set the purging criteria for manual purging to p=0.01 and residual=4.5, whereas for auto purging (disabled by default) we have set them to p=0.001 and residual=7.0.
We also use a different logic for computing residuals because the previous residuals (defined as the maximum of the absolute values of the Pearson adjusted residuals in a row) have an unknown distribution. Now we compute (conceptually) for every row in the chi2 table the chi2 value of the 2x3 table obtained by that row and the sum of the other rows. This chi2 value follows a chi2 …
=> Refactor purging logic and overhaul the residuals computation.

server/fishtest/rundb.py, server/fishtest/util.py
The new purging logic purges workers (based on their residuals), not tasks. So the current code which sets the residual to 8 for a task with several crashes has no effect anymore (since it does not change the residual of the worker).
The implemented solution is to start `purge_run()` with a loop which filters tasks with crashes and time losses, and then to compute the worker based residuals (since these will be affected by the preliminary filtering).
Fixes #1058.
=> Suggested fix for #1058.

server/fishtest/api.py, worker/worker.py
Raise also server side.
First update to rename the "requests" directory to "_requests".
=> Raise worker version to 110: drop old "requests"

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/tests/test_rundb.py, worker/games.py
```
black --exclude=worker/packages .
isort --profile black --skip worker/packages .
```
=> Auto format files with black and isort

server/fishtest/stats/sprt.py
=> Fix typo in string format

server/fishtest/util.py
Of course this is a non-functional change.
=> Add explanatory comments about the computation of residuals.

server/fishtest/static/css/theme.dark.css, server/fishtest/templates/tests_run.mak
- Use new bootstrap input classes
- Keep input fields within container width when toggling time odds
- Fix some spacing around inputs and labels
=> Styling tweaks for create new test page

worker/games.py, worker/test_worker.py, worker/worker.py
Get rid of all calls to worker_exit().
Eliminate global variable "config".
Move all parsing of parameters to setup_config_file().
Rename main() to worker().
Refactor adjust_tc.
=> More refactorings.

server/fishtest/actiondb.py, server/fishtest/rundb.py, worker/games.py, worker/test_worker.py, worker/updater.py, worker/worker.py
Also format the project files with:
```
black --exclude=worker/packages .
isort --profile black --skip worker/packages .
```
=> Drop Python2 support from worker

worker/games.py
With this PR the correct message is used even if the user presses `Ctrl-C` (in which case "Terminated by signal" is used). This is done by equipping `WorkerException` with an optional argument `e`. If `e` is of the type `WorkerException`, or a subclass of it then it will be forwarded. We use some `__new__` hackery for this.
This PR establishes a pattern for cases where forwarding inner exceptions is useful.
We use it at three places
- in requests_get()
- in requests_post()
- while wrapping the main make command.
The general idea is to gradually replace the `Exception at games.py:xxx` messages in the action log with meaningful messages.
Also for consistency: two more `FatalExceptions` when handling cutecess.
=> Do not mask Ctrl-C when wrapping a call.

server/fishtest/templates/machines_table.mak, server/fishtest/templates/tests_view.mak
=> Show worker RAM in home and test pages

worker/worker.py
On the server it can then be included in the info string of the workers.
=> Send the gcc version to the server as part of the worker_info.

server/fishtest/static/html/live_elo.html
Sorry for the inconvenience
If you want, test it on dev first to make sure it works as expected now
=> Live elo changes

server/fishtest/static/js/application.js
=> Drop two function calls using variables in js

worker/games.py
This will catch unsupported architectures.
=> Do the check for a working cutechess_cli before building SF.

server/fishtest/templates/actions.mak, server/fishtest/templates/base.mak
With the logging of api calls from the worker this seems more accurate.
=> Change "Actions" to "Events".

worker/worker.py
The start of the worker is racy. So after a small delay we verify that our lock file has not been overwritten by another worker. This will immediately detect duplicate workers, except on extremely slow systems.
This can be tested with the script
```
python worker.py &
python worker.py
```
where the line `python worker.py &` can be repeated as many times as desired.
=> Catch duplicate workers early on.

worker/games.py, worker/worker.py
Maybe we can understand the error.
=> Send errors when the cutechess version info is not found.

server/fishtest/rundb.py, server/fishtest/templates/tests_run.mak, server/fishtest/views.py, worker/games.py, worker/worker.py
=> Checkbox to disable adjudication.

server/fishtest/views.py
might be needed if there is a problem uploading to the server.
=> Add timeouts

server/fishtest/api.py, server/tests/test_api.py
This is the server counterpart to #1164 .
=> Final simplification of api.py.

server/setup.py
The code needs some refactoring to use the new pymongo 4.x
=> Use pymongo 3.x

server/fishtest/api.py, server/fishtest/userdb.py, server/tests/test_users.py
As a bonus we can now also return "blocked" messages.
=> Simplify authentication in api.py.

worker/games.py
=> Format large return codes in hexadecimal.

worker/games.py
`raise WorkerException(message, e=e)` with unbound `e`.
=> Bug in games.py.

worker/worker.py
The logo was generated using
https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20
using the "Doom" asci font.
```
_____ _     _     _            _                        _                                                                                   
|  ___(_)   | |   | |          | |                      | |                                                                                  
| |_   _ ___| |__ | |_ ___  ___| |_  __      _____  _ __| | _____ _ __                                                                       
|  _| | / __| '_ \| __/ _ \/ __| __| \ \ /\ / / _ \| '__| |/ / _ \ '__|                                                                      
| |   | \__ \ | | | ||  __/\__ \ |_   \ V  V / (_) | |  |   <  __/ | …
```
=> Display asci logo at startup.

worker/games.py
Also: make ARCH non-global.
It was actually used for two different things!
=> Remove a bunch of superfluous arguments from verify_signature().

worker/games.py, worker/worker.py
Trying to find a compromise between user friendly terminal messages and machine parsability is a losing battle. So we now separate the two.
For api logging we now print something user friendly on the terminal and for logging we use something more machine parsable.
We also log run/task_id since there may be a correlation between timings and the length of the run.
=> Introduce generic logging function with timestamp.

server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/templates/tests_view.mak, server/tests/test_api.py, server/tests/test_rundb.py, worker/games.py, worker/worker.py
In preparation for the db conversion we do some more cleanups.
=> Move `ARCH` and `nps` to `worker_info`.

server/fishtest/static/css/application.css, server/fishtest/static/css/flags.css, server/fishtest/static/css/live_elo.css, server/fishtest/static/css/theme.dark.css, server/fishtest/static/html/SPRTcalculator.html, server/fishtest/static/html/live_elo.html, server/fishtest/static/js/calc.js, server/fishtest/static/js/gkr.js, server/fishtest/static/js/jquery.cookie.js, server/fishtest/static/js/live_elo.js, server/fishtest/static/js/spsa.js, server/fishtest/static/js/spsa_new.js
```
npx prettier --write "server/fishtest/static/{css/*.css,html/*.html,js/*[!highlight.diff.min].js}"
```
- fix by hand some missing html tags attributes quotes that stop `prettier`
- fix some typos
=> Fix html tag attributes and auto format css, html, js files

server/fishtest/static/css/application.css, server/fishtest/templates/base.mak
=> Add Monitoring to the sidebar

worker/games.py
SF cannot handle paths with non-ascii characters on windows.
=> Do not use absolute pathname for net.

worker/games.py
This patch set the variant by reading book's name.
Based on: https://github.com/AndyGrant/OpenBench/commit/b9f86691b1be19c7f0a3a9f40c74fe0394b3f3aa
Comments on Discord: https://discord.com/channels/435943710472011776/900771437177094156/929026322913689662
=> Allow FRC testing

server/fishtest/rundb.py, server/fishtest/stats/stat_util.py, server/fishtest/templates/tests_view.mak, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/tests/test_rundb.py
Remove glue code at various places.
It should only make a difference for very old tests. So I have not been able to test this.
=> Trivial cleanups2

server/utils/create_indexes.py
Rationalize indexes according to #1242
=> Experiment: clean up indexes.

server/fishtest/templates/run_tables.mak
The current code generates incorrect html for "Unknown user".
=> Fix issue with usernames containing special characters.

worker/worker.py
The long time deprecated wmic tool was dropped in Windows 11 WIP and it
should be dropped in the next release of Windows 10 and Windows 11.
CMI cmdlets require powershell 3.0 or later, so a Windows 7 user
may need to update to a newer powershell version.
The legacy VMI cmdlets were dropped with powershell 6.0, so they are not
a viable solution to keep compatibility with old (and EOL) Windows versions.
Issue and solutions analysis by @d3vv
closes #1217
=> Switch from deprecated wmic to powershell

worker/test_worker.py, worker/worker.py
This should be a non-functional change.
=> Refactor option handling a bit.

worker/worker.py
The principle is that a broken config file should not prevent a worker to start, since errors in the config file are not obvious to diagnose. This principle was no longer valid, but this PR restores it.
Also:
Put actual values for concurrency, max_memory as comments in config file.
It now looks like:
```
concurrency = MAX-2 ; = 2 cores
max_memory = MAX/4 ; = 2849 MiB
```
Also:
Rename max to MAX and inject the function max in the parser.
As a temporary measure, for backward compatibility "max", when used as a variable, is automatically converted to "MAX", both in the config file and on the command line. When this happens a deprecation warning is given.
=> Earlier validation of `--concurrency` and `--max_memory`.

worker/worker.py
1) Show a message when a config option is preprocessed
(e.g. `max->MAX`).
2) Show defaults in the help message.
3) Correct a comment concerning the use of options from the config file as defaults.
4) Bugfix: enable comments when the config file is initialized because of a syntax error.
5) Tweak several help messages.
6) Hide the default values for flags in the help messages.
=> Some cosmetics in option handling.

server/fishtest/static/css/application.css
=> Fix info not showing in smaller screens

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/base.mak, server/fishtest/templates/run_table.mak, server/fishtest/templates/tests_run.mak, server/fishtest/templates/tests_view.mak, server/fishtest/templates/users.mak
Using more Bootstrap classes
Changed pending users icon and text
Changed grid system in test view
Increased contrast ratio of green links in light theme
Added lang (en) attribute
td inside of tr
This also reverts #1271
=> Style changes and W3

server/fishtest/static/css/live_elo.css, server/fishtest/static/html/SPRTcalculator.html, server/fishtest/static/html/live_elo.html, server/fishtest/templates/tests_stats.mak
Also update and use more Bootstrap classes
This should make the live elo, SPRTcalculator and raw statistics pages be responsive (look good on mobile devices)
=> Made some pages responsive

server/fishtest/static/html/SPRTcalculator.html
Hotfix for https://github.com/glinscott/fishtest/issues/1277#issuecomment-1038223194
=> Fix cursor positioning in the SPRT calculator

server/fishtest/__init__.py, server/fishtest/static/html/SPRTcalculator.html, server/fishtest/static/js/calc.js, server/fishtest/templates/base.mak
PR for the code snippet by dav1312 in https://github.com/glinscott/fishtest/pull/1278#issuecomment-1038462212
I tested it and it works perfectly.
=> Make the graphs in the SPRTcalculator responsive (dav1312).

worker/games.py
It is possible that the task is finished (not tested).
=> Safety check when asking for new spsa parameters.

server/fishtest/static/css/application.css, server/fishtest/templates/login.mak, server/fishtest/templates/signup.mak, server/fishtest/views.py
This also makes those 2 pages responsive by adding the meta directly into them.
If the website someday becomes fully responsive, that should be removed.
=> Login and register redesign

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/login.mak, server/fishtest/templates/signup.mak, server/fishtest/templates/user.mak
This also makes this page responsive by adding the meta directly into it.
If the website someday becomes fully responsive, that should be removed.
=> User Administration redesign

server/fishtest/static/css/application.css, server/fishtest/static/html/SPRTcalculator.html, server/fishtest/static/html/live_elo.html, server/fishtest/static/js/calc.js
```
npx prettier --write "server/fishtest/static/{css/*.css,html/*.html,js/*[!highlight.diff.min].js}"
```
=> Auto format code with prettier

server/fishtest/rundb.py, server/fishtest/templates/tests_run.mak, server/fishtest/views.py
- drop the dead (and dubious) "careful clipping" algorithm
- use "stochastic rounding"
https://en.wikipedia.org/wiki/Rounding#Stochastic_rounding
- clean up all references of "clipping" and "rounding"
=> Simplify SPSA "clipping" and "rounding" code

server/fishtest/__init__.py, server/fishtest/static/js/spsa.js, server/fishtest/templates/tests_view.mak, server/fishtest/views.py
Pass the SPSA data from mako template with a js variable.
=> Simplify code for SPSA chart

worker/games.py
In order to deal with this:
https://tests.stockfishchess.org/actions?count=1&before=1649527432.921
=> Try catch block around net download.

server/fishtest/static/css/theme.dark.css, server/fishtest/static/html/SPRTcalculator.html, server/fishtest/static/html/live_elo.html, server/fishtest/templates/base.mak, server/fishtest/templates/tests_stats.mak
font-awesome 6.1.1
jquery 3.6.0
bootstrap 5.1.3
=> Web packages update

server/fishtest/templates/tests_view.mak, server/fishtest/views.py
These are the required input values in a new SPSA test.
Closes #138
=> Add "c_end" "r_end" in SPSA table

server/fishtest/static/js/spsa.js, server/fishtest/templates/tests_view.mak
Also skip the smoothing call when the smoothing factor is
at the upper/lower limit of its range.
=> Clean up SPSA chart code

server/fishtest/static/js/spsa.js
=> Configure SPSA chart for light and dark themes

server/fishtest/api.py
Improve the process for a worker with a private IP
using the API of the GeoIP provider.
=> Change the GeoIP provider

server/fishtest/static/css/theme.dark.css, server/fishtest/static/js/live_elo.js
Thanks to @dav1312 for review and suggestions.
=> Dark style for Live Elo Gauges

server/fishtest/api.py
- little code simplification
- improve comments
- try except for a (very low probability) race condition:
workers with the same ip, without country code, accessing
simultaneously the global flag_cache
A flag_cache with 20k ip entries requires 590kB, is not necessary
to drop stale ip from the cache (see the PR for the code).
=> Refactoring of get_flag code

server/fishtest/util.py
Fix the "ValueError: too many values to unpack (expected 2)"
=> Split cookie text on first "=" occurrence

worker/worker.py
Currently the algorithm for the default `uuid_prefix` uses the MAC address. But the MAC address is unstable on modern OSes. Moreover `uuid.getnode()` seems to be buggy on a number of systems and simply returns a random number. This needs ugly and fragile workarounds.
The new algorithm uses:
1) the `machine_id` (a uuid generated during system install);
2) the absolute path of the worker;
3) a random seed which is saved in a new "private" section of the config file.
This algorithm can be defeated by cloning a cloud instance with an installed worker.
This seems like a niche case. But if it turns out that it does happen then we can work around it by detecting the resulting duplicate prefix and generating a new seed.
=> New shot at generating a stable default uuid_prefix for workers..

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/base.mak, server/fishtest/templates/login.mak, server/fishtest/templates/nn_upload.mak, server/fishtest/templates/signup.mak, server/fishtest/templates/tests_run.mak, server/fishtest/templates/user.mak
Redesign the nn upload page and make it mobile friendly
Reorder test inputs and add some placeholders
Note: in the future the tests_run page would need to be entirely redesigned too
=> Style changes

worker/worker.py
=> Make sure to import the local expression package.

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/tests_view.mak
More modern buttons, in tone with the rest of the website
=> Github diff buttons

worker/games.py
See https://tests.stockfishchess.org/actions?count=1&before=1658309580.049 .
=> Properly initialize spsa wld.

server/fishtest/templates/base.mak, server/fishtest/templates/tests_run.mak
introduce new bounds, requiring more games to pass, but makes passing more feasible.
=> New SPRT bounds

server/fishtest/static/css/application.css, server/fishtest/static/css/live_elo.css, server/fishtest/static/css/theme.dark.css, server/fishtest/static/js/live_elo.js, server/fishtest/templates/login.mak, server/fishtest/templates/nn_upload.mak, server/fishtest/templates/signup.mak, server/fishtest/templates/tests_view.mak, server/fishtest/templates/user.mak
Dark theme checkbox
Darkt theme hover file selector
Autofocus username in login and signup
Pointer style cursor for checkbox and checkbox label
Bootstrap alert for live elo warning
=> Minor style changes

server/fishtest/templates/tests_view.mak
Draft in case someone wants to make suggestions and because it has debug code
=> Save diffs in sessionStorage

server/utils/purge_pgn.py
The "pgns" collection inflated with old PGNs because: some devs's pattern
may stop the purging loop (eg pausing a run for some weeks), the purge
script was updated with delay with the changes to the run dictionary template.
The "pgns" collection was cleaned with a temporary custom script update.
Changes:
- stop the purging loop based on "last_update" instead than "start_time"
- purge the not finished runs if "last_updated" is older than 50 days
- use python3
=> Improve the purging PGNs script

worker/games.py
See https://tests.stockfishchess.org/actions?action=&user=ChessDBCN&before=1662019685.675&count=100
=> Catch exception when the call to os.path.getmtime fails.

server/fishtest/static/js/toggle_password.js, server/fishtest/templates/login.mak, server/fishtest/templates/signup.mak, server/fishtest/templates/user.mak
closes https://github.com/glinscott/fishtest/issues/970
=> Toggle password visibility

server/fishtest/static/js/application.js, server/fishtest/templates/base.mak, server/fishtest/templates/tests_view.mak
Set the default theme automatically based on the prefered color scheme
=> Automatic default theme

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/tests_run.mak
Makes the page responsive
Tests in dev are encouraged, it has lots of changes
---
=> Tests run redesign

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/run_table.mak
Dark mode alerts
---
New pagination colors
---
Use color-scheme dark in dark mode
---
Use more Bootstrap variables
=> Various style changes

server/fishtest/templates/tests_run.mak
Automatically set base branch, base signature, base options, stop rule, amount of games, threads, time control and book
=> Progression tests presets vs SF15

server/fishtest/templates/base.mak, server/fishtest/templates/tests_run.mak
More details in the issue comments
Fixes #1405
=> Make sure Back button reloads the tests page

server/setup.py
=> Use pymongo 4.x

server/fishtest/templates/tests_run.mak
Refactor for easier future modifications and also set test branch and signature
=> Progression tests v2

server/fishtest/views.py
a try with Mako template's conditional rendering
=> Redirect to home in /login and /signup if already logged in

server/fishtest/templates/tests_run.mak
Set info (https://github.com/glinscott/fishtest/pull/1416#issuecomment-1239326536)
Notes:
- Only makes the API call when the PT or PT SMP buttons are pressed
- The message is the first line of the commit message
=> Progression tests presets v3

server/fishtest/rundb.py, server/fishtest/templates/nns.mak, server/fishtest/templates/pagination.mak, server/fishtest/templates/run_table.mak, server/fishtest/views.py
Adds a basic search to the NN repository
Adds the pagination used for finished tests to the NN repository
Reduces the amount of NN per page from 250 to the usual 25
Makes pagination a template
=> NN repo search and pagination and pagination template

server/fishtest/templates/tests_run.mak, server/fishtest/views.py
Easier for the users to select the book that they want without having to manually check the repo and type it correctly
=> Use a select with options for the books in tests_run

server/fishtest/actiondb.py, server/fishtest/templates/actions.mak, server/fishtest/views.py
Add pagination to actions/events
Closes #1284
=> Events pagination

server/fishtest/static/js/application.js, server/fishtest/templates/tests_view.mak
Use a try catch because some old safari versions might not support this
Closes https://github.com/glinscott/fishtest/issues/1412
=> Catch error in case of no browser support

worker/games.py
Data:
https://tests.stockfishchess.org/tests/view/6343f4b04bc7650f075401c7 with old adjudication params https://tests.stockfishchess.org/tests/view/6343f4ba4bc7650f075401ca with no adjudication
If these tests come out with "noticeably different" results then we should consider this or similar adjustments. If those tests come back with "substantially identical" results than this should be rejected.
(Terms in quotes are left for future definition)
=> Adjust adjudication params by +50% in wake of new net arch with equivalent eval inflation

server/fishtest/static/js/live_elo.js, server/fishtest/templates/tests_live_elo.mak
Use template literals
Avoid innerHTML as much as possible, using textContent instead
Add a link to the user tests
Reorder based on table order
=> Template literals, avoid innerHTML and user link

worker/games.py
See
https://tests.stockfishchess.org/actions?action=&user=markkulix&max_actions=2
=> Handle make with invalid permissions gracefully.

server/fishtest/api.py, server/fishtest/templates/machines_table.mak, server/fishtest/util.py, server/tests/test_api.py, server/tests/test_rundb.py
This is the server counter part to #1442 .
Add (M) to workername of modified worker.
Add + to version of modified worker in machine table.
=> Give some indications that a worker is modified

.github/workflows/worker_posix.yaml, server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
Workers from China are unable to download the items.
Drop macOS from GitHub Actions.
=> Revert 731369e

server/fishtest/templates/tests_run.mak, server/fishtest/views.py, server/tests/test_run.py
Use the preexistent API call done in the backend to retrieve the bench to also get the message and date
Opened it as draft to gather suggestions about the python code
=> Progression tests presets v3.1

server/fishtest/static/css/application.css, server/fishtest/templates/base.mak
Progress wiki has migrated to the Stockfish repo.
=> Update progress link in view of new Stockfish wiki page.

server/fishtest/static/css/application.css
Reference:
1- [tests.stockfishchess.org/tests/view/638ec34268532fcbf79df94f](https://tests.stockfishchess.org/tests/view/638ec34268532fcbf79df94f)
2- [tests.stockfishchess.org/tests/view/638e49d468532fcbf79de4fd](https://tests.stockfishchess.org/tests/view/638e49d468532fcbf79de4fd)
3- [tests.stockfishchess.org/tests/view/638e497b68532fcbf79de4e6](https://tests.stockfishchess.org/tests/view/638e497b68532fcbf79de4e6)
Before:
After:
=> Also break the word if no pre-wrap white space can be done

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/test_worker.py, worker/worker.py
Introduced with python 3.5, see https://docs.python.org/3.6/library/subprocess.html
=> Use modern high-level API subprocess.run

server/fishtest/actiondb.py, server/fishtest/templates/actions.mak, server/fishtest/views.py, server/utils/convert_actions.py
To make this work the action database should be converted using the script `utils/convert_actions.py`.
Note: this script does not delete any data. Still would be good to temporarily keep a backup of the current action database, just in case something goes wrong.
This PR has no user visible changes.
=> PR2: Extract the event fields directly from the data base. 

server/fishtest/actiondb.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/templates/actions.mak, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/utils/convert_actions.py
The actiondb now has a well defined schema which is checked before insertions. This should facilitate debugging.
The script: utils/convert_actions.py deletes superfluous data from the actiondb. This should save a lot of space.
Note that the database still contains enough information to reconstruct the deleted data.
No user visible changes.
=> PR3: Directly write to the actiondb using the new schema.

server/fishtest/templates/actions.mak, server/fishtest/templates/base.mak, server/fishtest/templates/elo_results.mak, server/fishtest/templates/tests_view.mak, server/fishtest/templates/users.mak
Fix the html error:
"Bad value for attribute href on element a:
Illegal character in path segment: space is not allowed."
=> Fix url for username with space

server/fishtest/templates/tests_view.mak
The case of the asynchronously appearing SPSA graph should now also be fixed, although I did not test this.
=> Better handling of scroll to task.

server/utils/delta_update_users.py
It stopped working on December 13.
=> Fix bug in the updating of user statistics.

server/fishtest/static/js/spsa.js, server/fishtest/templates/tests_view.mak
This is achieved in a maintainable way by using promises instead of events.
=> Eliminate flashing. Only one scroll command.

server/fishtest/static/js/spsa.js, server/fishtest/templates/tests_view.mak
The async/await framework allows one to write asynchronous code as if it were synchronous. It uses promises under the hood.
=> Convert some promiscuous code to async/await.

server/fishtest/templates/tests_view.mak
Also: cleanups of latest scroll patch.
=> Keep table heading visible after scrolling.

server/fishtest/actiondb.py, server/fishtest/rundb.py, server/fishtest/templates/actions.mak, server/utils/delta_update_users.py
Also: retire the update_stats event and replace it with the more generic system_event.
=> Record server shutdown and restart as system events in the event log.

server/fishtest/views.py
=> Replace quotation marks by standard ones.

server/fishtest/actiondb.py, server/fishtest/rundb.py, server/fishtest/templates/tests_run.mak, server/fishtest/views.py
Examples
```
NumGames(40000)(PT) TC:30+0.3 Book:8moves_v3.pgn Threads:8(SMP)
SPRT<0.00,2.00> TC:10+0.1 Book:UHO_XXL_+0.90_+1.19.epd Threads:1
```
The format is terse, but the idea is that it should be easily searchable.
=> Give some information about new runs in the event log.

server/fishtest/actiondb.py, server/fishtest/rundb.py, server/fishtest/templates/actions.mak
Example
```
Result:green Elo:147.17[87.73,206.61] LOS:100%
```
=> Give useful information in the event log of a finished run.

server/fishtest/static/html/maintenance.html
Based on https://gist.github.com/pitch-gist/2999707?permalink_comment_id=4114075#gistcomment-4114075
=> Add a maintenance page

server/fishtest/static/js/notifications.js, server/fishtest/templates/tests_live_elo.mak
Otherwise stopped tests will have a follow button which makes no sense.
=> Omit the follow button in mako template for finished tests.

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/base.mak
In that way it will always be visible.
=> Make the bootstrap notification alert fixed-top.

server/fishtest/static/js/notifications.js, server/fishtest/templates/base.mak
To test this one should block notifications, follow some tests, and wait for them to finish. They will all appear in the same alert dialog.
=> Multiple fallback notifications no longer overwrite.

server/fishtest/static/js/notifications.js, server/fishtest/templates/tests_live_elo.mak, server/fishtest/templates/tests_view.mak
In that way it applies to all tests.
=> Move the follow button to the main test page.

server/fishtest/static/js/notifications.js, server/fishtest/templates/run_tables.mak
Also fix a small bug in the last PR.
=> Make the notification toggle disappear after a finished test.

server/fishtest/static/js/application.js, server/fishtest/static/js/notifications.js, server/fishtest/templates/run_table.mak
No functional change.
With all the bug fixing the code had grown a lot of hair. Now it is much cleaner I think. 
Some generic stuff (handling the document title and broadcasts) has been taken out of `notifications.js` and put into `application.js` .
=> Cleanup and refactoring of cross tab communication.

server/fishtest/static/js/application.js, server/fishtest/static/js/notifications.js, server/fishtest/templates/base.mak
Not tested with native notifications.
=> Make notifications clickable.

server/fishtest/static/js/notifications.js, server/fishtest/templates/tests_view.mak
Handle the follow/unfollow button in the same way as the clock+toggle icon.
Do the right thing when the user wants to follow > 15 runs.
Fix some typos.
=> More cleanups and refactoring.

server/fishtest/views.py
To avoid duplicated netowrk entries in the DB was forced a synchronous upload, see: https://github.com/glinscott/fishtest/pull/757
An easy way to enable to avoid duplicate entries is to look up the network in the DB just before adding the entry.
This PR speed up the upload process and reduces possible race conditions checking for duplicate files on the file server as well, raising the appropriate HTTP errors if necessary.
Other changes:
- use a fixed path for the POST (usually the {id} is used in PUT and DELETE)
- use a multipart form POST to upload the network. In this way the file server can use an UploadFile object that uses in a smart way the RAM for big data
Requirements:
- update of the file server
- adding a "/" in the fishtest.upload
=> Asynchronous network upload

server/fishtest/rundb.py, server/fishtest/static/js/application.js, server/fishtest/static/js/notifications.js, server/fishtest/util.py, server/fishtest/views.py
Also: include hash in new_run event message.
=> Give more information in notifications.

server/fishtest/static/js/application.js
=> Open test window and give focus when clicking a native notification.

server/fishtest/rundb.py, server/fishtest/static/js/notifications.js
make it consistent with the db state variable.
=> Fix blue showing as red

server/fishtest/templates/run_table.mak
=> Fix misalignment on mobile.

server/fishtest/static/css/application.css, server/fishtest/static/css/theme.dark.css, server/fishtest/templates/elo_results.mak, server/fishtest/templates/run_table.mak
Each commit is to be considered separately, independently:
1) Adjust color to match link color (still too dark/bright/attention-grabbing for my preference), reduce width for high-contrast color
2) Include `sprt @` in highlight box
3) don't highlight LLR box
@peregrineshahin thoughts?
=> Some possibilities for LTC highlighting

server/fishtest/util.py
This patch rewrites estimation algorithm to calculate remaining hours of SPRT type tests.
=> Use better estimation for remaining hours calculation.

server/fishtest/rundb.py, server/fishtest/views.py
Ideas by peregrineshahin, vondele, xoto10.
See #1596, #1597, #1620.
=> Optimize the number of db queries to build the main page.

server/fishtest/static/js/notifications.js, server/fishtest/templates/run_table.mak, server/fishtest/templates/tests_view.mak
=> Unfollowed test before trying to delete or stop.

server/fishtest/static/js/notifications.js, server/fishtest/templates/run_table.mak, server/fishtest/templates/tests_view.mak
Since the format of the LRU data structure has changed, it is very important to reload all tabs, since otherwise the results will be unpredictable.
=> Unsubscribe from stopped and deleted tests.

server/fishtest/api.py
The api call api_active_runs turns out to be pretty expensive (4s if the load is small). This PR writes the strip_run in a way that avoids the deep copy of the large task lists directy. Would need a measurement on the dev server to see if it improves performance. Basically a before / after of `time wget https://dfts-0.pigazzini.it/api/active_runs`
=> A hand-written deep copy avoiding copying some very large lists

server/fishtest/views.py
master is so hard to read that it was faster to fix it than to verify the correctness of the fix
no functional change
=> Fix illegible batch size calc

server/fishtest/rundb.py
=> Better fix for #1641.

server/fishtest/views.py
fixes: https://github.com/glinscott/fishtest/issues/1636
=> Handle wrong page params.

server/fishtest/rundb.py
Reverts glinscott/fishtest#1648
The tests user page need these info to stay synchronized with the home page and the single test page.
=> Revert "Avoid Useless calculations for /tests_user pages"

server/fishtest/static/js/notifications.js
Stale notifications are notifications for finished runs. They are harmless but they needlessly load the server (forever with the current implementation).
Stale notifications can for example be created by subscribing to a finished run in a browser tab that was not refreshed.
Purging will happen every 5.5 hours on average and uses the active_runs api to detect finished but still subscribed runs.
=> Regularly purge stale notifications.

server/fishtest/static/js/notifications.js
Using a counter does not really work since it is reset with every browser refresh.
=> Use timer instead of counter for purging stale notifications.

server/fishtest/static/js/notifications.js
Do not purge notifications with recent activity. They should be dealt with in the normal way.
=> Alleviate race in stale notifications purging.

server/fishtest/__init__.py, server/fishtest/templates/tasks.mak, server/fishtest/templates/tests_view.mak, server/fishtest/views.py
Try implement alternative solution (vs https://github.com/glinscott/fishtest/pull/1655) for task list rendering via injecting html.
drafted at the moment until I can build this
=> Inject tasks.

server/fishtest/templates/tests_view.mak
This shortens the code a bit and fetch_text() has moreover a bit more error checking built in.
=> Use fetch_text() from application.js instead of raw fetch.

server/fishtest/static/js/application.js, server/fishtest/static/js/notifications.js
Also: fix possible race. Currently if the browser sleeps after fetching and before purging (unlikely, but...) then some notifications may be lost.
=> Remove most console.log messages.

server/fishtest/rundb.py
See
https://tests.stockfishchess.org/tests/view/644d1ddb68e01d8194cddf35?show_task=90
https://tests.stockfishchess.org/api/get_run/644d1ddb68e01d8194cddf35
=> Fix wrong colors after purging.

server/fishtest/static/css/application.css
current flags have messed up alignments due to the align center when injected machines.
=> Fix alignment of flags

server/fishtest/templates/users.mak
Consistent with Home page cards UX.
=> Add cards/tiles to the users/monthly pages.

server/fishtest/rundb.py
after merging the new net, increase estimated memory needs for running the worker
=> Adjust memory estimate

server/utils/delta_update_users.py
- fix the exception when loading an empty deltas collection.
- write documents with many keys to speedup all the operations on the deltas collection (find, delete, insert). This save 33% of execution time in "update mode" with our DB.
=> Fix and improve delta_update_users.py

server/fishtest/static/css/application.css, server/fishtest/templates/tests_view.mak
https://tests.stockfishchess.org/tests/view/64abb2afe0c0e4e9fd848b02
=> Fix design overflow issue.

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
explicitly use x86-64-sse41-popcnt
=> Do not use deprecated x86-64-modern

server/fishtest/rundb.py, server/fishtest/views.py
This change includes:
* fix for multiple approving overwrites the approver in db
* removing extra work of getting runs twice
* show the approver of the run in tests view
=> no overwrite for the first approver

server/fishtest/rundb.py, server/fishtest/views.py
This patch intends to enhance the finished run logic to its minimal requirements.
=> Enhance finished_runs

server/fishtest/templates/tests_run.mak
to reproduce bug:
step 1 - Click SPSA
step 2 - Click LTC
step 3 - Change branch name
base_branch changes when you change test_branch to be same (bug)
`base-signature` had an unintended bad value assigned to it in case of SPSA.
=> Fix event listeners are not removing.

server/fishtest/templates/tests_run.mak, server/fishtest/templates/tests_view.mak
removes extra spaces, adds a placeholder to SPSA params textarea, and removes unnecessary usage of HTML non-breaking space.
=> Some html fixes.

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/static/css/application.css, server/fishtest/templates/actions.mak, server/fishtest/templates/base.mak, server/fishtest/templates/machines.mak, server/fishtest/templates/workers.mak, server/fishtest/views.py, server/fishtest/workerdb.py, server/utils/create_indexes.py
Approvers and owners can block/unblock.
A blocked worker gets an error message which can be customized by the blocker.
The html is atrocious but I have no time to improve it. Hopefully an expert will improve it.
Currently the workerdb keeps growing. In the future stale entries should be purged regularly.
=> First shot at worker blocking.

server/fishtest/templates/tests.mak, server/fishtest/templates/tests_view.mak, server/fishtest/views.py
* Navigate to the previous page in case login is required.
* Don't show options that a user can't use.
=> some views fixes

server/fishtest/views.py
latest simplifications omits the query string, add them natively with `path_qs`
=> Remember query strings

worker/games.py, worker/sri.txt
See
https://tests.stockfishchess.org/actions?action=&user=&text=AssertionError 
https://tests.stockfishchess.org/actions?action=&user=&text=ValueError
=> Chase the cause of some strange failures using longer error messages.

server/fishtest/api.py, worker/sri.txt, worker/worker.py
New format
Exception NameError at games.py:855 WorkerVersion: 215
=> Add worker version to message for uncaught exception.

server/fishtest/static/css/application.css, server/fishtest/templates/base.mak, server/fishtest/templates/tests_view.mak
bootstrap 5.3.1
highlight js 11.8.0
font awesome 6.4.2
=> Update cdn's versions.

server/fishtest/static/css/application.css
=> fix links colors on hover as well

server/fishtest/static/css/application.css, server/fishtest/templates/base.mak
MongoDB dropped the free cloud monitoring service, see https://www.mongodb.com/docs/manual/administration/free-monitoring/
=> Retire MongoDB free cloud monitoring

server/fishtest/userdb.py
This serves as documentation but we also enforce the schema using asserts to avoid inadvertent database corruption.
Unfortunately this was not tested. I could not create a new user on my local instance (captcha failure).
=> Add a schema to userdb.

server/fishtest/templates/workers.mak, server/fishtest/views.py
A draft message is provided (which includes the message in the worker management panel) which of course can be edited.
<hr>
Hi user00,
It seems your worker user00-7cores-1234567 has some issue(s):
Your worker is producing excessive timelosses! 
Can you take a look?
You may possibly find more information at
https://34.205.74.97/actions?text=%22user00-7cores-1234567%22.
Note: it may be that your worker is currently blocked. In that case
you can unblock it at https://34.205.74.97/workers/user00-7cores-1234567.
Thanks in advance!
The Fishtest team
=> Add mailto links to worker management.

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
See https://tests.stockfishchess.org/actions?max_actions=3&text=%22update_pentanomial%22&before=1695591050.683729
=> Tighten up parsing of "Finished game" lines in cutechess-cli output.

server/fishtest/api.py, worker/sri.txt, worker/worker.py
refactor the cutechess setup code a bit to make it more readable
=> cleanup the cutechess setup code

server/fishtest/api.py, worker/sri.txt, worker/worker.py
as discussed in https://github.com/official-stockfish/fishtest/pull/1802, this should fix the double cutechess verification
=> fix double cutechess verification

server/fishtest/views.py
This removes unnecessary loops.
=> Enhance pagination.

server/fishtest/static/js/calc.js, server/fishtest/templates/sprt_calc.mak
fix resize events keeps triggering old error alerts if the keyboard shows or hides on  mobile.
fixes: https://discord.com/channels/435943710472011776/900771437177094156/1160537676286541824
=> Fix android bug

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py
This comes handy for Devs who want to list the finished runs without having to scrape webpages.
=> Introduce finished runs API

server/fishtest/views.py
The Stockfish CI has picked a more suitable criteria for extracting bench in https://github.com/official-stockfish/Stockfish/commit/ca5d9a5ff0739a63f7b0a184193dfb9de3c57156 This commit adapts fishetst bench extraction to that. Fishtest Wiki instructions are outdated (as of now) by that Stockfish commit.
=> Fix bench extraction

server/fishtest/templates/base.mak, server/fishtest/templates/user_management.mak
=> Fix inconsistent <td> widths.

server/fishtest/templates/user_management.mak
=> Fix width also when table has not data

server/fishtest/views.py
This allows the use of folders in the books repo
=> Use Git trees to look for books

server/fishtest/templates/user.mak, server/fishtest/userdb.py, server/fishtest/views.py
follow up for https://github.com/official-stockfish/fishtest/pull/1805
=> Make it possible to reject users before accepting them

server/fishtest/templates/user.mak, server/fishtest/views.py
makes it the same button for block and unblock, 1 click is better than 2.
=> Make blocking and unblocking one button instead of a checkbox

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
Required by the new SF architecture with a Big + Small nets
https://github.com/official-stockfish/Stockfish/pull/4915
Raise the worker version to 224 (also server side)
=> Add multiple nets support to the worker

server/fishtest/static/js/application.js, server/fishtest/templates/contributors.mak, server/fishtest/views.py
This adds search filtering to contributors and top-monthly client-side based on any text in a row.
=> Implement client filtering.

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
Should fix https://github.com/official-stockfish/fishtest/pull/1865#issuecomment-1866726716
=> In make: put stdout=None, shell=False.

server/fishtest/static/html/maintenance.html, server/fishtest/static/js/application.js, server/fishtest/static/js/calc.js, server/fishtest/static/js/live_elo.js, server/fishtest/static/js/notifications.js, server/fishtest/static/js/spsa.js, server/fishtest/static/js/spsa_new.js, server/fishtest/templates/actions.mak, server/fishtest/templates/base.mak, server/fishtest/templates/contributors.mak, server/fishtest/templates/login.mak, server/fishtest/templates/nn_upload.mak, server/fishtest/templates/nns.mak, server/fishtest/templates/run_table.mak, server/fishtest/templates/signup.mak, server/fishtest/templates/sprt_calc.mak, server/fishtest/templates/tests.mak, server/fishtest/templates/tests_finished.mak, server/fishtest/templates/tests_live_elo.mak, server/fishtest/templates/tests_run.mak, server/fishtest/templates/tests_stats.mak, server/fishtest/templates/tests_user.mak, server/fishtest/templates/tests_view.mak, server/fishtest/templates/user.mak, server/fishtest/templates/user_management.mak, server/fishtest/templates/workers.mak
All functionalities touched should be Dev-tested, but this cleanup is essential and probably had to be done at some point (making the maintainer's life harder).
=> Assorted cleanup.

server/fishtest/actiondb.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/workerdb.py
Note: this PR conflicts (unavoidably) with #1877  . If the latter would be committed then this one has to be made into a draft, and vice versa.
=> Make the meaning of some strings in the schemas explicit.

AUTHORS, server/fishtest/static/js/application.js, server/fishtest/templates/contributors.mak
Add ranking numbers in the first column of the contributors list.
Big thanks to @peregrineshahin  who created the coding for this idea.
Conflict resolved.
=> Add ranking numbers in the contributors list

server/fishtest/static/css/application.css, server/fishtest/templates/machines.mak, server/fishtest/templates/run_table.mak, server/fishtest/templates/tests.mak, server/fishtest/templates/tests_view.mak
Sometimes when the text is too long, the page can expand in width, this fixes that
=> Fix tables overflows

server/fishtest/api.py
=> Improve comment

server/fishtest/static/css/theme.dark.css, server/fishtest/static/js/application.js, server/fishtest/templates/base.mak
No redirection to home page if logout failed, clears confusion.
=> handle logout fail

server/fishtest/templates/actions.mak
solves https://github.com/official-stockfish/fishtest/pull/1906#issuecomment-1977300568
=> Avoid links for fishtest.system user

server/fishtest/actiondb.py, server/fishtest/workerdb.py
This is a quick fix for #1920. A more substantial fix will be added to #1916.
=> Correct regexes for short and long workernames.

server/fishtest/templates/tests_view.mak
This request has been pending for years, since GitHub does not provide the diffs with two dots in the API we are not able to actually see the actual diff in test view, this replaces the request to GitHub API with three dots to a local algorithm with the help of jsDiff library to find the actual diff between files.
How can we continue from there:
make tabs for the diff section such that we can see the actual diff with official master without going to GitHub.
online tool made for testing at: https://githubdifftesting.netlify.app/
=> View actual git diff in tests_view

server/fishtest/static/css/application.css, server/fishtest/templates/user_management.mak, server/fishtest/views.py
This implement @disservin suggestion at https://github.com/official-stockfish/fishtest/issues/1894#issuecomment-1948782740
=> Dropdown menu for users management

server/fishtest/static/js/application.js, server/fishtest/templates/contributors.mak, server/fishtest/templates/workers.mak
Also Enhances filterTable clientside function to take a predicate instead of always includes
Closes https://github.com/official-stockfish/fishtest/issues/1894
=> Add menu for blocked workers

server/fishtest/views.py
this validates the post request against frontend manipulation.
=> Validate modify_test requests against bad requests

server/fishtest/views.py
Supersedes https://github.com/official-stockfish/fishtest/pull/1830
Dependent on  https://github.com/official-stockfish/fishtest/pull/1934
=> Require another approval to increase priority/throughput beyond limits

server/fishtest/__init__.py
This fixes a security concern (a blocked user is still able to submit tests.)
This logs the user out immediately with any interaction with the server if the user is blocked
=> Invalidate a blocked user session

server/fishtest/api.py
allow passing nothing for elo0 and elo1, and use the fixed game get_elo function
=> add fixed games to the calc_elo API

server/fishtest/api.py, server/fishtest/rundb.py
Improve https://github.com/official-stockfish/fishtest/pull/1955
=> Add "Content-Length" header for run PGN

server/fishtest/rundb.py, server/fishtest/schemas.py
This is the last collection format to be documented.
=> Add schema for the pgndb.

server/fishtest/rundb.py
also fix a stray unrelated typo
id put together a functional change that i was gonna suggest, but then i decided it wasnt worth suggesting. but since id done this cleanup anyways, may as well submit the cleanup
=> improve readability of itp code (no functional change)

server/fishtest/api.py, server/fishtest/rundb.py, worker/sri.txt, worker/worker.py
after the various net updates the estimated memory need was no longer accurate also add the estimated size of cutechess-cli with the larger book
=> Update memory estimates

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
The previous message is confusing and vague enough to convey the reversed meaning.
=> Clear out confusion in wrong bench message.

server/fishtest/templates/tests_view.mak
Deal in proper way when the run has not PGNs (yet or anymore)
=> Use JavaScript to download the run PGNs

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
https://tests.stockfishchess.org/actions?text=calledprocesserror
=> Handle failing make strip gracefully.

server/fishtest/templates/user.mak
All Repositories to Public Repo
=> Fix GitHub tokens instructions

server/fishtest/templates/tests_view.mak, server/fishtest/views.py
since official commits are always rebased
=> fall back to the three dot in case of PTs

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
SPSA tunes and same commit vs same commit runs the same binary so verify once
=> When running the same binary verify signature once

server/fishtest/rundb.py
=> Verify that `run_id` is a compatible `ObjectdID`

server/fishtest/api.py, server/fishtest/util.py, server/tests/test_api.py
This is a much better version of #1999 . Lightly tested.
The structure is now as follows
```
class GenericApi:
-- contains handle_error, add_time
class WorkerApi(GenericApi):
-- contains the apis used by the worker
class UserApi(GenericApi):
-- Apis useful for application developers
class InternalApi(GenericApi):
-- Apis (possibly exposing sensitive data) that should only be
used by Fishtest itself (possibly access controlled).
```
=> Clean refactoring of api.py.

server/fishtest/rundb.py, server/fishtest/static/css/application.css, server/fishtest/templates/base.mak, server/fishtest/util.py
unmaintained/unmoderated for years now, and google identified it as a place for spamming eventually.
https://groups.google.com/g/fishcooking
```
Banned content warning
FishCooking has been identified as containing spam, malware, or other malicious content.
```
=> Remove fishcooking posting

README.md
It looked weird not capitalizing the first word of a sentence.
=> Fix some capitalization

server/fishtest/api.py
Pyramid provides a zoo of ways of handling errors. It is best to always use the same method so that is easier to modify the behavior if needed.
=> Refactoring: handle all errors in api.py using handle_error.

server/fishtest/__init__.py
as a debugging aid, introduce a signal handler for printing stack traces
`kill -USR1 <pid>`
will result in a stack dump
needs testing on dev. The signal handler must be installed from the main python thread.
=> Introduce a signal handler for printing thread stack traces

server/fishtest/templates/tests_view.mak
makes it easy to spot for approvers
=> Give warning for (TP,Prio) exceeds the normal limits

server/fishtest/templates/user.mak
this adds a confirmation dialog with the approver to confirm rejecting a new user since the decision is sensitive.
=> Require confirmation before rejecting users

server/fishtest/templates/user.mak, server/fishtest/util.py, server/fishtest/views.py
=> Enhance ugly design

server/fishtest/templates/notfound.mak, server/fishtest/views.py
I personally prefer a wide banner just like GitHub in https://github.com/ghost/dummy , but this is good enough to have as a placeholder, feel free to overwrite me with a design.
=> This adds a 404 page

server/fishtest/templates/signup.mak, server/fishtest/templates/user.mak, server/fishtest/userdb.py, server/fishtest/util.py, server/fishtest/views.py, server/tests/test_api.py, server/tests/test_users.py
shows tests repo and the groups the user belong to
=> Show more info about user and in profile

server/fishtest/rundb.py
This is the right thing to do in order to have an audit trail for tasks that have not played all their games.
=> Use "failed_task" api to flag a stale active task.

server/fishtest/rundb.py, server/fishtest/schemas.py
=> Document the format of the cache in schemas.py.

server/fishtest/schemas.py
=> Force c>0, c_end>0 in the schema.

server/fishtest/helpers.py, server/fishtest/templates/tests_view.mak
code and idea by @Dubslow, math reviewed by Viz
=> Warn about too low hash values/tc_ratio

server/fishtest/__init__.py, server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/schemas.py, server/tests/test_api.py, server/tests/test_rundb.py
=> Dynamic duplicate workers detection.

server/fishtest/rundb.py
Also: remove some dead code while there.
=> Optimize the construction of the main page a little bit.

server/fishtest/templates/user.mak, server/fishtest/templates/user_management.mak, server/fishtest/util.py, server/fishtest/views.py
and enhance the page with count statistics
=> Show approvers to user management

server/fishtest/views.py
Thanks to @vdbergh for bringing attention to the bug.
=> Fix wrong inner quotation in text

server/fishtest/rundb.py, server/fishtest/util.py
Set it to 1.0 for the `flush_buffers` task.
=> Introduce `min_delay` parameter for `create_task`.

server/fishtest/rundb.py
Use the per-run active_run_lock instead.
=> Do not hold on to the run_cache_lock while writing to the db.

server/fishtest/rundb.py
Deals with https://github.com/official-stockfish/fishtest/issues/2094#issuecomment-2201970849
=> Protect internal data by lock before validation

server/fishtest/api.py, worker/sri.txt, worker/worker.py
Revert https://github.com/official-stockfish/fishtest/commit/a49df4844594b4a48afc72cbfdca99256b4f35d8 to complete https://github.com/official-stockfish/fishtest/pull/2131
=> Enable worker lock code

server/fishtest/rundb.py
as needed since SF 17 release.
=> Update base settings for PT tests

worker/games.py, worker/sri.txt
Now matches https://github.com/Disservin/fastchess/blob/master/app/src/engine/uci_engine.cpp#L258
=> Check for semicolon in fastchess Warning

server/fishtest/static/js/spsa.js, server/fishtest/templates/tests_view.mak
closes https://github.com/official-stockfish/fishtest/issues/2181
=> Toggle between absolute/percentage for SPSA graph

server/utils/nginx_cidr_builder.py
Data downloaded from repository:
https://github.com/ipverse/rir-ip.git
=> feat: add script to build Nginx CIDR config

server/fishtest/templates/tests_view.mak
easier than digging through the event log
=> show approver on test details

server/fishtest/templates/tests_view.mak
=> make approver name clickable in details

server/tests/test_rundb.py, server/utils/create_indexes.py
I cannot easily test this, so draft for now.
Might need a second pair of eyes from @vdbergh .
=> use constants for LTC bound

server/fishtest/api.py
See e.g. https://tests.stockfishchess.org/actions?max_actions=7&action=stop_run&user=&text=&before=1739317302.406786&run_id=
=> Do not produce a cascade of stop_run's.

server/fishtest/api.py, worker/sri.txt, worker/tests/test_worker.py, worker/worker.py
Build once fastchess to speedup the ci test.
Raise worker version to 261 (also server side).
=> refactor(worker): improve test code.

server/fishtest/api.py, worker/sri.txt, worker/tests/test_worker.py, worker/worker.py
Raise worker version to 262 (also server side).
=> refactor(worker): consistent use of "tests" flag

server/fishtest/static/js/spsa.js
- dropdown parameter is open after selection
- remember the selected parameter
- reduce gaussian filtering to 10 steps
- retire animation: inconsistent, slow, introduce glitches
closes #2222
=> feat(spsa chart): improve code

server/fishtest/rundb.py, server/fishtest/views.py
Reverts official-stockfish/fishtest#2227
=> Revert "Do not revive a failed run."

server/fishtest/static/js/application.js
fixes https://github.com/official-stockfish/fishtest/pull/2228#issuecomment-2670725836
=> fix darkmode switch

server/fishtest/views.py
This is a new version of #2227.
=> Require reapproval for reviving a failed run.

server/fishtest/schemas.py
=> Fix schema error introduced in #2239

server/fishtest/util.py
- use UHO_Lichess_4852_v1
- improve code and variable naming
=> refactor(server): util.py

server/fishtest/rundb.py
=> Decouple the core spsa update logic from the reporting

server/fishtest/templates/tests_view.mak, server/fishtest/views.py
The main aim is to track the impact on document size of the recents spsa changes.
=> Add document size to tests page.

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
- exit immediately after failing to delete the old binary
- improve exception handling
- always use Path().replace()
- use a single convention for returncode check
- enhance function naming
=> fix(worker): setup fastchess in robust way

server/fishtest/api.py, server/fishtest/rundb.py, server/fishtest/schemas.py, server/fishtest/util.py, server/tests/test_rundb.py
Also: do not allow multiple update_spsa for a single request_spsa.
=> Use bit array for storing flips in active spsa tasks

server/fishtest/static/js/application.js, server/fishtest/templates/contributors.mak, server/fishtest/templates/machines.mak, server/fishtest/templates/user_management.mak, server/fishtest/templates/workers.mak, server/fishtest/util.py, server/utils/delta_update_users.py
- use last_update as single source of truth in collections and in templates
- tidy up code in delta_update_users.py
- improve code in utils.py and drop not useful function
- sort the machines for formatted last_update
=> refactor(server): improve formatted last_update

server/fishtest/views.py
Also: slightly tweak the reapproval conditions.
=> Only display reapproval message for previously approved run.

server/fishtest/actiondb.py, server/fishtest/api.py, server/fishtest/schemas.py
=> Increase max size of action message to 5120

server/fishtest/api.py, worker/sri.txt, worker/worker.py
See https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=&before=1742552611.384284&run_id=
=> Look for curl and/or wget during toolchain check in worker.

server/fishtest/api.py, worker/sri.txt, worker/worker.py
Now Stockfish Makefile checks for already downloaded nets before testing
for `curl/wget`.
https://github.com/official-stockfish/Stockfish/commit/6028264cb991b99b3a51cf2fd01b6f1f6ce24cc3
=> feat(worker): drop check only mandatory tools

server/fishtest/templates/tests_view.mak, server/fishtest/util.py, server/fishtest/views.py
Here is how it looks (not all warnings):
=> Further tweak warnings/notes in tests_view.mak

server/fishtest/rundb.py, server/fishtest/schemas.py, server/fishtest/views.py
We also enforce the corresponding condition in the run schema.
=> Check that a run is not finished before reviving after modifying.

server/fishtest/api.py, worker/games.py, worker/sri.txt, worker/worker.py
This is the worker compagnon to #2299.
=> Make it possible for the worker to post to the server event log.

server/fishtest/templates/tests_run.mak
For context, I took some old data that I had and:
| Bench diff (±%) | % of tests |
|---|---|
| 5 | 45.48% |
| 10 | 20.16% |
| 15 | 8.16% |
| 20 | 3.08% |
| 25 | 2.05% |
| 30 | 1.30% |
| 35 | 0.89% |
| 40 | 0.68% |
| 45 | 0.54% |
| 50 | 0.43% |
=> Add signature difference check

server/fishtest/rundb.py, server/fishtest/schemas.py, server/fishtest/views.py
This serves as backup if GitHub is down during server start.
Also: Get the list of valid books from rundb.books.
=> Save rundb.books to a collection.

server/fishtest/schemas.py, server/fishtest/views.py
This is a PR on top of #2305.
Additional warnings:
- Time odds
- Small book
=> More warnings

server/fishtest/helpers.py, server/fishtest/util.py, server/fishtest/views.py
We keep the fail safe and the log message, but hopefully they will not be triggered anymore.
=> Hopefully should fix the issue raised in #2309

server/fishtest/routes.py, server/fishtest/static/css/application.css, server/fishtest/static/js/application.js, server/fishtest/templates/base.mak, server/fishtest/templates/rate_limits.mak, server/fishtest/templates/tests_view.mak, server/fishtest/views.py
The client rate limit takes the personal access token into account.
=> Add a rate limit item (server and client) to the sidebar.

server/fishtest/github_api.py, server/fishtest/rundb.py, server/fishtest/templates/run_table.mak, server/fishtest/util.py, server/fishtest/views.py
The result is cached except when a network error occurs.
=> Introduce convenience function is_master(sha) and use it.

server/fishtest/github_api.py, server/fishtest/views.py
=> Some last second changes which were missed in the last PR.

server/fishtest/templates/tests_view.mak
The exception is already caught by the caller.  See https://github.com/official-stockfish/fishtest/pull/2340#issuecomment-3031034201.
=> Remove superfluous try/catch block.

server/fishtest/static/js/application.js, server/fishtest/templates/rate_limits.mak, server/fishtest/templates/tests_view.mak
A rudimentary implementation for
https://github.com/official-stockfish/fishtest/pull/2340#issuecomment-3033389107
=> Display error message when obtaining diff fails.

server/fishtest/views.py
When a test is being viewed, the server makes some GitHub api calls to potentially show some extra information to the user. Most of the time the results of the api calls are cached.
This system works well under normal use but it seems to break down somewhat when crawlers systematically view all tests. In that case the server becomes just a proxy for executing pointless GitHub api calls.
From a practical side this has not been a real problem. When a crawler visits, the server seems to execute up to 500 GitHub api calls/hour which is far below the limit of 5000.
Still, the server executing pointless GitHub api calls on behalf of random crawlers seems wrong, so in this PR we restrict this as follows:
- Authenticated users are allowed to make api calls (a crawler will be unauthenticated).
- …
=> Restrain GitHub api calls by the server

server/fishtest/github_api.py, server/tests/test_github_api.py
Also: add corresponding unit tests.
=> Cleaner and more efficient implementation of is_master
