- worker/games.py
and do not set global value in -each clause to cute chess if so. Keep the global value to correctly compute concurrency.
This is suggested to allow Lucas to perform Elo scalability testing in the framework.
For normal use, nothing changes (no need to change howtos etc)
In order to test a version against itself with different threads, set the normal threads parameter to the *higher* value and then add the usual Threads=N option to the custom UCI options for each.
See Lucas' post here:
https://groups.google.com/d/msg/fishcooking/_aLnMjMH4ec/jbKXgJrpcq0J
> Detect if threads have been specified manually (for scalability testing)

- fishtest/fishtest/templates/base.mak
I miss direct link to official-stockfish/Stockfish github in main menu.
> Add link to official stockfish to menu

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
All tests are run in parallel and ordered by constantly changing internal priority rather than being processed one by one.
This has several advantages:
- No long running test should get stuck at the end of the queue. Instead these are progressing slowly.
- After a test has been approved in fishtest, the execution starts immediately, so a developer can immediately get feedback if the test is promising or not.
python is not my strongest language, so please review carefully :-)
I'm still running some internal tests in my local fishtest instance, but I'm submitting this for early review to get feedback...
> Throughput and internal priority. Better balancing between tests.

- worker/games.py
The new 'nodes time' option should allow virtual machines and more loaded hosts in general to take part in the framework. But local testing revealed that time losses are still possible if there is a local spike in CPU load.
So update the worker such that if 'nodes time' is being used, the 'timemargin' option is passed to cutechess. This allows the engines (which are not really using the clock at all) to overstep the time limit by up to 10 seconds (a huge amount, and one that should stop any time losses at all)
Since the SF instances are still playing without the knowledge they have this reserve, it won't distort the results.
The next refinement I guess would be for workers to be able to indicate that they are only good for 'nodestime' jobs, but that is rather more complicated.
In the …
> Detect the new nodestime option and use timemargin to reduce noise

- worker/games.py
Without that we cannot test time management patches correctly, because each
worker uses a different increment/base ratio.
This problem is also known to cause chi-square to fail for tcs where the
increment is not small respective to the base, like 5+0.05 for example
(for the same reason).
Now with C++11 std::chrono, SF uses a sub millisecond precision on every
platform. The only constraint is that the Timer thread only checks for
time every 5 msec, but that's still 10x less than our 50msec increment,
so no risk to go below that.
> Scale increment

- fishtest/fishtest/templates/tests_run.mak
- Reduce resolution from 6 to 5 bayes elo. Detect >= 2 elo patches more
reliably, and reject regressive to almost useless patches more strictly
(less lucky runs).
- No average cost increase. even a slight decrease in the most common cases.
Supporting evidence provided + approved by Joona:
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/Vai7kJKlwaM
Also remove OwnBook while at it. SF does not support book, which must be handled
by the GUI.
> Change default SPRT bounds

- fishtest/fishtest/views.py
It does not make sense to purge SPSA. Bad workers have contributed towards
moving the parameters, and reducing c(k), so there is no going back.
> Do not purge SPSA

- fishtest/fishtest/templates/tests_run.mak
Use a standard `100:1` ratio, proportional to `5'+3"`, more or less in line with typical rating lists.
Joona is ok with it, so it's up to you:
https://groups.google.com/forum/?fromgroups=#!topic/fishcooking/e4aApDQKlCY
> Test with increment by default

- fishtest/fishtest/templates/tests_run.mak
The sensible point of a LTC game is the average search depth (specially at midgame) not the average game duration.
Scalability issue are more and more important and the number of tests that pass STC and fail LTC is sensible (even now with SPRT[0,5] for both cases). This means that we really want to test a patch at a good average search depth rate. Ideally we want an even higher value of LTC, but given our current resoruces 60 seconds is an acceptable compromise.
This patch restores average search depth and has the draw back of increasing testing time by 40 secs on average. This is more then acceptable IMO considering the current rate of tests that fail LTC after STC (scalability sensible) and the fact that only few tests reach LTC, so total testing time is not so impacted.
> Restore LTC at 60 seconds

- worker/worker.py
This should increase the maximum allowed game duration
to 30 minutes, and allows tests with longer time controls.
Also bump up worker version.
This change worked recently for CoffeeOne.
I propose to run a test of about 1,000 games at 5min+3sec.
I chose a limit of 30 minutes as I think this is a good compromise
between the maximum game duration, and the time an unattended PC
must wait until the hanging process is being killed.
> Increase the time waiting for a new game result.

- fishtest/fishtest/views.py
At the moment, we are trying to fix time loss issues. And fishtest is really not helping because it auto-purges all time losses!
This hack was never needed in the first place. Point is that machines with many time losses are already more likely to behave differently from the rest in terms of (W,L,D) joint distribution, and be burged by the chi-square test. Sounds statistics are enough, no need to add homegrown hacks on top of chi-square.
Ideally, we want to know which version lost on time (test or master). But that requires a bit more work.
> do not purge time losses

- worker/games.py
Cutechess presently uses the current time, in seconds, to seed its RNG.
This makes it very easy for various machines in fishtest to choose the
same random seed on the same workload, particularly when a large number
of machines join a machine pool for a specific test.
The fix here is to pass a random integer to cutechess via the "-srand"
option.  A platform-independent seed is chosen using os.urandom(),
which raises an exception if a randomness source is unavailable.
Cutechess only uses 32 bits of random state (a "quint32"), and the
parser for -srand requires an unsigned integer (although the
Mersenne::initialize routine just takes an int), so the routine here
generates an unsigned integer.
Issue originally discovered by VoyagerOne at …
> Feed a random seed to cutechess.

- worker/games.py
In verify_signature 'concurrency' was wrongly set to 'games_concurrency' instead of 'games_concurrency * threads'
In verify_signature() are started 2 instance of the engine:
- the first one with 'go infinite' and number of threads 'concurrency - 1': in order to load the CPU
- the second one with 'bench' and one thread: in order to compute bench signature and bench nps
In this way:
1. worker with virtual cores are rated correctly in SMP tests
2. worker without virtual cores are rated with the correct setting for TurboBoost (minor effect)
Tested with my worker (4-cores with HT)
With 'concurrency = 3', in all tests, my worker is rated @ 2.24 Mnps
With 'concurrency = 7'
a. in 1-thread tests, the worker is rated @ 1.40 Mnps (TC scaled as with 7 slow cores)
b. in 7-threads tests, the worker is …
> fix base_nps in SMP tests with HT

- fishtest/fishtest/rundb.py
The purpose of throughput was to increase parallelism and ensure equal distribution of resources between tests. So there is no reason to allocate 7x more resources to a 7 thread test, and throughput should be rescaled accordingly.
> Rescale throughput with threads

- fishtest/fishtest/templates/tests_run.mak
STC: 4MB
LTC: 64MB
These values were calibrated using fishtest:
STC: 2MB is too low, 4MB is enough
http://tests.stockfishchess.org/tests/view/569b14d50ebc594a0871d925
http://tests.stockfishchess.org/tests/view/569adc340ebc594a0871d910
LTC: 32MB is too low, 64MB is enough
http://tests.stockfishchess.org/tests/view/569b5c090ebc594a0871d937
http://tests.stockfishchess.org/tests/view/569c6d980ebc594a0871d958
> Correct default hash size

- fishtest/fishtest/rundb.py
Prior to this patch, spsa iteration count is increased when spsa work is
requested, not only when it is completed.  The spsa iteration count is
important to convergence as it affects the step size.  This has been
a problem recently as there have been many disconnecting clients; e.g.,
checking the most recently completed spsa run
http://tests.stockfishchess.org/tests/view/573fc6890ebc59301a354f99
the final iteration count is 60837 instead of 20000.  See also related fishcooking thread
https://groups.google.com/forum/#!topic/fishcooking/Np13OpEO1_w
> increase spsa iter count only with completed games

- fishtest/fishtest/rundb.py
I believe this corrects the number of finished tests (and pages of them) listed on user pages (which I believe occurs when the number in the runs db exceeds one page).
> fix count of finished runs

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/views.py
I was watching some recent tunings by Fisherman, and saw spsa reverse its trend after its bounds were changed:
http://tests.stockfishchess.org/tests/view/575a7d0f0ebc59029919b385
http://tests.stockfishchess.org/tests/view/575ae6ee0ebc59029919b39d
There's a chance that the current behavior at boundaries is to blame (though I'm not sure), so I created the present pull request.  It contains two changes: one attempting to make spsa more stable at boundaries, and one to make it more stable in general by replacing the round() with a randomized rounding that in expectation gives a smoother function.
It's possible that neither of these changes are improvements, so I've added options to the new run page to enable or disable them (they are disabled by default).  I can post on the mailing list so …
> Spsa boundary tweak

- fishtest/fishtest/templates/base.mak
This patch intends to regularize the indentation in base.mak that was broken after adding the green link (spaces replaced by tabs). No other changes.
> Regularize space in base.mak

- fishtest/fishtest/templates/tests.mak
When the number of running machines is high, reaching the tables of running and finished tests requires some serious scrolling.
Add a "Show/Hide" button for the running machines table, the page is loaded with the running machines table hidden.
> Add "Show/Hide" button for the running machines table

- fishtest/fishtest/templates/base.mak
"Wiki" is the currently used name for a Knowledge Base (especially if organized in a wiki).
"Help" is a bit misleading, suggesting information for new users.
> Change menu voice from "Help" to "Wiki"

- fishtest/fishtest/rundb.py
The internal priority formula implicitly uses the chunk size, so make this dependency explicit by replacing the hard-coded value.
> Replace hard-coded value by chunk size

- fishtest/fishtest/views.py
Idea by Stehane Nicolet. Sorting criteria:
1) SPRT jobs sorted by decreasing LLR, with higher LLR at the top
2) Fix number of games jobs, with larger number of games at the top
3) SPSA tuning jobs, with larger number of games at the top
> Sort active tests

- fishtest/fishtest/stat_util.py
If the Elo difference in a fixed number of games test is huge, the calculation of the statistical error in `get_elo` will fail for `mu_max >= 1`. I encountered this error on my fishtest instance for chess variants (http://35.161.250.236:6543/tests), but it is not very likely to occur in the main fishtest instance, since Elo differences usually are much smaller there.
> Protect elo formula from math domain error

- fishtest/fishtest/views.py
The action history does not show a meaningful message when the throughput is changed (`modify:`). With this PR, `'throughput changed from %s to %s' % (before, after)` is added to the message.
> Show change of throughput in action history

- fishtest/fishtest/templates/tests.mak
When scrolling through the test results I think it would be convenient to also have a pagination at the bottom, because you otherwise have to scroll back to the top before you can go to the next page.
> Add page navigation at bottom

- fishtest/fishtest/templates/tests_run.mak
Since SPRT bounds are not directly related to the choice of time control, automatically resetting the bounds when changing time control might be surprising for the user.
> Do not change bounds when switching time control

- fishtest/fishtest/templates/tests_view.mak
Currently, the start date is only shown in the list of tests, but not in the detailed view of a test. This PR adds a table (below stats on the right) where the start and last updated times are displayed.
> Show time stamps on test details page

- fishtest/fishtest/templates/tests_run.mak
It seems more intuitive to have them next to the field they change.
> Move Fast/Slow buttons to time control field (#129)

- fishtest/fishtest/templates/tests_run.mak
Add buttons to automatically set the SPRT bounds with one click for convenience. The naming of the buttons is "std" [0,5], "tweak" [0,4], "simp" [-3,1] to keep them small, but can of course be changed if desired. Similar buttons can be found on http://35.161.250.236:6543/tests/run.
> Add buttons for choosing SPRT bounds

- fishtest/fishtest/views.py
...instead of by starting time. This should result in a more intuitive sorting of the pending tests, since internal priority determines which test will be picked first.
> Sort pending jobs by internal priority

- fishtest/fishtest/api.py
- worker/games.py
- worker/worker.py
Currently, setting Book Depth to 0 breaks the worker, which loops with an error.
To allow testing from the start position, i.e. no starting book, this change makes Book Depth 0 miss out all of the book arguments in the cutechess command.
> Make book_depth = 0 disable the opening book

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/views.py
This is a proposal to add an option for disabling auto-purge on a per-test basis. This might be useful if for certain tests it is expected that there will be a big statistical fluctuation, e.g., when using no/small opening book, when testing patches that give different speed-ups depending on the architecture, for time management tests, etc. By disabling auto-purge for such tests, one can avoid to bias the result and/or wasting too much resources by reapeatedly purging results.
Test submission page looks like this: http://35.161.250.236:6543/tests/run
An intentionally problematic test (in terms of fluctuations) where auto-purge was disabled: http://35.161.250.236:6543/tests/view/5a6474bb6e23db7297acc507
> Add option for disabling auto-purge per test

- fishtest/fishtest/views.py
Currently, SPRT tests have a 128000 game limit, meaning that at most 128
workers can be assigned to a test, unless the limit is manually
increased. With the recent increase of fishtest machines, we are hitting
this limit quite often. The 128 chunks can get assigned quickly when the
test has barely started. As a result, some machines become idle.
This patch allows 1000 chunks to be assigned to a test by default.
> Increase default SPRT game limit to 1000000

- fishtest/fishtest/templates/tests_run.mak
uses STC/LTC instead of fast/slow.
The easy bit of issue #148
> Adjust labels for TC in test submission

- fishtest/production.ini
Waitress default is 100.
If we have 200 workers with 8 cores and TC = 10s+0.1s
then this results in about 160 game result updates per second.
If a few expensive requests like the /tests, api/request_run or
api/request_spsa cause a delay of more then 0.625s then requests
will be dropped because the backlog is > 100 requests
Most of these dropped requests could have been processed quickly
and each worker will never have more than one outstanding request.
In addition default worker timeout is 5s.
Raising max connections from 100 to 500 (300 in original proposal, see comments) does better match
current number of workers.
> Set max waitress connections to max nr of workers

- fishtest/fishtest/rundb.py
- fishtest/utils/index.py
This index should speed up the finding of a new task when a worker has finished the previous one. Gives only a marginal gain on my home test, but I only have a handful of tests in the database at the moment. Should give a useful gain (possibly a very large gain) on a large db.
> add index on tasks.pending to speed up query of new tasks

- fishtest/fishtest/rundb.py
- fishtest/production.ini
This prevents:
- A slow down due to parallel execution of the stop run and SPSA logic
which overwrites the computed results of other threads
- Concurrent overwriting saves to the MongoDb
- Stopped runs which display an LLR of <= 2.94 instead of >= 2.95
- Display artifacts in Last Updated time
but still allows concurrent updates by tasks of different runs.
This is important because update_task is the most executed (> 99%) API call.
> Make update_task synchronous for each active run

- fishtest/production.ini
because we introduce some locks and to handle
the larger amount of traffic due to the many
workers in general.
> Increase threads to 16

- fishtest/utils/index_pending.py
This index aims to speed up the request_task() function with less risk than the index on tasks.active. (I suspect the index on tasks.active may cause a decrease in performance on some queries.)
There are comments in the script indicating how to drop the index if necessary.
> create index on run.tasks.pending

- fishtest/fishtest/views.py
and add some comments.
This gives a minor improvement under heavy load, because it prevents parallel cache builds when we don't have an old cache yet, e.g. after a server restart.
> Improve tests cache implementation

- fishtest/fishtest/rundb.py
Do not erase the dictionary but remove entries
last used over 10000 seconds ago.
This is not critical, but the right way to clean up old entries.
> Fix a race condition on periodic lock cleanup

- fishtest/fishtest/rundb.py
This is caused by a MongoDb index combined with a search
which skips some entries while being updated, see:
https://blog.meteor.com/mongodb-queries-dont-always-return-all-matching-documents-654b6594a827
Performance impact should be small because this is only called from the cached Overview page.
Edit: Note that there is still a smaller race condition, because this prevents acquiring new update locks while the overview is building, but updates might be already in flight. So it will reduce the chance but not completely reduce it to 0. Acquiring all run locks looks like overkill.
> Fix missing runs from Overview page

- fishtest/fishtest/rundb.py
Reverts glinscott/fishtest#179
The official server uses python 2.6.6 that does not support this syntax.
```
mydict = { k:v for k,v in mydict.items() if k!=val }
mydict = dict((k,v) for k,v in mydict.iteritems() if k!=val)
```
> Revert "Fix a race condition on periodic lock cleanup"

- fishtest/utils/index_active.py
This aims to speed up the request_task() function and get_machines() function, but has a risk of slowing down another query in request_task().
#174 should be tried before this one and the impact assessed for a while before considering this one.
Edit: no need to restart the server when changing indexes, the index create might take a short time, but once the script finishes and the new index is listed it is active. Obviously if it does cause a problem follow the instructions in the script to drop the index.
> create index on tasks.active

- fishtest/start.sh
There is not a start_fishtest process to be killed
> Drop useless instruction in start.sh

- fishtest/fishtest/rundb.py
Store the history every 'freq' iterations.
More tuned parameters result in a lower update frequency,
so that the required storage (performance) remains constant.
Limit history to 250000 iterations (500000 games).
History is written e.g. every 100 iterations (<= 4 parameters),
every 250 iterations (10 parameters) and every 2500 iterations (100
parameters).
> Rewrite history logic

- fishtest/fishtest/rundb.py
This functionality was lost after the MongoDb speedup modifications
which did only recompute the priority once every minute.
> Resort internal priority after each request_task

- worker/requests/adapters.py
The client side HTTP connection pool creates unnecessary load on server because when connection pool is not fully occupied, previously created connections are not reused.
We are reporting to server single-threaded, meaning that we'd never use more than one connection ever, pooling more than one of them makes no sense.
> Reduce HTTP connection pool size

- .travis.yml
- setup.py
- worker/games.py
- worker/setup.py
- worker/test_worker.py
- worker/updater.py
The actual application to be launched should be the fishtest worker.
This version solves locally all issues of https://github.com/glinscott/fishtest/pull/213
> Make the worker a standalone application

- .travis.yml
- fishtest/fishtest/rundb.py
- requirements.txt
- setup.py
- test_server.py
This is a folluwup to
https://github.com/glinscott/fishtest/pull/178
Now that we have a buffer cache we should use that lock
instead of the update_task lock. This should handle
the periodic flush thread and give a small performance boost.
Also add a simple Travis-CI test
> Use cache lock

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/tests_view.mak
on the main page, colored boxes containing LLR results can overflow if the number of tests exceeds 100000, causing the numbers to be split on two lines.
This patch (unfortunately untested), widens the column by a bit to give space for 2 more digits.
Would need somebody to have a look at the result on the dev server if the result is fine.
> SLightly wider column

- fishtest/fishtest/views.py
when no runs are active
This is a minor fix
> Fix showing LLR bounds for pending runs

- fishtest/fishtest/api.py
- fishtest/tests/test_users.py
stop_run is called when a wrong run is detected by workers.
Prevent that with many workers this call is executed in multiple threads
simultaneously.
> Make API stop_run synchronous

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/signup.mak
- fishtest/fishtest/views.py
See: https://www.google.com/recaptcha/admin
Store the secret key in
~/fishtest.captcha.secret
Store the public key in
templates/signup.mak
in the line near the end:
<div class="g-recaptcha" data-sitekey="PUBLIC-KEY-HERE"></div>
> Add captcha for signup form

- fishtest/utils/scavenge.py
This fixes scavenge.py for the current MongoDb software in production.
Followup for #246
> Use old mongodb method to drop users

- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/tests/test_rundb.py
- worker/games.py
but store them in the fishtest server to reduce network traffic
and significant unmarshalling time for SPSA runs with many parameters.
This reduces #253 significantly and is a followup to #155 
Only drawback is an increase in memory usage of the server, about 50 bytes per SPSA parameter per worker. So 200 workers working on a 500 parameter run adds 5 megabyte to the worker memory usage.
> Do not POST SPSA parameters from worker

- worker/games.py
- worker/test_worker.py
In case of an exception occurred during the download & build process, add a catch block so that temp directory cleanup is not skipped.
This also gives an opportunity to retry a few times instead of going through the expensive request_task process in case of a recoverable failure.
> Add exception handling of download & build process

- worker/games.py
- worker/worker.py
With recent changes to smaller chunk sizes and speedups reduce the startup time
to 1-10s from 1-30s for increased efficiency with fast workers.
Also remove the progressive quadratic delay after failed update_task
calls. These made no real sense, because cutechess-cli keeps on playing
while we wait and will be kiled after about 3*TC seconds.
> Adjust worker timings

- worker/games.py
fixes the cornercase described in issue #125 for those systems where /tmp/ is noexec. Since we anyway need the worker dir to be writable, and exec, we can as well compile there.
> Compile in worker subdir.

- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/fishtest/views.py
- fishtest/tests/test_rundb.py
- worker/games.py
A small optimization for #261 
In addition add a lock to get_worker_key() because it has a race condition.
Fix print issue introduced in #162
8a2da7b
> Unique_key from task + 2 fixes

- worker/games.py
This caused premature worker exits
> Fix SPSA games end time calculation

- fishtest/start.sh
pserve log is always empty.
Flush the pserve buffered output according
this [stackoverflow post](https://stackoverflow.com/questions/25674613/python-nohup-out-dont-show-print-statement)
While here use /bin/sh for better generality.
> Flush pserve buffered output

- fishtest/start_dev.sh
- fishtest/utils/backup.sh
Use /bin/sh in scripts to simplify the server requirements.
Add the line buffering for the nohup output in the commented out instruction.
> Drop /bin/zsh and use /bin/sh

- fishtest/fishtest/views.py
In some rare cases an approved test was still shown as unapproved to the approver
> Force rebuild of main page after change

- worker/games.py
- worker/test_worker.py
- worker/updater.py
- worker/worker.py
because Python2 will be EOL 1 jan 2020
Also make the updater.py runnable stand alone: "python updater.py"
To my surprise very few changes to the code were needed.
Tested with python3 AND python2:
- Downloading testing/ contents
- building
- running runs
- updating...
And fix the Travis worker_test for when we hit the github.com API limit
and add an `updater.py` Travis test.
Show Python version number to server.
> Make the worker Python3 compatible

- fishtest/fishtest/__init__.py
- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_view.mak
- fishtest/utils/clone_fish.py
- fishtest/utils/create_pgndb.py
- fishtest/utils/index_pending.py
- fishtest/utils/purge_pgn.py
- worker/games.py
- worker/worker.py
See #140 
PGN-files are stored gzip compressed in a new MongoDb collection ('pgns') with as only additional attribute the creating run_id-task_id.
Currently only a minimal API to retrieve the PGNs and a link in the task list.
About 200 kbyte compressed storage for a 250 game task (compression to 25% original size).
Also add a simple clone script which uses the REST APIs to make a copy of the run and PGN data in a fishtest database.
> Implement PGN upload/download and database clone

- fishtest/utils/purge_pgn.py
Keep the STC games for 2 days and the LTC games for 10 days
to decrease the DB size and increase the HD free space.
This solve also the problem of the backup upload to S3.
Parameters values suggested by @tomtor in #314
> Lower the PGN purge parameters

- fishtest/utils/backup.sh
The size of the DB is increasead, so keep locally a zipped copy of
the MongoDB dump in order to have more free HD space for the server maintenance.
This speed up also the copy of the DB on the development server.
> Keep the zipped MongoDB dump

- fishtest/utils/backup.sh
The pgns collection has a big size.
This can trigger:
* the bandwidth limit of the production server
* the size limit of the boto package used to upload to s3
> Delete the pgns collection from the backup

- fishtest/fishtest/templates/tests_run.mak
Following the discussion here https://github.com/official-stockfish/Stockfish/issues/1859, we aim at
- Improve precision, i.e. discard zero or negative patches and accept positive ones with higher margin
- Manage resource consumption.
After various simulations, here are results for different sets of SPRT parameters:
| Limits | [0,5] + [0,5]  | [0.5, 4.5] + [0,3.5] | [1,4] + [0,3]  | [0.5, 4] + [0, 3] | [0.5, 4] + [0, 3.5] | [0.4, 4.4] + [0, 3.2] |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 0 ELO pass prob | 0.0025 | 0.00123 | 0.00036 | 0.0011 | 0.0011 | 0.0014 |
| 1 ELO pass prob | 0.0744 | 0.1002 | 0.0805 | 0.1451 | 0.1183 | 0.1276 |
| +1 ELO rejectance ratio | 0.8201 | 0.7547 | 0.7625 | 0.6718 | 0.7049 | 0.7137 |
| …
> Change SPRT parameters for standard test to [0.5, 4.5] + [0,3.5]

- fishtest/fishtest/templates/tests_run.mak
This makes the default hash size 8 for STC.
I have not tested this as my local fishtest is not working currently but the change is minimal and hopefully easy enough for others to check.
Let me know if I need to do anything else.
> Update default hash size for STC

- fishtest/fishtest/templates/tests_run.mak
[This](https://groups.google.com/d/msg/fishcooking/BxWmrJ9yK64/ltnoKx0rFQAJ) discussion on fishcooking  suggested changing the default throughput for tests.
Possible values of 5000 or 10000 were mentioned. This patch currently changes the default to 10000, but if people want a different value, it could obviously be changed before being merged.
> Change default throughput to 10000

- worker/games.py
Required by python 3.x
Bug reported by Guy Vreuls
> Flush the subprocess stdin buffer

- worker/worker.py
Change the Linux command to read the system memory in bytes
like the Windows and MacOS commands.
The max_memory value is computed in mebibytes like the hash memory.
Add also the missing MacOS command (bug reported by @d3vv)
> Fix system memory read

- fishtest/fishtest/api.py
Currently a job with eg bad signature is not stopped immediately
and reliable when there are not many workers. Setting
run['Finished'] to true is a side effect of auto purging.
Fix this by setting 'Finished' in the API handler.
> Fix stop_run API

- fishtest/fishtest/actiondb.py
- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/actions.mak
- fishtest/fishtest/views.py
- fishtest/utils/delta_update_users.py
- fishtest/utils/scavenge.py
See #391 
`update_users.py` reads the whole MongoDb database to build user statistics from scratch.
This PR creates a new script `delta_update_users.py` which incrementally updates the statistics and only reads runs from the last 31 days.
Edit: Note that the first run will be as slow as `update_users.py`
> Write a more efficient script to update the user statistics

- fishtest/utils/delta_update_users.py
@ppigazzini This one sneaked through. The games/hour grand total should be cleared but it was not, so in the users report the games/hour continuously grows. The first incremental run should fix the grand total, no need to run a full scan.
> Fix games per hour statistic for grand total

- fishtest/utils/delta_update_users.py
because the users DID work on them and it
disturbs delta update calculation
@ppigazzini Can you run a full scan before testing or installing on production?
> Do not skip deleted runs in statistics

- fishtest/fishtest/templates/tests_run.mak
This pull request proposes to change the STC bounds to [-1.5 , 4.5]
At the date of october 19th, the pourcentage for speculative LTC
of the last 100 LTC Elo-gaining tests was 70%, from all active 
Stockfish developers.
This gives some feedback after a few months of intensive use with
the changes introduced in #342, and shows that the new STC bounds
were too strict for our community since even the most motivated
members bypass them.
Related discussions:
glinscott/fishtest#342
https://github.com/official-stockfish/Stockfish/issues/2283
https://github.com/official-stockfish/Stockfish/pull/1804#issuecomment-445429885
https://github.com/official-stockfish/Stockfish/issues/1859
> Change STC bounds to [-1.5 , 4.5]

- fishtest/utils/delta_update_users.py
When a test is stopped and restarted (by a modify) this
can cause many runs (30 days period) to be counted twice.
This happens only when the restarted test was the only new
finished test at the last execution of this script.
When the test is restarted before the script is executed
then there is also no error condition.
This can be fixed by storing also all older run-ids,
with a small performance impact (bigger MongoDb table).
Note that tasks in the restarted test are counted twice
when the error condition happens. This should be very rare.
@ppigazzini This has low priority. The performance impact should be minimal. Note that linenumbers have changed so you should adapt your upgrade procedure patch.
> Handle test stop, restart in statistics update

- fishtest/fishtest/__init__.py
- fishtest/setup.py
As of Pyramid 1.5, Mako templates are no longer configured by default.
See http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/whatsnew-1.5.html
This probably breaks things on Pyramid <1.5 so you should keep it around for when you update.
> Fix mako templates on Pyramid 1.5

- fishtest/utils/backup.sh
Empty the pgns collection (pgns.bson) to reduce the backup size but keep the indexes (pgns.metadata.json).
> Empty pgns collection and keep indexes during backup

- fishtest/fishtest/rundb.py
Currently the last page shows some tests of 100 days old.
And at the break: https://tests.stockfishchess.org/tests?page=134
> sort old runs for viewing

- fishtest/utils/test_queries.py
This script creates an easy way to see how quickly some of the key database queries are taking. This may help diagnose problems at times when fishtest gets slow.
More queries can be added to make the script a more thorough.
> Python script to time some db queries

- fishtest/fishtest/rundb.py
- fishtest/fishtest/views.py
edit: Filtering 'deleted' in python speeds up to 0.2s
> Speed up finished runs MongoDb query

- fishtest/fishtest/rundb.py
- fishtest/fishtest/views.py
I make a short cut here, I do not filter deleted runs from old_runs, but that should not be an issue.
@xoto10 I also noted that the grand total of runs is computed by counting 'finished' runs in old_runs, but old_runs does NOT have an index on 'finished'! We may consider all runs in old_runs to be finished, so I changed it to just count all in old_runs. That should give a significant speedup (EDIT: because old_runs does not change very often, MongoDb might cache the count result between invocations).
@ppigazzini This really needs testing on the dev server before it can be merged. 
Edit: Also fix count of runs
> Fix old_runs delete and speedup grand total

- fishtest/fishtest/views.py
Currently active machines and pending tests info is
computed for every info page even if it is not displayed.
Also remove computation of total_games which is never displayed.
> Speedup computation of info pages

- fishtest/utils/backup.sh
Speedup the back process using collection skipping and compression options of new mongodump.
Respect to the previous version this saves:
- 9/10 hard disk space
- 1/2 time
- 1/6 size backup file
> Speedup backup using mongodump options

- fishtest/fishtest/templates/tests_run.mak
In the past, parameter tweak tests were allowed to use easier bounds than normal tests. Now that normal test bounds have been changed they are easier to pass than the old parameter tweak bounds so the [0,4] bounds are redundant.
This patch removes the ` Parameter Tweak [0,4] ` option from the SPRT bounds drop-down in the New Test web page.
> Remove parameter tweak option for test bounds

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/tests.mak
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
- fishtest/tests/test_rundb.py
See https://github.com/glinscott/fishtest/pull/458
@ppigazzini @vdv @xoto10 I have tested this locally and it is ready for some more testing and feedback.
This change allocates cores round-robin. It is not completely fair now, because all cores are treated equally, so some workers might get faster cores than others. This is easy to change to Mnps calculation, but because we show allocated cores on the main page this is both simple to code and least confusing for users.
Note that old existing tests will have 3000 as throughput, so until they are finished they will get a large amount of the cores. When merging we should change prio to 100 for old tests
> Calculate priority with number of active cores

- worker/games.py
- worker/worker.py
This PR contains the worker changes. There are no server changes in this patch.
The updated worker will send the pentanomial frequencies
to the server and the server will faithfully store them in
its database as it does with all information received from
the client.
The actual logic added to the worker is quite minor.
A dictionary "rounds" keeps track of the finished games. For every
finished game pair (which consists of an odd numbered game
and the next even numbered game) the pentanomial frequencies
are updated.
Since sending incorrect frequencies to the server would
be quite disastrous, a lot of sanity checking is done to
make sure that the pentanomial frequencies are consistent
with the trinomial frequencies provided by cutechess itself.
> Make the worker calculate the pentanomial frequencies.

- fishtest/fishtest/rundb.py
This small compagnon PR to PR #351 makes the server aggregate the pentanomial frequencies, whenever they are present in its database. The effect can be verified with the `get_run` api call (see the next to last line in the output below).
```
$ curl http://localhost:6543/api/get_run/5c40f4d75c6d4e34f00d7269
{"results_info": {"info": ["ELO: -3.13 +-18.7 (95%) LOS: 37.1%", "Total: 1000 W: 371 L: 380 D: 249",
"style": ""}, "last_updated": "2019-01-17 21:43:25.249000", "results_stale": false, 
"start_time": "2019-01-17 21:34:15.163000", "args": {"book_depth": "8", "internal_priority": -1547759955.0, 
"new_signature": "3739723", "auto_purge": true, "tests_repo": "https://github.com/official-
stockfish/Stockfish", "new_tag": "master", "priority": 0, "base_signature": "3739723", "book": …
```
> "get_results" now returns the aggregated pentanomial frequencies.

- fishtest/fishtest/templates/elo_results.mak
- fishtest/fishtest/views.py
The pentanomial frequencies cannot be used solely behind the scenes
since that would make it difficult to verify independently the
statistical quantities derived from them.
So here we include them in the elo widget. As yet no statistical
quantities are computed.
```
ELO: -4.86 +-20.6 (95%) LOS: 32.2% 
Total: 500 W: 111 L: 118 D: 271 
Ptnml(0-2): 10, 60, 114, 59, 7
```
> Include the pentanomial frequencies in the "elo results" widget.

- fishtest/setup.py
- fishtest/utils/backup.sh
Switch from the outdated boto v2 package to the awscli v1.x package.
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
Document the aws cli usage and simplify the script.
> Use awscli v1.x package for backup management on aws s3

- fishtest/fishtest/templates/tests_run.mak
Increase hash size from 8 to 16.
STC shows ~6ELO gain from 16MB hash.
http://tests.stockfishchess.org/tests/view/5e15e3f661fe5f83a67dd938
> Increase hash to 16

- fishtest/fishtest/api.py
As stated in #498 the old API endpoint has been declared as outdated and thus been shut down about 2 years ago.
We can use a similar, free provider (it only limits at around 15'000 requests/hour, which we never exceed because of caching) to circumvent that problem.
Please share your thouights about using a third-party service instead of shipping the fishtest server with a prebuilt IP database file. We don't have control of what they want to do with the data we sent them (same goes for the old provider). Both of them have their source-codes publicly available but you never know how they implemented it on their side...
Feel free to change/adjust code if I misinterpreted your contribution guidelines :)
> changed geo provider for country lookups

- fishtest/fishtest/static/html/SPRTcalculator.html
- fishtest/fishtest/static/js/calc.js
As usual the new version is here.
http://hardy.uhasselt.be/Toga/SPRTcalculator.html
**Changes**
There are now minor and major vertical grid lines.
The Elo increment used for graph drawing is now a bit adaptive. This gives smoother tooltip behaviour for small elo differences.
All mouse events are now captured by a div specially created for that purpose. The GC default event handlers are thus completely disabled. This removes some prior artifacts, e.g. when the user clicked on the graphs.
Events are now disabled until the charts are fully drawn.
In general event handling is greatly simplified internally.
Some html cleanup. In particular the name attribute of the input fields is not used and thus was removed. Most inline styling was removed. A spurious ```</div>``` was removed.
> Various internal/external cleanups for the SPRT calculator.

- fishtest/fishtest/static/html/SPRTcalculator.html
- fishtest/fishtest/static/js/calc.js
Fixes an html error (apparently inconsequential) and some warnings found by https://validator.w3.org/ .
Fixes an inconsistency. I was using both float:left and display:inline-block for the char divs. They serve the same purpose. So now I only use display:inline-block which is the more modern solution.
Fixes a small, probably untriggerable, race condition in event handling. 
As usual the latest version is here 
http://hardy.uhasselt.be/Toga/SPRTcalculator.html
Externally it is indistinguishable from the previous version (or should be).
Future plans: when I find the time I will add a curve with the 95% quantile...
> A few minor cleanups in the SPRT calculator.

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/tests_run.mak
as per discussion in https://github.com/official-stockfish/Stockfish/issues/2531
introduce new bounds:
standard STC {-0.5, 1.5} -> 50% pass rate at 0.5 Elo (100k games), 1% pass rate at -1.0 Elo
standard LTC {0.25, 1.75} -> 50% pass rate at 1.0 Elo (137k games), 0.3% pass rate at -0.5 Elo
simplification STC/LTC {-1.5, 0.5} unmodified.
> Adjust bounds

- fishtest/fishtest/rundb.py
- fishtest/fishtest/stats/LLRcalc.py
- fishtest/fishtest/stats/stat_util.py
- fishtest/fishtest/templates/tests_stats.mak
- fishtest/fishtest/views.py
The theoretical properties of an SPRT are established under the
assumption that updates are continuous.
To have accurate agreement with the predictions, when the updates are
discrete, one has to estimate the expected "overshoot" and terminate
the SPRT a bit early, accordingly.  Unfortunately, to the best of our
knowledge, overshoot estimation is (surprisingly) computationally expensive.
Moreover in the case of a GSPRT there is the added complication of
unknown parameters and these have to be continuously estimated from
the sample. This more or less means that the expected overshoot
estimation has to be performed after every update, which is
prohibitively expensive (IMHO, doing it only when we are "close" to
one of the boundaries would lead to messy and possibly fragile code).
A …
> Better overshoot correction.

- worker/games.py
Looking into a number of timeouts in fishtest run using TC 0.5+0.005,
the workers with problems had an effective TC without increment, while others had one of 0.01:
5e0654a4c13ac2425c4a9e14-74.pgn:[TimeControl "0.55+0.01"]
5e0654a4c13ac2425c4a9e14-76.pgn:[TimeControl "0.36"]
This is due to rounding, with the given format string.
Cutechess allows for 3 digits, use that internally as well.
> Fix Time Control Format.

- .gitignore
- worker/test_worker.py
- worker/updater.py
Update only the worker files so that the update process will work
also with a custom worker folder name.
Enforce the download of the lastest version of cutechess-cli, books etc.
renaming the "testing" folder with a timestamp. Keep the lastest 3 backups
of the "testing" folder to save eventual custom user files.
Thanks to @vondele for some ideas and code.
> Fix the worker update process

- worker/games.py
- worker/worker.py
Dropping worker updates violates the SPRT contract which says
that updates should occur after every game pair.
Also: for connection related exceptions print the exception instead
of the full backtrace.
This issue came up while testing. The backtraces are too verbose
as they refer to the inner workings of things like urllib etc... The
exceptions themselves seem to contain exactly the right amount
of information.
The effect of this PR can be seen using #536. With this PR the
overshoot data should no longer be deleted after a server restart.
This was verified with some local testing.
> Queue worker updates if the server is down (worker update)

- worker/games.py
- worker/worker.py
Fix the "Warning: 2 opening repetitions vs 1 games per encounter"
Also raise the worker version to 72 (worker side).
> Fix #537: cutechess warning for opening repetitions

- fishtest/fishtest/rundb.py
- fishtest/fishtest/stats/stat_util.py
- fishtest/fishtest/views.py
The commit 926b8853c0a8c1fc7 appears to have cured the problem of disappearing overshoot data. So it seems to be the right approach to keeping state across updates. In fact I now realize it is similar to how spsa works (Instead of an sprt object there is an spsa object, both represented by dictionaries of course, for easy conversion to json). It could be the model for new types of tests.
This commit removes some remnants of the old sprt handling. In particular it fixes a small bug. Currently a ghost (empty) sprt item is left in the results dictionary after the test is finished. This is innocent of course, but not nice.
> Remove some remnants of the old sprt handling.

- fishtest/fishtest/templates/tests_run.mak
The test repo and test branch fields are closely related. As reported in a separate issue, I also think this is a UI problem for first-time test submitters. Fixes https://github.com/glinscott/fishtest/issues/340
---
This is how the top of the "Create new test" page will look:
> Move "Test repo" field right under "Test branch"

- fishtest/fishtest/templates/tests_view.mak
This shows the Github diff on the test page so you don't have to open the diff in a separate tab or window. The browser fetches the diff from Github through their API. If for some reason the request fails, then the diff section just won't show up. Fixes https://github.com/glinscott/fishtest/issues/332
---
For example, this is how this test page would look with the diff rendered:
https://tests.stockfishchess.org/tests/view/5e8a751164ea67c1c449bb7e
---
Github API docs for commit ranges:
https://developer.github.com/v3/repos/commits/#compare-two-commits
> Show github diff above tasks section on test pages

- AUTHORS
Data from `git shortlog -s | cut -c8-`
Moved Gary Linscott in first position.
> Update the list of authors and contributors

- fishtest/fishtest/templates/tests.mak
So you can easily tell how many tests are running. The homepage will also look more consistent with user pages this way. Fixes https://github.com/glinscott/fishtest/issues/450
---
The homepage will look something like this:
> Show # of active tests on homepage

- fishtest/fishtest/views.py
As reported in a separate issue, submitting a test with an invalid book name will cause workers to hang until the test is manually stopped. This PR prevents that from happening by making sure the book exists in https://github.com/official-stockfish/books. If the supplied book name is invalid, the page will display an error.
Fixes https://github.com/glinscott/fishtest/issues/531
---
Example of the error message when using an invalid book name:
> Validate book is in official books repo when submitting tests

- fishtest/fishtest/templates/tests_view.mak
@ppigazzini can you see if this fixes the issue you mentioned? i'm unable to test on my dev server
https://github.com/glinscott/fishtest/pull/559#issuecomment-610654540
these are the two test pages you mentioned:
https://tests.stockfishchess.org/tests/view/5214a8390ebc59160a0182f6
https://tests.stockfishchess.org/tests/view/5214ce9a0ebc59160a0182f8
> Don't show base branch comparison message for old finished tests

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
Since the client-side unauthenticated Github API limit is only 60 requests/hour, users will run into issues with the master diff check if they look at a bunch of tests.
This PR fixes that by moving this API request to the server, which has a limit of 5,000 API requests/hour (source: https://github.com/glinscott/fishtest/issues/385#issuecomment-528313637)
> Server-side check for whether master diff matches base branch

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/tests_view.mak
@vondele this adds the # of comments to the diff section as you suggested here https://github.com/glinscott/fishtest/pull/558#issuecomment-610596557
---
Example of how this page would look:
https://tests.stockfishchess.org/tests/view/5e8cab330ffd2be7f15e560f
> Show number of github comments on the diff when viewing tests

- fishtest/fishtest/templates/tests.mak
- fishtest/fishtest/views.py
this should improve the pending hours estimate, by reflecting current average games / test, and not counting tests run so far for sprt tests.
More accurately estimating the remaining number of games for a running sprt test is not obvious.
move this estimate away from the pending tests line, to the top status line, since this is an estimate of all tests, related to the current estimated fishtest performance.
fixes https://github.com/glinscott/fishtest/issues/564
> Improve pending_hours estimate

- fishtest/fishtest/rundb.py
- fishtest/utils/create_indexes.py
Some MongoDB queries are really slow because they don't use indexes, so they have to scan an entire collection (runs, old_runs, actions). Slow queries also degrade performance for other people using the site at the same time.
@tomtor this adds indexes to `old_runs` as you suggest here https://github.com/glinscott/fishtest/issues/563#issuecomment-610868360. It looks like there were no indexes on that collection at all, so queries being sent to `old_runs` would be slow.
@ppigazzini if you check out this branch in DEV, you'll have to use `fishtest/utils/create_indexes.py` to set up the indexes. My dev server has almost no data on it, so I don't have a good way of verifying the performance improvement.
Examples of really slow pages that should be fixed:
- …
> Fix slow queries due to missing MongoDB indexes

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/templates/users.mak
Linking another site using `target="_blank"` attribute exposes the site
to performance and security issues:
- the linked page may run on the same process as the start page
- the linked page can access the `window` object of the start page
Adding `rel="noopener"` to `target="_blank"` link avoids these issues.
https://web.dev/external-anchors-use-rel-noopener/
> Protect links to cross-origin destinations

- fishtest/fishtest/static/css/application.css
- fishtest/fishtest/templates/base.mak
- All sidebar links now show up on one line
- Hide register and login links when already logged-in
- Add Github section for fishtest and stockfish repos
---
Before and after:
> Minor sidebar cosmetic update

- fishtest/fishtest/__init__.py
- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/mainpage.mak
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/signup.mak
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
Auto-attaches CSRF token fields to POST forms and adds CSRF protection for logout link.
These routes are now protected. Normal users should see no difference.
- /login
- /signup [erratum corrige: /register]
- /logout
- /tests/run
- /tests/modify
- /tests/delete
- /tests/stop
- /tests/approve
- /tests/purge
For a simple example of a CSRF attack in master, put this in an html file locally (`csrf.html`):
```html
<form action="https://tests.stockfishchess.org/logout"></form>
<script>document.querySelector("form").submit()</script>
```
While logged-in to https://tests.stockfishchess.org/ open `csrf.html`. You will be taken to the fishtest website and you'll be logged out. When CSRF protection is enabled, you'll see an error message instead.
Fixes …
> Enable CSRF protection for POST requests on website

- fishtest/tests/test_run.py
- fishtest/tests/test_rundb.py
- fishtest/tests/test_users.py
- fishtest/tests/util.py
this fixes the failing travis tests as @tomtor pointed out in https://github.com/glinscott/fishtest/pull/577.
it also uses a `fishtest_tests` db so running tests in dev/prod will use a different db.
> Fix failing tests, use different db for tests

- fishtest/fishtest/userdb.py
Fix (makes rare) #578 
Edit: Alternatives are:
* completely remove caching of pending user query
* disable separate main page pserve instance
> Cache pending for 1s instead of 60s

- fishtest/fishtest/__init__.py
- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/machines_table.mak
- fishtest/fishtest/templates/tests.mak
- fishtest/fishtest/views.py
@tomtor as we discussed in https://github.com/glinscott/fishtest/pull/581, this is what i was thinking:
- if the user has the machines table hidden by default, it won't be rendered upon pageload
- if the user clicks "Show" while the table doesn't exist, the table is fetched and then rendered
the idea is to speed up the homepage by doing less work on both client and server when not needed, but there are still a lot of calculations done for the homepage on each request.
> Lazy-load machines table on homepage if hidden by user

- fishtest/fishtest/rundb.py
- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
Fixes https://github.com/glinscott/fishtest/issues/585
General fix so that all lazy-loaded tables will be sortable. Does not yet track the default sort key
> Fix sorting of lazy-loaded tables

- fishtest/fishtest/__init__.py
- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/run_table.mak
- fishtest/fishtest/templates/tests.mak
- fishtest/fishtest/templates/tests_finished.mak
- fishtest/fishtest/views.py
So the title of the page tells you which page you're on:
---
- Use a separate view for finished test pages
- Simplify tests view function for better readability
- Show Greens and LTC (Slow) titles on finished test pages
- Handle table pagination in one place
> Use different titles for finished test pages

- fishtest/fishtest/templates/run_tables.mak
- fishtest/fishtest/templates/tests.mak
- fishtest/fishtest/templates/tests_user.mak
- fishtest/fishtest/views.py
Previously, expensive calculations for unfinished runs (active, pending, failed) were being done on ALL `/tests` and `/tests/user` pages when you visit them. They're calculated when you visit any page number, but the results of these calculations are only shown on page 1. Only the homepage (page 1 of `/tests`) caches the results.
This PR should speed up page 2 and beyond of all `/tests` and `/tests/user` pages while reducing CPU usage.
Summary:
- Don't calculate unfinished runs on tests pages after page 1
- Separate view for user tests, show username at top of user tests
- Don't calculate unfinished runs on user pages after page 1
- Simplify tests view logic
- favicon.ico and robots.txt views are served by nginx
- Add a todo for calculating results_info when the run is finished, not when …
> Fix unnecessary expensive work on tests pages past page 1

- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/tests/test_api.py
if we want to change the server-side behavior of `update_task` or `request_task` for the 40k cores problem, having good test coverage would be useful for stability
> Add initial tests for fishtest API

- fishtest/fishtest/rundb.py
- fishtest/fishtest/views.py
- fishtest/tests/test_rundb.py
- fishtest/utils/create_indexes.py
@ppigazzini this PR only uses the `runs` collection for queries, so you can use it to see how the site is when everything is moved from `old_runs` to `runs`.
Fixes https://github.com/glinscott/fishtest/issues/569
Fixes https://github.com/glinscott/fishtest/issues/563
> Stop using old_runs collection for runs queries

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/tests_finished.mak
- fishtest/fishtest/views.py
As suggested by @vondele in https://github.com/glinscott/fishtest/pull/588#issuecomment-613239579
---
---
@ppigazzini this would require setting a new field on all runs. no need to rebuild indexes since the index was already added. just need to run a migration like this. i changed this migration from the previous migration script to update a single field on the run rather than replacing it (untested):
```python
import sys
from pymongo import MongoClient
conn = MongoClient()
runs = conn['fishtest_new']['runs']
for run in runs.find():
try:
if run['results_info'].get('style') == 'yellow':
runs.update_one({ '_id': run['_id'] }, { '$set': { 'is_yellow': True } })
except Exception as e:
print("Unexpected error:", sys.exc_info()[0], e)
```
> Add yellow finished tests page and sidebar link

- fishtest/fishtest/api.py
- worker/games.py
- worker/worker.py
Instead of calling `/api/update_task` after each game finishes, the worker now calls it either:
- once per N games, where N is worker concurrency (min of concurrency flag and # cpus - 1)
- or after all the games in the task have been completed
This should ease the load on the server by generating less network traffic (see https://github.com/glinscott/fishtest/issues/553#issuecomment-614500983) and allow prod to handle a higher # of worker cores.
> Scale down update_task request frequency by 2x

- fishtest/fishtest/rundb.py
EDIT: SPSA tuning jobs with many parameters require additional server resources compared to SPRT tests, due to the recalculation of the parameters after each mini batch of (2 * concurrency) games.
This PR limits the number of cores that are allocated to these jobs to (10000 / sqrt(nr-of-tuning-parameters)).
> Limit max number of worker cores for a SPSA tuning job

- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/views.py
@xoto10 suggested ways to improve the [create new test page](https://tests.stockfishchess.org/tests/run)  (see https://github.com/glinscott/fishtest/pull/556#issuecomment-610750254)
Here is how the page would look with this PR:
---
This is how the page currently looks in master:
> Update layout of 'create new test' page

- fishtest/fishtest/api.py
Flag look ups kill performance when the queue is empty.
See https://github.com/glinscott/fishtest/issues/605#issuecomment-616095195
> Cache flag lookups

- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/tests/test_api.py
- fishtest/tests/test_users.py
Added more comprehensive test coverage for API endpoints and actual use cases from workers. Simplified the API code a bit. Should be no functional change.
Add more API tests
- Use helper methods for more succinct tests
- for building requests with invalid passwords
- for building requests with correct passwords
- Add test cases for all API endpoints used by workers
Simplify API code
- Use a view class for API views
- Set renderer type json for all views by default
- Don't need manual json encoding with json renderer
- Use a separate method for authentication check
- Use exception view for handling failed auth
> Add more API tests and simplify API code

- fishtest/fishtest/__init__.py
- fishtest/fishtest/templates/login.mak
- fishtest/fishtest/views.py
Login sessions now persist between browser sessions (for a year) instead of until the browser window is closed if the user checks the 'stay logged in' checkbox during login.
The auth cookie is now http-only to prevent XSS attacks from stealing user sessions. For example, if you try `alert(document.cookie)` in prod, the auth cookie currently shows up there.
Partial fix for https://github.com/glinscott/fishtest/issues/610.
Still would be nice to redirect to the page you wanted to visit before the login prompt.
---
> Persistent logins and http-only auth cookies

- fishtest/fishtest/api.py
- fishtest/fishtest/userdb.py
- fishtest/utils/create_indexes.py
- fishtest/utils/delta_update_users.py
Follow-up to https://github.com/glinscott/fishtest/pull/611
- Add indexes to `flag_cache` and `user_cache` for faster lookups and lower CPU usage
- `flag_cache` documents auto-expire after 7 days using a MongoDB TTL index
- create_indexes.py now takes a list of collection names as arguments
- since it's rare to need to re-create ALL indexes, and re-building pgn indexes is very slow
- with no arguments, it only prints the indexes on all collections
- for each collection name given, it drops then creates indexes on the collection
Strictly speaking, the index on IP in flag_cache should be a unique index, but practically a non-unique index avoids race conditions, and documents in this collection auto-expire anyways.
The `flag_cache` collection will need to be dropped (or have the timestamp …
> Add index to flag_cache, auto-expire after 7 days, new create_indexes.py

- fishtest/fishtest/helpers.py
- fishtest/fishtest/templates/tests_view.mak
Old runs are missing the `tests_repo` key because they're hardcoded to `https://github.com/mcostalba/FishCooking`.
this PR should fix https://github.com/glinscott/fishtest/issues/615 but it's probably cleaner to do a data migration and set that `tests_repo` value for old runs instead of hard-coding it in the code.
> Fallback to a default tests_repo for old runs

- fishtest/fishtest/templates/tests_run.mak
These seem like reasonable defaults:
- alpha = 0.602
- gamma = 0.101
- A = 10% expected # iterations ~ 5% number of games (2 games per iteration)
See https://github.com/glinscott/fishtest/issues/535
---
> Bring back default values for SPSA params

- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
The SPSA params are currently really hard to read. Much easier to read in a table format.
---
Before:
---
After:
> Show SPSA params in a table for readability

- fishtest/fishtest/rundb.py
Python < 3.6 compatibility fix 
'_sre.SRE_Match' object is not subscriptable
> Python < 3.6 compatibility fix 

- fishtest/fishtest/static/css/application.css
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
- Use integers for numbers that start off as ints
- Right-align numbers to line up digits and decimal points
- Show less sig figs when not needed
---
Before
---
After
> Simplify displaying params in SPSA table

- fishtest/fishtest/static/css/application.css
- fishtest/fishtest/templates/base.mak
Add some space above it so it isn't displayed as stuck to the very top of the page.
> Add some space above flash (success/error) messages

- fishtest/fishtest/views.py
If a logged-out user tries making a new run or re-scheduling an existing run, after logging in they'll be redirected to the page they tried to visit before logging in. Fixes https://github.com/glinscott/fishtest/issues/610
> Go to /tests/run after login if logged-out user tried going there

- fishtest/fishtest/templates/tests_run.mak
If you click the "Submit test" button more than once or hit enter to submit more than once before the test submission goes through, you might create duplicate tests. This PR prevents that from happening through the UI by disabling the form and the submit button after the form is submitted the first time.
Fixes https://github.com/glinscott/fishtest/issues/347
> Prevent 'create new test' form creating duplicate tests

- fishtest/fishtest/templates/tests_run.mak
The base branch/signature should always match the test branch/signature for SPSA tests.
In this PR, when a user selects an SPSA test type, the base branch/signature fields are disabled and match whatever the user puts into the test branch/signature fields. This change prevents people from submitting invalid SPSA tests through the UI. Users can also safely do less work by not having to copy/paste the same info into two sets of fields.
Fixes https://github.com/linrock/Stockfish/commit/a548e8e66f544fba3b174c27d27a9a939e5a5759#commitcomment-38631870
---
> Disable base branch/signature fields for SPSA tests

- fishtest/fishtest/templates/tests_view.mak
Edit: i changed this PR to show short hashes on tests_view pages since when copying the hashes, it's more common to use a short prefix than the entire hash. the links are removed since the `base_tag` and `new_tag` fields link to the commit already. maybe there's a better way to present this info more succinctly?
---
> Show short new/base commit hashes on tests_view pages

- fishtest/fishtest/templates/tests_run.mak
When switching from SPSA to another test type, this sets the base branch and signature back to their initial values when the page was loaded. Usually, this will be master and master bench.
Fixes https://github.com/glinscott/fishtest/pull/626#issuecomment-618026692
> When switching away from SPSA test type, use initial base values

- fishtest/fishtest/templates/tests_view.mak
The master diff link now only shows up if:
- the base branch is not the same as stockfish master
- we don't know if the base branch is the same (old runs)
See https://github.com/glinscott/fishtest/issues/625#issuecomment-618030661
> Hide master diff link if base branch is same as stockfish master

- fishtest/fishtest/templates/tests_view.mak
If you have a lot of stockfish test browser tabs open, they all say `Stockfish Testing Framework` which makes it hard to look for a particular test you might have open.
On tests pages, depending on the test type, the browser tab titles will be more descriptive:
- SPRT testBranchName vs master
- SPSA tuningBranchName
- 5000 games - anotherTestBranch
> Set page title on test pages to test type+branches

- fishtest/fishtest/views.py
- fishtest/utils/delta_update_users.py
- worker/games.py
* rename parse_tc to estimate_game_duration: as that is what it does
* in this routine, use the current average number of moves per game (68),
as well as the percentage of time used (92).
* Use the correct reference nps to adjust tc in views, this must match the value in the worker 1.6Mnps
* take threading of a test into account to estimate game rate.
These changes should result in more accurate estimates for games/minute and duration.
It will also affect the displayed CPU hours contribution attributed to a user,
as that is estimated from the number of games played. The latter quantity is unaffected.
> Adjust time estimate

- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
So when viewing a test page, the page title shows up like this:
- SPRT testBranchName vs master
- SPSA tuningBranchName
- 5000 games - anotherTestBranch
Instead of always like this regardless of test type:
- testBranchName vs testBranchName
> Update page titles to match browser tab names

- fishtest/fishtest/templates/base.mak
So you can get back to the list of your tests from any page on the site. Right now, most pages have no direct way of getting back to your tests.
See https://github.com/glinscott/fishtest/issues/625#issuecomment-619228174
> Link to your tests in the sidebar for logged-in users

- fishtest/fishtest/rundb.py
- fishtest/fishtest/util.py
- fishtest/fishtest/views.py
- fishtest/tests/test_api.py
- fishtest/utils/delta_update_users.py
This is a code cleanup that changes the behavior of the homepage so that it doesn't write to runs when a user visits the page. This enables:
- routing requests by `run_id` to multiple pserves. this allows scaling server load over multiple cores when routing to pserves by `run_id` since each pserve would need to consistently write to the same subset of runs. this isn't possible if the homepage writes to runs since homepage requests are not routable by `run_id`. (see https://github.com/glinscott/fishtest/issues/133#issuecomment-526931028)
- speeding up the homepage and lowering overall CPU usage when combined with future code changes where homepage visits will no longer need to loop through all unfinished tasks.
Currently, visiting the homepage writes to the runs collection by:
- saving …
> Homepage visits no longer cause writes to runs collection

- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
Adds a checkbox for auto-purge when you go to a test page so you can change auto-purge on running tests instead of just upon test submission. See https://github.com/glinscott/fishtest/issues/625#issuecomment-619376772 for original suggestion.
---
> Enable modifying auto-purge on tests_view pages

- fishtest/fishtest/rundb.py
- fishtest/fishtest/stats/stat_util.py
- fishtest/fishtest/views.py
- fishtest/tests/test_api.py
Server changes to set the batch size for sprt tests.
In this PR the batch size is set to 8 which seems like a reasonable value. As the batch size has to be a divisor of the chunk size, the latter was changed to 200 (formerly 250). To compensate  for the smaller chunk size the initial maximum number of games for an sprt test is changed to 2000 times the chunk size (formerly 1000 times the chunk size).
One unittest is updated.
> Server changes to set the batch size for sprt tests.

- fishtest/fishtest/templates/tests_run.mak
When using the browser back button to get to the 'create new test' form, the submit button might be stuck in the 'Submitting test...' state.
This PR should fix that issue in Firefox. Chrome didn't seem to have the issue. Fixes https://github.com/glinscott/fishtest/issues/647
> Enable submit test button if arriving from browser back button

- fishtest/fishtest/rundb.py
fixes the 40/10 use case, using the estimate_game_duration call.
> Fix TC parsing for itp

- fishtest/fishtest/rundb.py
- fishtest/tests/test_api.py
- fishtest/tests/test_rundb.py
The current worker cannot handle tasks with an odd number of games.
On the other hand it will (should...) never send odd sized updates
itself. Enforce this contract server side.
Some unit tests updated.
> Enforce even sized worker updates.

- worker/games.py
- worker/worker.py
The worker code is serial and hence in principle
quite simple. Unfortunately it has grown organically
and currently it is not so easy too follow anymore.
This makes the idea of adding new types of tests
rather unattractive.
This is PR is the first timid attempt at cleaning
up some of the worker code.
This version of the worker should be functionally
equivalent to version 75. 
The most notable changes are
- The global variable old_stats is eliminated. The fact
that such a global variable exists needlessly complicates the
logic of the worker code.
- Trinomial and pentanomial frequencies are
now kept in sync for all types of tests. This simplifies
the code a lot.
- More asserts have been added.
> Some code cleanup in the worker

- fishtest/fishtest/rundb.py
seems to be a leftover from the CLOP implementation, and is not used anymore.
> Remove unused list

- fishtest/fishtest/templates/tests_user.mak
- fishtest/fishtest/templates/tests_view.mak
So if you have a browser tab open while viewing a user's tests, it will show their username in the tab title instead of just "Stockfish Testing Framework"
> Show username in page titles when viewing a user's tests

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_run.mak
- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
Implements vondele's suggestion here:
https://github.com/glinscott/fishtest/issues/625#issuecomment-617950457
So you can easily see which test a re-run came from and then get to it.
---
> Show link to original test when viewing a rescheduled test

- worker/games.py
- worker/worker.py
See https://github.com/glinscott/fishtest/pull/662#issuecomment-626908989
After first failure of `rate_limit` call switch to precompiled tests.
It will retry after finishing the received 200 game batch.
> Handle rate_limit API call failure

- fishtest/fishtest/templates/tests_view.mak
- fishtest/fishtest/views.py
So apostrophes don't show up as `&#x27;`
Before:
new_tag `tDblpawns (Tune doubled pawns penalty using vondele&#x27;s tuning )`
After:
new_tag `tDblpawns (Tune doubled pawns penalty using vondele's tuning )`
> Fix some chars showing up as html entities in test commit msgs

- fishtest/fishtest/rundb.py
Dropping 'cores' from run in stop_run causes sort to fail in
request_task
```
May 23 12:30:48 tests pserve[23821]:   File "/home/fishtest/fishtest/fishtest/fishtest/rundb.py", line 524, in <lambda>
May 23 12:30:48 tests pserve[23821]:     r['cores'] / r['args']['itp'] * 100.0,
May 23 12:30:48 tests pserve[23821]: KeyError: 'cores'
```
> Fix race condition with request_task/stop_run

- fishtest/utils/backup.sh
Limit the CPU usage to only one core during the MongoDB backup.
> Dump MongoDB collections sequentially

- fishtest/fishtest/static/html/SPRTcalculator.html
- fishtest/fishtest/static/html/live_elo.html
- fishtest/fishtest/static/js/live_elo.js
small change reducing the range on the Elo dial from [-6, 6] -> [-4, 4].
Covers 99.9% of patches, and gives a little more details for typical patches around 1Elo.
> Adjust Elo range on dial for live_elo

- fishtest/fishtest/templates/tests_run.mak
Add a default parameter for contempt to fishtest.  This allows us the flexibility to use a separate default contempt for fishtest testing from SF own default contempt.  Currently it's set to 24 to keep things the same but I don't know what the best value for testing purposes should be.  Discussion is welcome here.
See comments in https://github.com/official-stockfish/Stockfish/pull/2740
Note: I am unfamiliar with .mak files so if my changes aren't correct please advise.  Also I'm not sure if lines 146 and 150 should also be changed and if so what the exact syntax should be.  Ty.
> Add a default test contempt parameter

- fishtest/fishtest/views.py
Reduce from 50 for less IO and faster response.
See https://github.com/glinscott/fishtest/issues/690#issuecomment-647110579
> List 25 items on view pages

- fishtest/fishtest/views.py
Test case:
len("".split(","))
returns 1, not 0.
> Make parsing of spsa parameters resistant to blank lines.

- worker/games.py
A None value indicates that the process hasn't terminated yet.
Typically, an exit status of 0 indicates that the process ran successfully.
> Fix subprocess.Popen.poll() check

- fishtest/fishtest/static/js/spsa_new.js
- fishtest/fishtest/templates/tests_run.mak
This PR adds a checkbox to the "New Test" form. Checking this option will rewrite the hyperparameters furnished by the tuning code in Stockfish in such a way that the SPSA tune will finish within 0.5 Elo from the optimum (with 95% probability) assuming the function 'parameters->Elo' is quadratic and varies 2 Elo per parameter over each specified parameter interval. The hyperparameters are relatively conservative and their performance will degrade gracefully if the actual variation is different.  The theoretical basis for choosing the hyperparameters is given in this document
https://github.com/vdbergh/spsa_simul/blob/master/doc/theoretical_basis.pdf
The formulas can be checked by simulation which is done here
https://github.com/vdbergh/spsa_simul
It is important for the current version of …
> Enable a new algorithm for choosing SPSA hyperparameters.

- worker/games.py
- worker/worker.py
Clean up the code removing the calls to `kill_process()`.
In this way also the Windows worker, where at the moment the cutechess-cli
STDERR is queued after the STDOUT, is able to process the STDERR.
Thanks to @vdbergh for the suggestion.
> Clean up parse_cutechess_output()

- worker/games.py
File objects for stdin, stdout and stderr by default are opened in bynary mode
and require a byte string literal b'' as iter() sentinel.
We have opened the file objects for stdout and stderr in text mode using the
"universal_newlines=True" argument in subprocess.Popen() so use the string
literal '' as iter() sentinel. Using b'' as sentinel is wrong and floods the
queue with void lines.
Drop the unnecessary closing of the stdout pipe, already done in kill_process()
> Use the string literal '' as iter() sentinel

- worker/games.py
For SPSA raise "tc_limit" only once and not at any iteration.
~~Raise also the "scaled_tc" decimal places to 5 for ultra low time control.~~
> Fix "tc_limit" for SPSA

- worker/games.py
- worker/worker.py
combined set of patches for the net download and architecture selection. (i.e. on top of https://github.com/glinscott/fishtest/pull/733)
This should be sufficient to have the worker do the right thing for the NNUE testing (modulo bugs and oversights).
I've connected my worker to this test https://dfts-0.pigazzini.it/tests/view/5f25614a9106dbb0ea3b5b57 with these patches. Seems OK.
To be done:
> Worker changes for NNUE testing

- worker/games.py
I'm not sure what exactly I should do here, but in the Stockfish pull request (https://github.com/official-stockfish/Stockfish/pull/2922 ) vondele said that fishtest worker needs to be changed also.
I don't know how to test this change but this seems simple enough?
I understand that versions need to be incremented. This is NOT done here.
Corresponds to the above-mentioned change for the Stockfish Makefile, however, should work now as is (as SSE4.2 is not used by Stockfish now, other than to display that it was compiled with SSE4.2 support).
> Remove x86-64-sse42 target (corresponds to Stockfish pull request)

- fishtest/fishtest/rundb.py
- fishtest/fishtest/templates/tests_run.mak
currently, with NNUE we expect the different hardware to have slightly different result.
Auto-purge would need to take the ARCH=.. tags into account to work correctly.
As a zero-th order fix, switch default to off.
partially addresses #727
> Change default auto-purge to false.

- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/tests_run.mak
given the change in NNUE Elo and draw rate, a change of bounds was needed.
See discussion in https://github.com/glinscott/fishtest/issues/764
> Adjust SPRT bounds

- worker/games.py
with NNUE some machines get excluded (e.g. opteron cores), which we could keep
Non-urgent worker change.
> Reduce somewhat the minimum NPS

- worker/games.py
This is a follow up to the following PR, which would add support for the targets x86-32-sse41-popcnt and x86-32-sse2.
https://github.com/official-stockfish/Stockfish/pull/3022
> Detect x86-32 targets

- fishtest/fishtest/views.py
- worker/games.py
the changes needed to embed the net in the binary:
https://github.com/official-stockfish/Stockfish/pull/3070
need a change in the magic for finding the default net from sources on both the server and worker. This should be merged before we can merge the above PR
For backwards compatibility we now need to look for the name of the default net in two places.
> Finding the default net from sources.

- fishtest/fishtest/views.py
- fishtest/utils/delta_update_users.py
- worker/games.py
as discussed in https://github.com/glinscott/fishtest/issues/764
use 1.2MNPS instead of 1.6MNPS to account for the bench slowdown after merging NNUE.
This effectively reduces TC by 25%.
No functional change.
> Rescale TC with new NPS

- fishtest/fishtest/templates/tests_view.mak
Fixes https://github.com/glinscott/fishtest/issues/625#issuecomment-629713265 as suggested by @silversolver1
> I mean on the page of an actual test where a user can access the stop/purge, reschedule or modify buttons, next to where the value for itp is listed, there is the word "username". here, the user's particular name does not currently link to that user's /tests/user/ page, which is the feature I am suggesting
I agree this is more practical since I've also commonly wanted to go see a list of the user's tests while on an individual test page.
---
Approvers will see a link to the user admin page in addition to the link to the user tests page.
> Link username to user tests page from tests_view pages

- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/run_tables.mak
- fishtest/fishtest/views.py
The `Pending` section currently mixes both tests that are pending approval, and inactive approved tests.
This separates the `Pending` section into two separate sections:
- `Pending approval` - tests that are not yet approved
- `Paused` - tests that either haven't started running yet, or were modified to have a priority of -1
Open to renaming these sections to whatever people feel is most clear.
Fixes https://github.com/glinscott/fishtest/issues/716
> Use separate homepage sections for pending and paused tests

- worker/games.py
- worker/worker.py
change from 2 to 32 concurrency, should reduce load on the server with
many workers and running SPSA tasks.
This potentially improves
https://github.com/glinscott/fishtest/issues/792
https://github.com/glinscott/fishtest/issues/784
> Adjust SPSA batch size

- fishtest/fishtest/views.py
https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior
The compiler now produces a SyntaxWarning when identity checks (is and is not)
are used with certain types of literals (e.g. strings, numbers).
These can often work by accident in CPython, but are not guaranteed by the
language spec.
The warning advises users to use equality tests (== and !=) instead.
> Fix SyntaxWarning: "is" with a literal

- fishtest/utils/backup.sh
This stops the division in chunks of the file keeping low the CPU load
during the scheduled backups
See https://docs.aws.amazon.com/cli/latest/topic/s3-config.html
> Disable concurrent tranfers for aws s3

- fishtest/production.ini
Default values and higher values showed the same performance in some tests with
2000 machines 17000 cores.
Restoring the threads default values allows to save some RAM useful
to raise the MongoDB cache.
> Restore waitress default for connections/threads

- fishtest/fishtest/templates/nn_upload.mak
should presumably simplify the upload in that only .nnue files should be listed in the 'browse' file selector.
> NN upload accept .nnue

- fishtest/fishtest/static/css/application.css
- fishtest/fishtest/static/css/theme.dark.css
- fishtest/fishtest/static/html/live_elo.html
- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
- fishtest/fishtest/templates/signup.mak
- fishtest/fishtest/templates/tests_stats.mak
This PR adds a sun and a moon icon to the bottom of the sidebar. Clicking on the icons will switch the site between light and dark modes. Dark mode is implemented as a CSS file that's injected into the page to override the default CSS.
Example of how the homepage looks in dark mode:
All suggestions welcome! Some pages that I was unable to view in dev may have unreadable text in dark mode and will need to be fixed. Some standalone pages don't use bootstrap 2 so they haven't been updated to respect dark mode yet. 
Fixes https://github.com/glinscott/fishtest/issues/599
> Enable toggling between light and dark mode

- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
The current status is obvious for light/dark modes.
Use the sun/moon icons for the action (switch to the alternative mode).
https://ux.stackexchange.com/questions/39418/night-day-mode-toggle
https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan?rq=1
> Use sun/moon icons for actions

- fishtest/fishtest/rundb.py
- fishtest/utils/scavenge.py
- worker/games.py
- worker/worker.py
Increase timeout settings because we now batch SPSA results.
In addition workers with 7 or more cores will never show as active because they post only results after 200 played games.
This is caused by a batch size of 32*concurrency.
@vondele I remember you suggested to increase this setting? What would you suggest?
We could adjust with concurrency of workers and NPS.
EDIT: See also https://github.com/glinscott/fishtest/issues/809
> Increase active timeout settings

- fishtest/fishtest/static/css/theme.dark.css
- fishtest/fishtest/static/html/SPRTcalculator.html
- fishtest/fishtest/static/html/live_elo.html
- fishtest/fishtest/static/js/application.js
- fishtest/fishtest/templates/base.mak
Updates the background colors of running tasks and cells in the residual column:
Fixes https://github.com/glinscott/fishtest/issues/811
Fixes https://github.com/glinscott/fishtest/issues/819
> Fix readability of test tasks table in night mode

- fishtest/fishtest/__init__.py
- fishtest/fishtest/api.py
- fishtest/fishtest/rundb.py
- fishtest/tests/test_api.py
- fishtest/utils/scavenge.py
- worker/games.py
- worker/worker.py
See #818 
Add a simple worker heartbeat (every 60s) for reliable scavenging (remove as active after 3 minutes).
Also show a worker immediately when it receives a task and do not wait for the first batch of games to be completed.
Finally replace `utils/scavenge.py` with server logic.
> Simple worker heartbeat to detect dead workers

- fishtest/fishtest/rundb.py
STC jobs suffer from time losses on machines with large concurrency,
probably because cutechess can't keep up with the IO. Workaround this
issue by assigning workers with a concurrency >= 32 to LTC and multi-threaded
jobs
fixes https://github.com/glinscott/fishtest/issues/822
> Do not assign workers with large concurrency to STC jobs

- worker/games.py
build binaries without embedded net, keep a smaller cache of nets
> Save some space in testing dir

- worker/test_worker.py
Fixes a flaky worker test and a subprocess warning when running that test.
i see this test fail when running the test locally and also in recent Travis builds:
https://travis-ci.org/github/glinscott/fishtest/builds/738772657
https://travis-ci.org/github/glinscott/fishtest/builds
here's the failing test output. note that `worker.py [username] [password]` does get printed to stderr but it's no longer being picked up in the unit test. i simplified the test to check against the expected non-zero return code to work around this. not sure why the test started failing.
```
test_worker_script (test_worker.workerTest) ... Worker started in /home/travis/build/glinscott/fishtest/worker ...
Memory: 8364236800
FAIL
/opt/python/3.6.7/lib/python3.6/subprocess.py:766: ResourceWarning: subprocess 3919 is …
```
> Fix worker test: exiting early when given no args

- worker/worker.py
Use a proper logic for the positional arguments ("username", "password"):
- two positional arguments, use the cli data
- zero posizional arguments, use non zero data from config file
- others, write error message and exit
> Fix logic for cli positional arguments

- worker/games.py
Recent testing shows that avx512 can be up to 10% faster than avx2 on certain chips.
Additionally, this makes sure the avx512 arch will be tested on fishtest, improving coverage of the code.
> Start using avx512 again.

- server/fishtest/views.py
The message is now like this:
```The net <net name>, used by <branch>, is not known to Fishtest. Please upload it to: <fishtest_url>/upload.```
where <fishtest_url> is determined via request.host_url.
Addresses: #872
> Hopefully clearer feedback in case of a missing net.

- server/fishtest/templates/tests_stats.mak
Normalized Elo is inversely proportional to the square root of the number of games it takes on average to detect a given strength difference with a given level of significance. In this PR it is given by
```
logistic_elo/(2*standard_deviation_per_game)
```
which in case of a perfectly balanced book and small Elo differences is equal to
```
logistic_elo/sqrt(1-draw_ratio)
```
In other words if the draw ratio is zero, the book is perfectly balanced, and Elo differences are small then normalized Elo and logistic Elo coincide. We say that zero is the "reference draw ratio". A reference draw ratio different from zero would also work. This seems less intuitive however.
The advantage of expressing SPRT bounds in normalized Elo (which is currently not done) would be that the expected test length …
> List SPRT bounds also in "normalized Elo" on the raw stats page.

- server/setup.py
With the new pyramid 2.0 some server tests are failing with the message:
```
from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```
See:
https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html
> Set pyramid to version 1.10

- server/fishtest/api.py
- worker/games.py
- worker/updater.py
- worker/worker.py
The worker is running games from the "testing" folder, so switch folder
before moving the "testing" folder.
Also fix a couple of file reading/writing.
Raise version and trigger the wokers update.
Fix #891
> Switch folder to fix the update process

- server/fishtest/templates/base.mak
- server/fishtest/templates/tests_run.mak
New bounds for STC and LTC tests in fishtest.
The main change is that the new bounds will make LTC tests quite easier to pass Elo-wise.
We have to shrink the intervals to keep good precision, so the total cost will be about three
times longer runs in the worst case.
See discussions in https://github.com/glinscott/fishtest/issues/865 and https://discord.com/channels/435943710472011776/813919248455827515/825466226994053170
> New SPRT bounds for tests

- server/fishtest/static/js/application.js
- server/fishtest/templates/users.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/utils/delta_update_users.py
Ordering users in https://tests.stockfishchess.org/users using "last active" filter led to a wrong output: the program order alphabetically the strings in the column instead of the time passed.
So I try to introduce an user-defined html attribute whose value is the time difference used by delta_date to write the corresponding strings. In order to do this I split the function delta_date in two parts creating a new function called diff_date whose output is the desired time difference in datetime.datetime format. I rewrite every delta_date call letting them to be compliant with the new definition. Hence I converted diff in isoformat and I stored it in user["diff"]. In application.js I introduced another "or" in the first line: my aim is to let the program search "data-diff" attribute, and …
> Bug in ordering users in website: fixing attempt

- worker/games.py
The options `-rounds str(int(games_to_play / 2)) -games 2` was introduced
to mute a cutechess-cli warning.
In fishtest the rounding works because the pentanomial code updates the result
with game pairs, so an unfinished run (after a worker stop) has an even number
of games_to_play.
Use the safer `-games str(int(games_to_play))` option that mutes the warning
and works also with an odd number of games_to_play.
From a prompt by @ianfab
> Use safe "-games" option in cutechess-cli

- server/fishtest/templates/tests_run.mak
Implementing the proposed bounds for classical tests:
classical LTC: Elo{ 0.4;1.7} nElo{0.75,3.25} LTC regression rate 0.9%, 160k games peak, 1.05 elo 50% pass, draw rate 0.73416
classical STC: Elo{-0.3,1.6} nElo{-0.5,2.5} STC regression rate 11.8%, 113.5k games peak, 0.65 elo 50% pass, draw rate 0.60113
See https://discord.com/channels/435943710472011776/813919248455827515/829456512841547787 for the relevant discussion. This is being done to bring the classical STC/LTC bounds in line with the current normalized elo bounds. As an aside, this is my first pull request, my apologies if I've done something wrong here.
> Add SPRT bounds for classical tests.

- server/fishtest/views.py
This is needed for a test I want to run. It will use the HalfkAE5-v2 arch (256x2->32->32->1) from Sopel. The net is 115,525,612 Bytes in size.
> Update views.py to allow for slightly larger nns

- server/fishtest/rundb.py
- server/fishtest/static/js/calc.js
- server/fishtest/stats/LLRcalc.py
- server/fishtest/stats/sprt.py
- server/fishtest/stats/stat_util.py
- server/fishtest/templates/base.mak
- server/fishtest/templates/tests_run.mak
- server/fishtest/templates/tests_stats.mak
- server/fishtest/util.py
- server/fishtest/views.py
Specify SPRT bounds in normalized Elo.
The normalized bounds are indicated using `<>` brackets. Currently they are
```    
standard STC  : <-0.5, 2.5>
standard LTC  : < 0.5, 3.5>
regression STC: <-2.5, 0.5>
regression LTC: <-2.5, 0.5>
```    
leading to a peak expected test duration of `116K` games.
Specific changes:
Update LLRcalc.py, sprt.py and stat_util.py to understand normalized Elo bounds.
Introduce a new Elo model 'normalized' for the sprt object.
Clean up the raw stats page. In particular give variables referring to 'sensitivity' a 'nt' (normalized t) prefix. 'Exact LLR' is renamed to 'Multinomial LLR'.
Add appropriate bound conversions to the raw stats page.
Show normalized LLR's on the raw stats page.
Generic bounds formatting ([],{} or <>).
Put normalized bounds in …
> Use normalized Elo input for Fishtest

- server/fishtest/views.py
When rescheduling a test, fishtest previously used the cached commit sha to retrieve
the code to execute, but fetched the net using only the branch name.
This leads to race conditions if the default net of the corresponding branch was changed in
the meantime as observed in issue https://github.com/glinscott/fishtest/issues/919
To fix the problem use the commit sha also to fetch the net.
Note: I do not have a local fishtest installation to test this fully, so please test with care before merging.
> Use commit sha to retrieve net.

- server/fishtest/stats/LLRcalc.py
- server/fishtest/templates/tests_stats.mak
I have now found a relatively elegant numerical procedure to compute the exact LLR for normalized Elo. It is documented in S4.1 of this document
https://hardy.uhasselt.be/Fishtest/normalized_elo_practical.pdf
I simulated it for a SPRT<0,5> with a draw ratio of 99% and the error probabilities were close to 0.0500.
> Exact LLR for normalized Elo.

- server/fishtest/views.py
- server/utils/delta_update_users.py
- worker/games.py
The recently added new net arch introduced a slowdown. On my system it is 6.8% slower. In the commit it is said to be 15% to 20% slower. I guess this could vary quite a lot between different CPU instruction sets. For now I decreased base_nps by 10% but there are arguments to be made to change it less/more depending if we change on most commonly supported instruction set on fishtest, slowest arch or fastest arch etc.
I hope @vondele and @snicolet have recommendations on how to deal with this matter.
Edit: meant to open as a draft but well... new to git ^^
> Decrease base nps

- README.md
Follow the official documentation template, see
https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge
> Improve GitHub workflow status badge

- server/utils/create_indexes.py
Fixes a deprecation warning during the initial setup of the server.
`collection_names()` is deprecated since pymongo 3.7.
See: [https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-7-0](https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-3-7-0)
> Fix deprecation warning for collection_names

- server/fishtest/util.py
Post on the new group https://groups.google.com/g/fishcooking-results because
the old one has not an active owner
(https://groups.google.com/g/fishcooking_results)
Use an email address from stockfishchess.org to fix the DMARC check
Fix #945
> Fix posting tests results on googlegroup

- server/fishtest/templates/signup.mak
- server/fishtest/templates/user.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/setup.py
- Fixes a bug where a non-matching verification password in user profile causes internal server error.
- Introduces an offline, password strength validation for signup and password change operations. Existing passwords in the userdb are not subject to a minimum strength evaluation.
- Adds notifications upon email and/or password updates on user profile page. Relevant errors are displayed as well, accordingly.
- Skips email update if the email field matches the db entry. 
- The mako template for user profile page specifies the same minimum 8 character requirement for the password as the signup
Fixes #953
> Add password strength requirement

- server/fishtest/rundb.py
in addition to the TT, we allocate quite some memory for the net.
Add a base estimate of memory usage per process.
This might fix some timeout observed on workers, that might be paging.
> Refine memory check a bit

- server/fishtest/views.py
Update the NN db only after a successful upload.
> Stop NN upload process after exception

- server/fishtest/templates/base.mak
- server/fishtest/templates/machines_table.mak
This copy the elements order used for the "Worker" column in tasks table.
Also change a link to https.
> Switch "UUID/Cores" columns in machines table

- worker/worker.py
This one is the right one, sorry for missing your message on the previous PR https://github.com/glinscott/fishtest/pull/966
> Fix missing word in error message for --concurrency

- worker/games.py
In case of a bug thas is OS dependent we can have some workers that waste CPU
failing to setup the engine while the test seems to run fine in the dashboard.
The fishtest server already stops a test only for user with at least 1000 hours
of CPU contributed, so a beginner mistake in setup the worker toolchain
cannot stop a test.
> Stop the test after failing to setup an engine

- server/fishtest/rundb.py
Of course this is a purely cosmetic issue. Trinomial and pentanomial "statistics" for zero games are computed from a weak fictitious prior. They are equally meaningless.
Fixes #1015
> On the raw stats page show pentanomial statistics from the beginning.

- server/fishtest/rundb.py
The frequency modified here determines the scaling on the x-axis of graphs of tuning tests. Currently the scaling can be any multiple of 25, e.g. 375 or 425, which is not very intuitive for the user. Also, the last data point from the test is often not displayed on the graph as numbers like these tend not to divide exactly into the number of games in a test. This change ensures that the frequency is a multiple of 100 and divides neatly into 10,000, making the graph more intuitive for users.
> Use multiples of 100 for freq.

- server/fishtest/util.py
In this way the worker key becomes a property of the worker and not of the sequence of tasks used to compute it.
This what I want to say about getting rid of the sequence numbers. After that further simplifications can be made.
This was not live tested.
> Get rid of sequence number in the worker key.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/templates/tests_view.mak
- server/fishtest/util.py
This should be a non functional conceptual simplification.
The worker key tries to solve two unrelated problems:
(1) Long ago workers did not have to a unique key, so a substitute has to be provided for the chi2 test.
(2) The unique key is not suitable for displaying, and perhaps should be kept secret as well. So the worker key is displayed instead.
Now we simply provide two functions
unique_key(worker_info)
worker_name(worker_info)
corresponding to (1,2).
Not live tested.
> Get rid of worker_key altogether.

- server/fishtest/rundb.py
- server/fishtest/templates/tests_view.mak
- server/tests/test_api.py
The pending flag is True when a task is not finished. It was always redundant since it can be recomputed from the number of games received on a task and the task size.
However, now that there is no task migration any longer, the pending flag has become even more redundant since, if a worker goes offline, the task it was working on will never receive any further updates, no matter what the pending flag says.
Another issue with the pending flag is that the word "pending" is also used in other contexts (e.g. a run may be pending). This creates confusion.
> Get rid of the flag "task['pending']".

- server/fishtest/rundb.py
After the purge a test is automatically queued to play the purged games.
An old test could lack some dictionary keys making unsafe the queueing.
Thanks to @vdbergh for reporting and debugging the problem.
> Purge a test only if not older than 30 days

- server/fishtest/static/css/application.css
- server/fishtest/static/css/theme.dark.css
- server/fishtest/static/html/SPRTcalculator.html
- server/fishtest/static/html/live_elo.html
- server/fishtest/static/js/application.js
- server/fishtest/templates/actions.mak
- server/fishtest/templates/base.mak
- server/fishtest/templates/elo_results.mak
- server/fishtest/templates/login.mak
- server/fishtest/templates/machines_table.mak
- server/fishtest/templates/nn_upload.mak
- server/fishtest/templates/nns.mak
- server/fishtest/templates/pending.mak
- server/fishtest/templates/run_table.mak
- server/fishtest/templates/run_tables.mak
- server/fishtest/templates/signup.mak
- server/fishtest/templates/tests.mak
- server/fishtest/templates/tests_run.mak
- server/fishtest/templates/tests_stats.mak
- server/fishtest/templates/tests_view.mak
- server/fishtest/templates/users.mak
Makes the site feel more modern since bootstrap 2.3.2 is 8+ years old (Jul 2013) and 5.1.1 was released a few weeks ago. Most of the site should still look similar.
Bootstrap 5.1 docs:
https://getbootstrap.com/docs/5.1
There will likely be issues since I didn't exhaustively check every page and don't have much test data to do so.
issues found by ppigazzini:
> Upgrade bootstrap from 2.3.2 to 5.1.1

- server/fishtest/static/js/spsa.js
- server/fishtest/templates/tests_view.mak
The problem was newer bootstrap uses a new `data-bs-toggle` attribute to mark a button as a dropdown toggle.
Fixes https://github.com/glinscott/fishtest/pull/1044#issuecomment-927500322
> Fix toggling individual spsa parameters dropdown

- server/fishtest/__init__.py
- server/fishtest/templates/base.mak
This enables auto-updating cache buster query params when static files change. The goal is to:
- not require users to manually hard refresh the page when css/js files change
- not require devs to manually update cache buster query params when css/js files change
This implementation:
- calculates the md5sum of the listed static files when the server starts
- uses the md5sum of the static file as a query param when serving the file
Prompted by https://github.com/glinscott/fishtest/pull/1044#issuecomment-927375281
> Enable using dynamic cachebusters for static files

- server/fishtest/__init__.py
- server/fishtest/static/js/application.js
- server/fishtest/templates/base.mak
This makes edits to `dark.theme.css` more convenient, since we'll no longer have to manually calculate the sha256sum and update `application.js` to fix the dark/light toggle.
The expected behavior is now:
- make `dark.theme.css` changes
- restart the server, and the toggle will automatically work
> Automatically set dark.theme.css sha256 during server init

- server/fishtest/api.py
- worker/updater.py
- worker/worker.py
The old "requests" packages is incompatible with python 3.10 and lacks the
updated list of root certificates to work with Let’s Encrypt, see:
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
Add temporary code to delete the old "requests" package:
1. at the next worker update: rename the "requests" directory to "_requests"
to have a backup in case of problems for some users
2. at the successive worker update: delete the "_request" directory
> Delete the old "requests" package

- server/fishtest/api.py
- worker/updater.py
- worker/worker.py
This ensures that we only have updated and consistent files.
The switch to the new "requests" package was problem free so skip
the backup step.
> Delete the "packages" folder during an upgrade

- server/fishtest/rundb.py
A Windows 10 worker running with a modern CPU (it should be a 36 cores + HT)
had many time losses with concurrency 64 or 71 in SMPT test at 8 threads 20+0.2
With the same configuration the worker ran without problems all his LTC task.
The Windows 10 Pro seems to be suboptimal for high count threads, see
https://www.anandtech.com/show/15483/amd-threadripper-3990x-review/3
Thanks to: @Vizvezdenec (bug report) @vondele (fix idea)
> Only LTC task to Windows high concurrency worker

- server/fishtest/actiondb.py
- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/templates/actions.mak
- server/fishtest/views.py
- worker/games.py
- worker/test_worker.py
- worker/worker.py
Post a message in the server log.
Post a message in the actiondb.
Introduce "WorkerException" for standard exceptions.
One does not want to record all exceptions on the server since this would include things like syntax errors, potentially even leading to privacy issues.
If one raises WorkerException(reason) in run_games() then the reason will be recorded on the server using the "failed_task" api. Exceptions caused by syntax errors etc... are of course not of the type WorkerException. Such exceptions will be recorded on the server with the file name and the line number where the exception occurred.
Also: fix a bug in pgn uploading created by the last commit.
> Give server feedback for failed tasks.

- worker/worker.py
This is again to prevent flooding. Such exceptions are likely to be unrecoverable.
> Make implicit exceptions (of the type filename:fileno) fatal.

- worker/games.py
It took me a bit of time to understand this.
> Add a comment why there is no failed_task message after stop_run.

- worker/games.py
For a failed get_request use the exception in the error message.
I don't want to do this for post requests since I am afraid it may expose passwords. Even if it does not now it may do so in future versions of the requests module.
Raise an exception on http status codes >= 400.
This is apparently not done by default by the requests module. See
https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module
for background.
See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes for http status codes.
> For a failed get_request use the exception in the error message.

- server/fishtest/templates/base.mak
- server/fishtest/templates/tests_run.mak
slightly narrower interval to avoid flukes. Slightly more difficult to pass Elo gains STC, somewhat more easy to pass Elo gains LTC.
> New bounds for SPRT tests

- server/fishtest/templates/machines_table.mak
- server/fishtest/templates/tests_view.mak
Also show in a separated column the python version and reorder the columns.
> Show gcc version in home and test pages

- server/fishtest/static/js/application.js
The original table sorting code (first reference) sorts for:
- numerical order: for strings that are a number
- lexygraphical order: for other strings
Using the second reference add also:
- numerical order: for strings that are a dotted version (eg 3.10.12)
Also add a comment with the references.
https://stackoverflow.com/questions/14267781/sorting-html-table-with-javascript
https://stackoverflow.com/questions/40201533/sort-version-dotted-number-strings-in-javascript
> Sort the table rows for dotted version header

- server/fishtest/rundb.py
256 appears to be insufficient, in some cases, to capture  a representative part of the error messages associated with a failed build.
> Increase the maximum length of an action message to 1024.

- worker/worker.py
We may have several processes reading from and writing to the lock file at the same time with potentially unpredictable consequences (especially on windows). We now refactor the file IO operations and put them in a try: except: bracket.
We also change the logic:
At the start of the worker we tolerate an invalid or non-existing lock file since we intend to replace it with one of our own. Once  we have started, we now only accept a valid lock file containing our own PID.
Also: the name of the lock file is not a global variable anymore.
Also: send stderr to devnull on Linux. Like it is done on Windows.
> Make lock file system more robust.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/util.py
- server/tests/test_api.py
- server/tests/test_users.py
- worker/games.py
- worker/worker.py
This allows for simplification of downstream code. Notably `failed_task()`, `update_task()` and `request_spsa()`.
We do the validation when parsing the arguments. For example `self.task_id()` will throw a `HTTPBadRequest()` exception if it does not succeed in returning a `task_id` corresponding to an existing task. So downstream code may assume that a `task_id` argument is valid.
The same mechanism has allowed us to simplify `api_stop_run` which had recently ballooned because of argument validation.
To check that the api arguments are syntactically correct we provide a rudimentary, but generic, "schema" implementation in `utils.py:validate()`.
> Do more validation of api arguments in api.py.

- server/fishtest/templates/tests_run.mak
Firefox apparently has this weird behavior to change number inputs when the scroll wheel is used. This triggered some unintended off-by-one errors when submitting tests.
> Prevent scroll wheel from changing bench for firefox users.

- server/fishtest/views.py
The neural network server has often a low uploading bandwidth, stopping
the upload process with a timeout error.
The issue is solved:
- raising the HTTP_TIMEOUT with this PR, and
- caching the upload request with Cloudflare ("fishtest.upload" server
configuration)
> Raise HTTP_TIMEOUT for neural network upload

- worker/games.py
Tested with 
https://dfts-0.pigazzini.it/tests/view/61a550c37347b974ba95a02f
In this case the intervals when setting up the test were declared to be `[-1024,1024]` whereas the intervals used by this branch of SF were `[-128,128]`.
See https://github.com/glinscott/fishtest/pull/1170#issuecomment-982294779 .
> Stop the run if the server sends invalid SPSA options.

- worker/games.py
If the server finishes a SPRT test then it takes a long time before the worker actually kills cutechess-cli.
We try to fix this by sending a SIGINT first. This works correctly on Linux. cutechess-cli will write the pgn and then quit.
I cannot test if it works correctly on Windows since I don't have windows.
> Send a SIGINT to cutechess-cli to give it a chance to exit nicely (Linux only).

- worker/games.py
On Windows the signalling of the CTRL+C event requires a disposable process.
References:
https://stackoverflow.com/questions/7085604/sending-c-to-python-subprocess-objects-on-windows
https://stackoverflow.com/questions/813086/can-i-send-a-ctrl-c-sigint-to-an-application-on-windows
https://docs.microsoft.com/en-us/windows/console/freeconsole
https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler
https://docs.microsoft.com/en-us/windows/console/attachconsole
https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent
Added some controls before signalling to minimize
the race condition probability.
> Send CTRL+C to cutechess-cli on Windows

- server/fishtest/actiondb.py
- server/fishtest/static/css/application.css
- server/fishtest/static/css/theme.dark.css
- server/fishtest/templates/actions.mak
This is similar to system events.
A dead task may for example be caused by a user closing their laptop. Or a colab worker being disconnected.
Dead tasks do not carry a lot of information (they have no associated message) and there are a lot of them.
But the fact that a task was declared dead can explain why a pgn file was not uploaded. So it might still be useful to have a record of them.
> Do not make dead tasks visible by default in the events log.

- server/fishtest/views.py
- worker/games.py
- worker/worker.py
- drop deprecated `Threads.setDaemon()`
- drop unused `json` library
- drop `from os import path` for the already used `os.path()`
- simplify import for `multiprocessing` and `ctypes`
- fix the print of old gcc version
- improve CPU count code
- run black and isort
> Little clean up

- worker/games.py
- worker/worker.py
MAX_RETRY_TIME: speedup recovery time after longer fishtest outages.
HTTP_TIMEOUT: allow a little more time for longer downloads
> Adjust network timeouts

- server/fishtest/rundb.py
- server/fishtest/views.py
(1) Avoid making a copy of the task list in `del_tasks()`.
(2) Use `buffer(run,False)`.
(3) Do not grab the active run lock (there seems to be no point).
> Make `failed_task()` less expensive.

- server/fishtest/util.py
as discussed in the issue, our estimate is probably relatively accurate.
It might 'feel' wrong, as it reports the time needed to empty fishtest
assuming no further patches are submitted.
This updates one of the parameters to the current measured value.
fixes https://github.com/glinscott/fishtest/issues/879
> Adjust remaining hours estimate

- worker/games.py
This was suggested by @vondele.
Also: log api calls, with timestamp, to a file "api.log".
> Add timestamp to api timings.

- worker/games.py
- worker/worker.py
If Ctrl-C happens during `/api/update_task` then this leads to a "Finished match uncleanly" and moreover it takes `15s` before the worker quits. This PR should fix this.
> Fix a problem with Ctrl-C during /api/update_task.

- worker/worker.py
`/api/pgn_upload` takes only a few ms in normal circumstances. Even if it takes longer then there is already a huge amount of randomness built in because the workers only call home when a game is finished (and there is also the batch size...).
> Eliminate the random delay before pgn uploading.

- server/fishtest/__init__.py
- server/fishtest/api.py
This makes it convenient to inspect tasks from long ago before the current db schema crystallized. It's another step towards db conversion.
Tweaks in the returned task.
- The `unique_key` is truncated to 8 characters.
- The remote address is replaced by "?.?.?.?".
- If `"task_id"` ends with `"bad"` then the api call returns the corresponding element from `run["bad_tasks"]`.
- `task["last_updated"]` is replaced by a string since json does not know about `datetime`.
- If `task["residual"]` is infinite then it is replaced by the string `"inf"` since JSON does not know about infinity.
> Introduce `/api/get_task/{id}/{task_id}`

- server/fishtest/api.py
- server/fishtest/rundb.py
- Add a comment why `tc_base` is needed (it is used for an index).
- Remove the unused field `new_tc`.
- For consistency always set the `country_code` field in `worker_info`, even if it is unknown.
- Initialize the fields `crashes` and `time_losses` during run/task creation.
> Various tweaks in preparation of db conversion.

- server/fishtest/templates/tests_view.mak
Fast fix for an issue that happens for very old tests when logged in as approver.
> Drop link for "Unknown_worker"

- server/fishtest/rundb.py
- server/fishtest/views.py
Queries in mongodb for missing flags are a bit messy. This is the first step at fixing this. The next step is to loop through the runs collection and set/unset these flags as needed. **Both steps should be mostly non functional for now** (except for a few bug fixes along the way).
Also: we document where the flags
`finished`, `failed`, `deleted`, `is_green`, `is_yellow` are set and unset.
> Create `failed`, `deleted`, `is_green`, `is_yellow` flags in new_run.

- server/fishtest/rundb.py
- server/utils/upgrade.py
1) We replace a `unique_key` `xxxxxxxx` by a random `unique key` depending on `worker_name`.
Making the `unique_key` equal to `xxxxxxxx` if it was missing, messes up the residual calculation for old tests.
After this replacement we can retire `unique_key` in `utils.py`.
2) We replace the fields in `run["args"]` which are "?" by "". This corresponds to the defaults in `new_run()`.
3) Set the flags `finished`, `failed`, `deleted`, `is_green`, `is_yellow`, if they are missing.
I see no issues running this against a live system. It changes the `runs` collection in place.
> Further cleanups in the db.

- server/fishtest/templates/tests_stats.mak
The pentanomial draw ratio is the ratio of `DD+WL+LW` results (i.e. non-decisive game pairs).
When the probability of double wins/losses is low then normalized Elo may be approximated as
```
nElo = sqrt(2)*Elo/sqrt(1-d)
```
Here `Elo` denotes `logistic Elo` and `d` is the pentanomial draw ratio.
> List the pentanomial draw ratio on the raw stats page.

- server/fishtest/views.py
I think the format of the pager has changed over the years. As a result the code for disabling the Next button is no longer correct.
In this PR the Next button is disabled when
```
page_idx>=(num_finished_runs - 1) // page_size
```
where `page_idx=<current page no>-1`.
Examples:
```
num_finished_runs=75, page_size=25
```
We have 3 full pages. So Next should be disabled if the current page number is 3. I.e. if `page_idx=2`. This is what the formula gives.
```
num_finished_runs=76, page_size=25
```
Now we have 4 pages, the last one containing 1 run. So Next should be disabled when `page_idx=3`, which is again what the formula gives.
Note:
Since we currently do not exclude deleted runs from our queries, but filter them out later instead, it is theoretically possible to have empty pages. This …
> Fix formula for disabling "Next" button in pager.

- server/fishtest/rundb.py
- server/fishtest/views.py
This is an attempt to fix #1247 by reordering `stop_run()` and enhancing `purge_run()`.
We now let `stop_run()` completely stop the run and _then_ we invoke `purge_run()`, if `auto_purge` is enabled. `purge_run()`, which can now only be invoked on a finished run, will usually revive the run, _except_ when the test is an sprt test and after purging the LLR is outside the bounds (this part is new).
This PR is almost completely untested.
> Refactoring `purge_run` - again.

- worker/games.py
- worker/worker.py
Additions to support clang and apple-silicon (which is far more efficient on a M1 hardware (factor 1.7 vs. x86-64 arch)).
Tested on Mac with Intel and M1 cpu and on Windows 10 with Intel 64-bit cpu.
In order to make things perfect for Mac users a cutechess-cli with static linked qt5 would be fine. I can provide you with a binary that runs on Intel and M1 macs. If you upload it I can make the changes in games.py to check and download it to the testing dir if it is missing. Please drop me a note.
> add_clang_and_m1_support

- worker/games.py
This seems to work without further ado:
...
Running simpLimitExtension vs master
Variable task sizes used. Opening offset = 108600
Downloading cutechess-cli-macos-64bit.zip ...
Obtaining version info for /Users/raimundheid/Applications/forked_fishtest/worker/testing/cutechess-cli ...
Found:  cutechess-cli 1.2.0
...
> download missing cutechess-cli for macos

- worker/games.py
Tested on Mac with M1 and gcc 11.2.0.
IS_MACOS and props["arch"].startswith("armv8") 
would be a bit speculative but is worth to be considered.
> support apple-silicon when COMP=gcc

- server/utils/backup.sh
The new version of mongodump exports the collections with a higher level
of gzip compression, so the second gzip compression can be safely dropped:
-rw-rw-r--  1 fishtest fishtest 1851822080 Jan 26 14:58 dump.tar
-rw-rw-r--  1 fishtest fishtest 1809900535 Jan 26 12:20 dump.tar.gz
> Drop the final gzip for mongodb backup

- worker/packages/expression/__init__.py
- worker/packages/expression/interpreter.py
- worker/packages/expression/parser.py
- worker/worker.py
This is a more generic solution for #1265.
Examples:
```    
--concurrency max-1            # leave 1 core for the OS
--concurrency min(4,max/2)     # reserve half of the cores for
```    
We compute the defaults for `concurrency` and `max_memory` in the configfile.
A freshly minted configfile now contains
```    
concurrency = 1 if max==1 else min(3, max-1)
max_memory = max/2
```
If the expression for `concurrency` does not contain "max", `concurrency` is limited to `max_cpu_count-1`. Otherwise it is limited to `max_cpu_count`.
> Allow expressions involving `max` for `--concurrency` and `--max_memory`.

- server/setup.py
Update the entry_points format in setup.py according to the Pyramid
instructions to work with the latest setuptools version 60.9.0
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/project.html
The fishtest Pyramid project files are still a bit outdated with respect
to the latest version created with cookiecutter.
> Update the entry_points for setuptools 60.9.0

- server/fishtest/rundb.py
The SPSA graph x-axis is now the percentage of completion after the recent
commits to "spsa.js".
This companion PR:
- simplify the updates of the SPSA parameters history
- set the max size of the SPSA history parameters list to 10000 entries
- fix the bug that limited the parameters history to a max of 250k iterations
> Simplify the update of the SPSA history parameters

- server/fishtest/templates/tests_view.mak
In Boostrap the sticky style has "z-index: 1020" and the dropdown style
has "z-index: 1000", so one of the SPSA parameters from the dropdown menu
cannot be selected because it is overlapped by the sticky table header.
Raise the z-index for the dropdown menu to set the proper stacking order.
https://getbootstrap.com/docs/5.0/layout/z-index/
> Fix table header overlapping the dropdown menu

- worker/worker.py
Print the name of an unclassified exception in the event log.
Example: https://tests.stockfishchess.org/actions?count=1&before=1649400523.77
> Print exception name

- server/fishtest/__init__.py
- server/fishtest/static/js/application.js
- server/fishtest/templates/tests.mak
- server/fishtest/views.py
The old code refreshed the machines table content using a dedicated view
to avoid the costly reload of the whole home page.
However the code had some problems:
- the smart refresh worked only for the first click over the "Show" button
- the refresh of an open machines table required anyway the reload
of the whole home page
- the control logic was spreaded in a couple of views,
in a couple of mako templates and in one js script
> Simplify the machines table code

- server/fishtest/static/js/application.js
- server/fishtest/templates/tests_view.mak
- server/fishtest/views.py
The test page loads faster (and uses less RAM) with the tasks table
closed, very useful to open a test with many tasks, see https://github.com/glinscott/fishtest/issues/1299.
Use a cookie to remember the state of the toggle.
> Add a toggle button for the tasks table

- server/fishtest/static/js/gkr.js
Our implementation of the gaussian kernel regression works bad when the range
of y values is big, so normalize the y values in [0, 1] before the regression.
This is a fast fix, the gaussian regression code needs a review.
> Normalize the y values in SPSA gaussian regression

- server/fishtest/static/js/spsa.js
The default vAxis setting often compresses the range of negative data
in order to insert the x-axis in the chart.
https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options
> Expand the vertical range of data in SPSA chart

- server/fishtest/api.py
- server/fishtest/views.py
- server/utils/delta_update_users.py
- worker/games.py
- worker/worker.py
Fishtest with Stockfish 11 had 1.6MNps as reference Nps and 0.7MNps as
threshold for the slow worker.
Set the new reference Nps according to the average 17% slowdown.
Set the new threshold for slow worker according to the 21% slowdown.
- arch=bmi2 (Dual Xeon workstation)
```
sf_base =  1517458 +/- 9427
sf_test =  1259909 +/- 10794
diff    =  -257549 +/- 9477
speedup = -0.169724
```
- arch=modern (core i7 3770k)
```
sf_base =  1864275 +/- 20969
sf_test =  1466315 +/- 7262
diff    =  -397959 +/- 14643
speedup = -0.213466
```
The speedups are nearly the same measured after the switch to the new net arch
https://github.com/official-stockfish/Stockfish/pull/3927
- arch=bmi2 (Dual Xeon workstation)
```
sf_base =  1566536 +/- 6407
sf_test =  1308257 +/- 5827
diff    =  -258279 +/- 4440
speedup = …
```
> Set the SF15 reference Nps using SF11 as base

- server/fishtest/static/css/theme.dark.css
The light theme does not have this border, the table size difference is
very noticeable in a SPSA test with many parameters when switching
between the two themes.
> Drop the table "border-top" from dark theme

- server/fishtest/templates/tests_run.mak
- server/fishtest/views.py
The A parameter avoids instability in early SPSA iterations,
the seminal paper suggests to set it at 10% of the total iterations.
fishtest used the default A=3000 (10% of the default 30000 iterations)
that is too small for SPSA ran with 250-500k iterations.
- Ask for the "A_ratio", decimal in range [0; 1], in the new SPSA test
form.
- Set as default value the 10% of total iterations.
- Compute the "A_ratio" when rescheduling a SPSA.
- Backward compatibility saving in the DB "A = A_ratio * iterations"
> Set SPSA A proportional to the total iterations

- server/fishtest/static/js/spsa_new.js
Since the book is unbalanced, this commit introduces a
"virtual" draw_ratio defined as
`1 - 4 * ("pentanomial variance/game")`.
Further informations can be found in the closed issue and here:
https://github.com/vdbergh/spsa_simul/blob/master/doc/theoretical_basis.pdf.
Many thanks to @vdbergh.
Closes #1327
> Optimize SPSA Autoselect for "UHO_XXL_+0.90_+1.19.epd"

- worker/worker.py
At one point the variable `max` was renamed as `MAX` and there was a bit of code to automatically convert config files. By now all config files should have been converted.
> Delete deprecated code in the worker.

- server/fishtest/rundb.py
Might fix some of the crashes we currently see of fishtest for a test with 8 threads and 512MB hash.
> Refine memory estimate

- server/fishtest/util.py
- worker/worker.py
Example:
```
$ python worker.py --uuid_prefix `hostname -s`
…
^C
$ cat uuid.txt
pl-f91e-4757-950d-392ca20856dc
```
`--uuid_prefix _hw` resets the prefix to one depending on the system (default).
> Preserve the first 8 characters of the uuid across restarts and make them user settable.

- worker/worker.py
Currently "Štockfish" is allowed.
> Restrict uuid_prefixes to alphanumeric _ascii_ strings.

- server/fishtest/api.py
- worker/games.py
- worker/worker.py
Skip profiled build for Apple silicon
Workers with Apple silicon stopped building stockfish:
```
reason: 'Executing make -j 4 profile-build ARCH=apple-silicon COMP=clang failed.
Error: ['warning: default.profraw: Unsupported instrumentation profile format version\n', 'error: No profiles could be merged.\n', 'make[1]: *** [clang-profile-use] Error 1\n', 'make: *** [profile-build] Error 2\n']'
```
See https://stackoverflow.com/questions/71580631/how-can-i-get-code-coverage-with-clang-13-0-1-on-mac
A MacOS worker is running fine with clang, so at the moment
skip the profiled build only for Apple silicon.
Also raise worker version.
> Skip profiled build for Apple silicon

- worker/worker.py
See #1364 
Tested by replacing "ps" by "busybox", "ps" in the Popen statements and running the script
```sh
python worker.py &
python worker.py &
sleep 1
killall python g++ make
```
EDIT: It also works with the docker image
```
vdbergh@pl2:~/fishtest-docker$ sudo docker run -it  --pid=host -v worker-dir:/opt/fishtest/worker -e concurrency=1 fishtest
______ _     _     _            _                        _
|  ___(_)   | |   | |          | |                      | |
| |_   _ ___| |__ | |_ ___  ___| |_  __      _____  _ __| | _____ _ __
|  _| | / __| '_ \| __/ _ \/ __| __| \ \ /\ / / _ \| '__| |/ / _ \ '__|
| |   | \__ \ | | | ||  __/\__ \ |_   \ V  V / (_) | |  |   <  __/ |
\_|   |_|___/_| |_|\__\___||___/\__|   \_/\_/ \___/|_|  |_|\_\___|_|
Worker started in /opt/fishtest/worker ... …
```
> Fixes for busybox.

- server/fishtest/helpers.py
Bug reported by locutus2 (as well as the bugfix):
https://discord.com/channels/435943710472011776/900771437177094156/991994320464908418
> Fix broken SPSA's diff if the repo is too old

- server/fishtest/static/css/application.css
- server/fishtest/templates/tests_view.mak
This changes the amount of parameteres that are shown for the SPSA dropdown before the user has to scroll down.
With this change the SPSA dropdown should look like this:
Before it was:
> Limit SPSA Parameter dropdown

- worker/games.py
- worker/updater.py
- worker/worker.py
Logic:
1) Check if cutechess-cli exists and is working.
2) If not: download it.
3) Check if downloaded cutechess-cli is working.
4) If not: try to restore a backup copy.
5) If successful check if the backup copy is working.
6) If not: bail out.
Also: do not treat MacOS specially in the updater.
Also: only setup/verify during worker startup.
Solves #1368 .
> Try a backup copy if the downloaded cutechess-cli is not working.

- server/fishtest/static/js/application.js
- server/fishtest/templates/nns.mak
- server/fishtest/templates/run_table.mak
- server/fishtest/templates/tests.mak
- server/fishtest/templates/tests_view.mak
Explicitly set SameSite to Lax to treat FireFox warning (in the browser console) of new Cookie standard when clicking on the "finished button"
- Lax is the default we already have but setting it explicitly to make cookies standardized for most browsers and treat the warning
- Lax option allows HTTP cookie transmission which is what we have for buttons state and is convenient for Dev purposes in testing on other devices in the same network
- Note that any sensitive cookies introduced in the future should be flagged as secured and not Lax but these button-states are not sensitive data and we don't provide them to third parties after dropping google analytics 
For any new use of cookies in sensitive data,
see the options available at: …
> Adapt to new MDN standard with explicit SameSite

- server/fishtest/actiondb.py
- server/fishtest/views.py
Limit the count if max_actions is used (credits to @ppigazzini)
Correct value in url in case user uses a max_actions value larger than count
> Fix events pagination

- server/fishtest/views.py
this should in principle increase the performance of the load on the test pages, this minimal solution is dropping out cache control support of old legacy browsers while still unifying the back button mismatched behavior in different modern browsers
> Minimal solution for cached requests with wrong states

- worker/sri.txt
- worker/test_worker.py
- worker/worker.py
The sri hashes of the current worker files are stored in a file `sri.txt`. This file is updated each time the worker runs, and it can also be updated manually with
```    
python worker.py --only_config
```    
CI is used to enforce that the file `sri.txt` matches the worker files during pushes or pull requests.
The worker will also download the master `sri.txt` (currently not existing) 
https://raw.githubusercontent.com/glinscott/fishtest/master/worker/sri.txt
and check if the hashes in that file coincide with the sri hashes of the current worker. If not then a message is printed on the terminal. A tainted worker is not stopped but the flag `worker_info['modified']` is set to `True`. In a subsequent PR the server will use this information in the event log messages (for debugging …
> Compute sri hashes of worker files and compare with master

- worker/worker.py
The first (constant) part of the UUID is now written as a comment in the config file. This is sufficient to identify the worker.
> Retire uuid.txt.

- worker/sri.txt
- worker/worker.py
This is to handle another race condition. Namely the fact  that it takes some time for https://raw.githubusercontent.com to update after a push. See
https://github.com/glinscott/fishtest/pull/1445#issuecomment-1304848578
> Ignore the master sri if it has a different version number

- server/fishtest/static/css/application.css
This fixes the expanded page width issue reported on discord, x-axis appears with an x-scrollbar when the code in the diff is too long and ruins the layout (mostly in windows and macos).
For reference see: 
1- https://tests.stockfishchess.org/tests/view/6389512bd2b9c924c4c60151
2- https://tests.stockfishchess.org/tests/view/6385efc7d2b9c924c4c56abe
before:
after:
> pre-wrap `<code>` to fix expanding width issue in test view

- server/fishtest/templates/actions.mak
- server/fishtest/views.py
Currently the handling of events is a mess, so we want to fix this. The practical aim however is to provide more options for searching in the future (on the worker name and the comment field).
This project requires a fair number of changes. So the plan is to break it up into several consecutive mergeable PR's.
*Strategy*
- Extract data from the current description field (i.e. `task_id`, `worker name`, `message`) and use it in the new event log format (PR1, i.e. this one).
- Put the extracted data back into the action collection and use the action collection directly to show the event log. Also convert the old action records to the new format (PR2).
- Change the rest of fishtest to put the data directly into the action collection in the new format. No more parsing of the description field …
> Change the handling and presentation of events (PR1)

- server/fishtest/actiondb.py
- server/fishtest/templates/actions.mak
- server/fishtest/views.py
- server/utils/create_indexes.py
For this to work one needs to run
utils/create_indexes.py actions
to create a text index on the string fields of an event:
action, username, worker, message, run, nn.
> PR4: Add a free text search field to the event log page.

- server/fishtest/templates/actions.mak
- server/fishtest/views.py
It seems that using `${string|u}` in a mako template implies that `string` is first encoded as a URL and then again as html. This seems wrong to me if the URL is used as a href and gives strange results if the parameters are then used in a text field.
The workaround seems to be to use `${string|u,n}`. This is what we do in this PR.
Although it seems to be no longer required in html5 we are encoding the `&` separating the parameters by `&amp;`.
> Fix quoting the proper way

- server/fishtest/static/css/application.css
- server/fishtest/static/css/theme.dark.css
- server/fishtest/templates/actions.mak
- server/fishtest/templates/tests_view.mak
- server/fishtest/views.py
Also: include the bytes 2-4 of the run_id in the run name (there may be many tests with the same branch, currently these are indistinguishable).
One cannot yet search for the extra data. This will require again a database conversion.
> Make the task target links in the event log point to tasks.

- server/fishtest/views.py
fixes:
```
Dec 17 13:17:10 tests.stockfishchess.org pserve[22144]:   File "/home/fishtest/fishtest/server/fishtest/views.py", line 194, in sync_upload
Dec 17 13:17:10 tests.stockfishchess.org pserve[22144]:     "Network upload failed: " + str(response.status_code), "error"
Dec 17 13:17:10 tests.stockfishchess.org pserve[22144]: UnboundLocalError: local variable 'response' referenced before assignment
```
> fixe access to the response variable

- server/fishtest/rundb.py
- server/fishtest/templates/tests_view.mak
- server/fishtest/util.py
With the current code a purged task is deleted from the task list. This means that the numbering of tasks changes.
One consequence of this is that links to tasks in the event log may become invalid.
Another issue is that task_id's held by the worker become invalid. This is unlikely to cause problems but it is still not nice and could lead to bugs later.
In this PR we mark a purged task as bad. For safety we also make it non-active and set all its stats to zero.
> Do not delete a task after purging but mark it as bad.

- server/fishtest/templates/tests_run.mak
- server/fishtest/templates/tests_view.mak
Basically, the first one regarding the button is not catchable because it only "triggers" while submitting the test, and the other one was overlooked because of rebasing.
> Fix some missed W3C Validation errors.

- server/fishtest/templates/tests_view.mak
We set `scroll-behavior` to `auto` (instantaneous scrolling) and we only make the page visible when the scrolling is complete.
> Faster rendering and no more artifacts when processing ?show_task=xxx.

- server/fishtest/rundb.py
This directive is legal. It is currently not used but someone might use it in the future and then things would fail silently.
Also better error handling if we are not able to obtain the port number.
> (cleanup) Support the `listen host:port` directive in the ini file.

- server/fishtest/static/js/application.js
- server/fishtest/static/js/live_elo.js
The notify stuff is refactored but not tested. 
If the browser cannot use the notification api then a message is printed on the console.
> More refactoring of live_elo.js.

- server/fishtest/static/js/application.js
- server/fishtest/static/js/live_elo.js
It should also be robust now. All error paths were tested.
To simplify the logic we implement `raise_for_status()` as in the python requests package.
> Simplified main loop in live_elo.js.

- server/fishtest/static/js/application.js
- server/fishtest/templates/tests_view.mak
Also: delete v3 in the media type for a diff. It is no longer required. See:
https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28
> Refactor and flatten the function `handle_diff()` in tests_view.mak.

- server/fishtest/actiondb.py
- server/fishtest/templates/actions.mak
- server/fishtest/util.py
- server/utils/convert_actions.py
The run_id itself is not very suitable since it is not a hash but a combinations of a timestamp, a random number, computed once per process, and a counter initialized to a random value. It is not clear which part one should take.
The sha of the commit is also not suitable since there may be multiple runs with the same commit (e.g. different TC).
Before this works utils/convert_actions.py should be run.
> Append a hash of the run_id to the run name (=branch).

- server/fishtest/templates/actions.mak
- server/fishtest/views.py
The pagination was not tested since on my local fishtest I don't have events associated with runs spanning multiple pages.
> Adapt links on the events log to the run_id parameter.

- server/fishtest/__init__.py
- server/fishtest/api.py
- server/fishtest/static/html/finished_runs.html
A valid request consists of a POST request with a body that is a stringified version of the json query.
The response is limited to 200 events.
To test the api there is an example document
<server>/html/finished_runs.html
This will be removed later.
> Create an api for querying the event log.

- server/fishtest/static/js/notifications.js
- server/fishtest/templates/base.mak
- server/fishtest/templates/run_tables.mak
The PR has two independent commits
- Display the bootstrap notifications in all fishtest browser windows (currently a bootstrap notification is displayed only once, like a system notifications).
- Display the number of received (and non closed) notifications in the title of the tab.
> Some enhancements

- server/fishtest/rundb.py
The number of games reported in the `finished_run` message was half the real amount.
> Partially fixes #1547

- server/fishtest/rundb.py
A race condition between request_task and update_task may cause a test to be stopped multiple times.
> Should fix the other issue mentioned in #1547

- server/fishtest/rundb.py
Adjust the TC power law exponent to make base LTC TP of 4x STC TP, with the goal of reducing LTC latency to only 1.5x STC latency.
With the recent of busyness of fishtest (a good thing IMO), the current LTC latency of sqrt(6) ~ 2.5x is making for painfully long feedback time, potentially causing authors to submit more later-unnecessary STC tests rather than wait for LTC results. The latency is actually more than 2.5x on average since LTC elo bounds are higher as well, requiring more games at the same elo performance (on average).
This adjustment reduces LTC base latency from 2.5x to 1.5x, which should hopefully reduce the number of red-herring STC submissions as the test result feedback loop tightens up.
Edit: And, quite aside from red-herring STCs and test result feedback loops, the …
> Reduce latency of LTC relative to STC

- server/fishtest/rundb.py
- server/fishtest/templates/run_table.mak
- server/tests/test_api.py
- server/tests/test_rundb.py
- server/utils/upgrade.py
1) remove itp from run table
2) add worker count to run table like so: `cores: 150 (2)` (open to feedback)
3) adjust the itp LLR bonus to a tighter window, with asymmetric bonus (reward good LLR more than punish bad) (see commit message)
> Final itp adjustments

- server/fishtest/rundb.py
Several workers in the last month between 30 and 32 threads have fallen afoul of the well-established cutechess bugs in many-threaded contexts. Altho most such workers run fine, we currently have no server-side filtering of garbage results, nor any worker-side workaround, so this is the best we've got. Update it now to reduce future garbage with the least current effort.
As stated, most workers in the 29-32 thread run fine, but those that don't are a significant problem. To the best of my knowledge, all workers at 28 or less have run fine so far. It's certainly easy to adjust this again in the future.
> Reduce "LTC only" thread threshold

- server/fishtest/rundb.py
- server/fishtest/util.py
The former saves a bit of LOC, the latter should improve server performance.
Note that the tc_too_short comparison is now `<` rather than `<=`
> Use get_tc_ratio more, add cache to estimate_game_duration

- server/fishtest/rundb.py
I've concluded that the negative malus merely inflates the active test count rather than meaningfully spreading the love.
The positive bonus suffices to speed up passers, while clearing out the losers keeps the total test count lower, making the queue cleaner and easier to read.
> itp: remove malus for bad LLR

- server/utils/create_indexes.py
Sorting by last_updated is unnecessary since the unfinished runs are already sorted in code.
This presumably solves #134.
With the main page being served from a separate pserve, the current lock solution no longer works.
See the following helpful description of the issue
https://blog.meteor.com/mongodb-queries-dont-always-return-all-matching-documents-654b6594a827
> Do not sort the unfinished_runs index by last_updated.

- server/fishtest/views.py
an earlier commit made the batch size for SPRT test 32. This is a good number of single-threaded STC tests, but not for multi-threaded LTC tests. Tests running 60+0.6@8t take too long on an 8core worker to update results. The following patch adjust the number of games, keeping it the same for single threaded STC, but scaling down with TC and threading.
> Adjust batch size for SPRT tests.

- server/fishtest/templates/base.mak
The free mongodb monitoring was deprecated in April 2023 and will be decommissioned in August 2023.
Update the code to read the new format of `db.getFreeMonitoringStatus()`
Add some debug code in case the format will change in the future.
> Fix mongodb monitoring url

- server/fishtest/rundb.py
Since Only 'runs' are taken from
```
request.rundb.aggregate_unfinished_runs(
username=username,
)[0]
```
with index 0, it makes no sense to calculate workers related stuff for this page since they are not shown in the first place.
> Avoid Useless calculations for /tests_user pages

- server/fishtest/templates/tests_view.mak
The code was very CPU-intensive for runs with long task lists:
- checking that a dictionary is contained in a list of dictionaries is expensive
- the code performed O(n^2) checks with n the length of the list
Improvements:
- check very rare events first (bad task)
- check if the task is contained in the first list by comparing idx and
the length of the first list
- some code refactoring
> Speedup in tests_view for long list of tasks

- server/fishtest/rundb.py
Active tasks are near the end of the task list so this should give a small speed up.
> Go through task lists in reverse order to find active runs.

- server/fishtest/rundb.py
- server/tests/test_api.py
they make some operations in fishtest much slower, and the db bigger. Additionally larger batches means less idle time at the end of the batch for workers, which is good.
> Avoid long task lists

- server/fishtest/rundb.py
High game counts add load to the server because of the number of loops through run["tasks"]. Increase itp in longer running sprts to finish them off quicker.
> Increase itp if game count > 200k.

- server/fishtest/static/js/application.js
- server/fishtest/static/js/notifications.js
I noticed that after sleep all tabs wake up which occasionally may lead to multiple fetches and possibly duplicate notifications, if many tabs are open.
We use a standard trick to defend against this.
> Extra defense against race after wake up from sleep.

- server/fishtest/rundb.py
once a run is finished we expect workers to update_task, where they will be signalled that they can quit working on this task.
fixes https://github.com/glinscott/fishtest/issues/1668
> Avoid logging a frequent, expected event

- server/fishtest/static/js/notifications.js
We deal with some issues observed on Chrome/Linux.
- Tabs that are not active are severely throttled. A 20 second (asynchronous) sleep can last much longer. Thus the console becomes flooded with "Wake up from sleep" messages. This should be fixed in this PR.
- The milliseconds part of the time (obtained by `Date.now()`) is quantized. So it cannot be used as a simple source of randomness (see the code how it is used).
> Add a bit of randomness to current_time.

- server/fishtest/api.py
Fixes #1672
I would like further to remove the addition below as the existence of such a key with empty data is very improbable that is used by people who use this API, please let me know what you think.
```
run["tasks"] = []
run["bad_tasks"] = []
if "args" in run and "spsa" in run["args"]:
if "param_history" not in run["args"]["spsa"]:
run["args"]["spsa"]["param_history"] = []
```
> Fix api_active_runs

- server/fishtest/static/js/application.js
- server/fishtest/static/js/notifications.js
I occasionally still observe duplicate notifications on ipad after wake up. I think the reason is that one tab may sleep before a fetch and another thread may sleep during the "async_sleep(1500)". This presents a race.
We catch this by checking the actual time slept. If it is > 90s then we cancel the fetch.
One would like to reduce the 90s but this would be defeated by the fact that timers on Chrome fire only once per minute in inactive tabs.
There is also some nice refactoring. The function async_sleep can now be used as
```
let t = await async_sleep(delay_ms);
```
where t is the amount of time (in ms) that is actually slept.
> More robust wake up from sleep.

- .github/workflows/lint.yaml
The workflow never fails but it writes the linters and formatters outputs and the final results, eg:
```
./worker/worker.py:1570:89: E501 line too long (90 > 88 characters)
❌ flake8 failed
creating virtual environment...
installing black...
would reformat /home/runner/work/fishtest/fishtest/server/fishtest/api.py
would reformat /home/runner/work/fishtest/fishtest/server/fishtest/views.py
Oh no! 💥 💔 💥
2 files would be reformatted, 33 files would be left unchanged.
❌ black failed
creating virtual environment...
installing isort...
ERROR: /home/runner/work/fishtest/fishtest/server/fishtest/views.py Imports are incorrectly sorted and/or formatted.
Skipped 1 files
❌ isort failed
Checking formatting...
All matched files use Prettier code style!
✔️ prettier succeded
```
> Add linters and formatters to CI

- server/fishtest/rundb.py
Looping through all the tasks in get_results() gets very expensive when called from update_task() with a large fleet of workers on fishtest.
This patch removes the get_results() call from update_task() and only uses the info in the updated task to increment the run results.
> Update results stats incrementally

- server/fishtest/templates/tests_view.mak
- server/fishtest/views.py
- the string is already html escaped in "view.py", simplify the escaping in mako template
- python3 string supports unicode, drop unnecessary try except
> Simplify html escaping in mako

- server/fishtest/templates/elo_results.mak
- server/fishtest/util.py
- server/fishtest/views.py
Also use consistent spacing around ±.
When loading finished runs, we now always re-format the results because the stored results might still contain +-.
> Replace +- by ± in Elo output

- server/utils/delta_update_users.py
The previous version of the script had two major issues:
1. it loaded only one run ID from the deltas collection without any sorting
criterion. Since there is no guarantee that the returned natural order
is the insertion order, this could result in a very inaccurate contribution
calculation in the first update scan after a full scan, when the deltas
collection contains all the finished run IDs.
2. the run, with the ID loaded from the deltas collection, could switch
to active status (e.g., after a purge).
This resulted in failing to stop the processing and double counting
of already processed finished runs from the last 30 days.
Changes:
- load and save the IDs of all the processed finished runs in
deltas collection, python checks if a key is in a dict in O(1)
- in update scan mode, for …
> Rewrite "delta_update_users.py"

- server/fishtest/templates/users.mak
- server/utils/delta_update_users.py
In the codebase, the key "last_updated" is consistently used as
a datetime object. However, in "delta_update_users.py",
it was used as a string representation.
This change standardizes the usage of "last_updated" by ensuring that
it is always used as a datetime object. As a result, it is necessary
to run "delta_update_users.py" in full scan mode to rebuild the
"users_cache" and "top_month" collections with the new key names.
> Standardize usage of "last_updated" name

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Fishtest with Stockfish 11 had 1.6MNps as reference Nps and 0.7MNps as
threshold for the slow worker.
Set the new threshold for slow worker according to the 38% slowdown
of the SF dev-20230531-d99942f2 wrt SF 11 on the arch=modern.
The new reference Nps will be set (using the recent arch=bmi2) with
the next SF release to avoid a jump in the progression tests.
compiler clang 16.0.5
- arch=bmi2 (Dual Xeon workstation)
```
sf_base =  1591512 +/-   5997 (95%)
sf_test =  1125091 +/-   5203 (95%)
diff    =  -466420 +/-   7277 (95%)
speedup = -29.307% +/- 0.457% (95%)
```
- arch=modern (core i7 3770k)
```
sf_base =  1873067 +/-  18016 (95%)
sf_test =  1161362 +/-   8271 (95%)
diff    =  -711704 +/-  12171 (95%)
speedup = -37.997% +/- 0.650% (95%)
```
> Set slow worker threshold

- server/fishtest/api.py
- server/fishtest/rundb.py
- worker/sri.txt
- worker/worker.py
In case the worker has little memory (noob's workers), it might be impossible to run any tasks at the full concurrency specified by the user.
In that case, reduce concurrency to be able to run at least STC tests.
> Reduce concurrency if needed

- server/utils/purge_pgn.py
- use mongodb queries to speedup the process (measured 9x)
- clean up and comment the code
- compact the "pgns" collection. After several weeks, the collection
grows and accumulates a significant amount of wasted empty space
> Speed up "purge_pgn.py"

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/utils/delta_update_users.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Fishtest with Stockfish 11 had 1.6MNps as reference Nps and 0.7MNps as threshold for the slow worker.
Set the new reference Nps according to the 26% slowdown of the SF 16 wrt SF 11 on the ARCH=x86-64-bmi2.
Set the new threshold for slow worker according to the 34% slowdown of the SF 16 wrt SF 11 on the ARCH=x86-64-modern (x86-64-sse41-popcnt).
compiler clang++ 16.0.6
- arch=bmi2 (Intel Xeon CPU E5-2680 v3)
```
sf_base =  1580934 +/-  12410 (95%)
sf_test =  1163656 +/-   7679 (95%)
diff    =  -417278 +/-  11547 (95%)
speedup = -26.394% +/- 0.730% (95%
```
- arch=modern (Intel core i7 3770k)
```
sf_base =  1865978 +/-  14061 (95%)
sf_test =  1228350 +/-  11701 (95%)
diff    =  -637627 +/-   5230 (95%)
speedup = -34.171% +/- 0.280% (95%)
```
Raise worker version to 206, also server side.
> Set the SF16 reference Nps using SF11 as base

- server/fishtest/static/css/application.css
- server/fishtest/static/js/spsa_new.js
- server/fishtest/templates/base.mak
- server/fishtest/templates/tests_run.mak
- server/fishtest/util.py
* Stockfish now officially prelease dev builds so redirect to the latest one instead of Dev builds for ARM builds.
* as Stockfish's maintainer discussed on Discord, change the default testing book to UHO_4060_v2.epd in preparation for the SF16 release.
* Remove deprecated fishcooking forum link
* Adds Stockfish Wiki and NNUE Trainer Wiki as Fishtest maintainer suggested.
> Prepare Fishtest for Stockfish 16 release.

- server/fishtest/templates/tests_run.mak
perform SMP PT at 60+0.6T. The reason is that we're doing quite a few tests at those settings today, so it might be nice to capture that.
> Adjust settings for the SMP PT

- server/fishtest/static/css/application.css
- server/fishtest/templates/tests_view.mak
mobile version looks unreadable now, do an auto fix.
> Fix overflow on both mobile and desktop

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/utils/delta_update_users.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Fishtest with Stockfish 11 had 1.6Mnps as reference nps and 0.7Mnps as threshold for the slow worker.
Set the new reference nps to 0.64Mnps according to the 60% slowdown of the SF 16 wrt SF 11 on the ARCH=x86-64-bmi2
Set the new threshold for slow worker to 0.231Mnps according to the 67% slowdown of the SF 16 wrt SF 11 on the ARCH=x86-64-sse41-popcnt
compiler clang++ 16.0.6
- arch=bmi2 (Intel Xeon CPU E5-2680 v3)
```
sf_base =  1515099 +/-   6276 (95%)
sf_test =   610755 +/-   2686 (95%)
diff    =  -904343 +/-   5940 (95%)
speedup = -59.689% +/- 0.392% (95%)
```
- arch=sse41-popcnt (Intel core i7 3770k)
```
sf_base =  1929595 +/-  19733 (95%)
sf_test =   654161 +/-   5421 (95%)
diff    = -1275433 +/-  14999 (95%)
speedup = -66.099% +/- 0.777% (95%)
```
Raise worker version to 207, also …
> Set the SF16 pure NNUE reference nps wrt SF11

- server/fishtest/views.py
This is no longer needed, as the itp will be updated in the next request task.
> Fix server error in modify.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
See 
https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=&before=1692105137.772177&run_id=
vs
https://tests.stockfishchess.org/actions?max_actions=1&action=&user=&text=&before=1692102104.224252&run_id=
> Fix string representation of signals for Python 3.11.

- server/fishtest/views.py
- server/tests/test_run.py
> Fix validating Master branch in the form.

- server/fishtest/__init__.py
- server/fishtest/api.py
This should make it possible for external use to calculate the ELo based on Either (Ptnml or WDL) and elo0, elo1 bounds (elo_model is optional and defaults to "normalized").
The format is:
https://tests.stockfishchess.org/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=-1.75&elo1=0.25
needs testing.
> Introduce Calculate Elo API for external use.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
as the user could change the compiler at worker startup time (e.g. clang vs gcc), the binary cache might contain binaries compiled with a different compiler than the ones generated by the worker. As different compilers lead to binaries of different speed, test results could be biased, unless we assure that the same compiler is used for both base and new test.
This patch just clears the binary cache once at worker startup, leaving the caching mechanism unchanged otherwise.
Possibly the binary cache should also be flushed on worker update (e.g. the architecture selection logic might change). This is not implemented.
fixes https://github.com/glinscott/fishtest/issues/1666
> Remove cached binaries on worker startup

- server/fishtest/rundb.py
- server/tests/test_api.py
During request_task, we check if there are active tasks for workers with the same name, which have recently been updated (i.e. they are not dead). If so then we return an error.
Should fix https://github.com/official-stockfish/fishtest/issues/1360#issuecomment-1689436054 .
> Try to avoid workers with the same name.

- server/fishtest/actiondb.py
- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/userdb.py
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_api.py
- server/tests/test_rundb.py
- server/tests/test_users.py
- server/utils/convert_actions.py
- server/utils/delta_update_users.py
- server/utils/purge_pgn.py
- server/utils/upgrade.py
- worker/games.py
- worker/sri.txt
- worker/updater.py
- worker/worker.py
The function is deprecated in python 3.12, see
https://docs.python.org/3.12/library/datetime.html?highlight=utcnow#datetime.datetime.now
"Because naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing the current time in UTC is by calling `datetime.now(timezone.utc)`."
> Replace deprecated `datetime.datetime.utcnow()`

- server/fishtest/api.py
- worker/sri.txt
- worker/updater.py
- worker/worker.py
The package `distutils` is deprecated since python 3.10 and it is scheduled to be removed with python 3.12, see: https://docs.python.org/3.12/whatsnew/3.12.html
https://github.com/python/cpython/issues/92584
`shutil.copytree()` is able to copy the source directory tree to an existing destination directory only from python 3.8 (parameter `dirs_exist_ok=True`), for python < 3.8 still use `distutils.dir_util.copy_tree()`
While here:
- create in a safe way the temporary directory used for the update
- deal with possible download problems
Raise worker version to 214 (also server side)
> Replace deprecated `distutils` package

- AUTHORS
- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
This PR uses the full commit sha of `Base` for the engine name sent to cutechess-cli.
This would make it easier for scripts to identify the SF version that played games on fishtest.
Possible applications would be the tracking of the normalizing constant in SF's WDL_model, in the spirit of @vondele 's matetrack.
I do not know if the longer names could break things for other third party tools that make use of fishtest pgn's, so feedback would be appreciated.
> send full commit SHAs to cutechess-cli

- server/fishtest/templates/tests.mak
production shows  `Workers - undefined machines` instead of an actual count.
> Fix wrong DOM selector

- server/fishtest/static/js/spsa_new.js
- server/fishtest/templates/tests_run.mak
- server/fishtest/util.py
this book adds back the move counters to UHO_4060_v2, restored from UHO_4060_v1, but is otherwise identical.
> Update book to UHO_4060_v3

- server/fishtest/templates/workers.mak
- server/fishtest/views.py
This is per the spec. It makes gmail on ipad work (before, all linefeeds were suppressed).
> Encode \n as crlf in email body.

- server/fishtest/userdb.py
- server/fishtest/util.py
- server/tests/test_validate.py
- Use f-strings in `validate()`.
- Fix bug which prevented strict validation with optional keys.
- Tighten up the user schema and use strict validation (strict validation means that one cannot introduce keys which are not in the schema).
- Add some unittests for the validation code. There is in particular a test that shows how to create a type `lower_case_string`.
> Various validation fixes.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
See the comments for #1815 .
This PR seems to work fine when the only messages are on stdout. Not tested yet when there are actually error messages. 
One way to do it is to create a test with an option unknown to SF.
> Merge cutechess-cli stdout and stderr inside the worker instead of relying on Python to do it

- server/fishtest/templates/workers.mak
If the admin panel is shown and the worker in the admin panel has never been updated then all the last_updated fields in the list of blocked workers are shown as "Never".
> Bugfix in worker management.

- server/fishtest/__init__.py
- server/fishtest/api.py
- server/fishtest/rundb.py
- server/tests/test_api.py
- worker/sri.txt
- worker/worker.py
The previous worker code posted the PGN to the server in a zlib-compressed format. This required the server to decompress the data before serving the PGN as text, resulting in significant CPU and network overhead. Furthermore, a bulk download of all PGNs from a run necessitated additional CPU overhead for compression.
The updated worker code posts a gzip file containing the PGN text to the server, leading to more efficient handling on the server side:
- for single PGN downloads, the server simply serves the gzipped PGN retrieved from MongoDB. All modern browsers decompress the gzip file client side, so the user will get the pgn as text file. nginx can be configured to decompress on the fly the gzip content for a client that is not declaring his compression capability.
- for bulk PGN …
> Implement efficient PGN upload and bulk download - gzip and tar

- server/fishtest/api.py
- server/tests/test_api.py
Currently workers can add arbitrary fields to the api payloads, some of which may find their way into the db. This PR makes this impossible.
Note: strict parsing is possible thanks to the fix of a validation bug in #1811.
> Switch to strict parsing of worker api's.

- server/fishtest/templates/tests_run.mak
The tests are hidden, just like the PT tests, but at least this allows for some s13n
key parameters
```
"name": "VLTC",
"tc": "180+1.8",
"throughput": "50",
"threads": 1,
"options": "Hash=192",
"bounds": "standard STC",
"name": "VLTC SMP",
"tc": "60+0.6",
"throughput": "50",
"threads": 8,
"options": "Hash=512",
"bounds": "standard LTC",
```
_(not tested)_
> VLTC test presets

- server/fishtest/templates/tests_run.mak
A new book with better properties for testing as described in
https://github.com/official-stockfish/books/commit/426eca422c202ef381a1380ada1873a7f185c4b9
favorable draw rate of about 50%
https://tests.stockfishchess.org/tests/view/6533f394de6d262d08d3a55e
Similar to our current book (which is in fact pretty good) in Elo detection: https://tests.stockfishchess.org/tests/view/6534127dde6d262d08d3a76a https://tests.stockfishchess.org/tests/view/65341296de6d262d08d3a76f
This should (if done correctly) no affect the book for progression testing, this we can leave at the old version, to ensure continuity.
> New default book for tests

- server/fishtest/rundb.py
- server/fishtest/views.py
- server/tests/test_api.py
- Remove the field `"results_stale"` since now the results are updated incrementally. So they should never be stale.
- Retire `get_results()` and replace it by `compute_results()` which has no side effects (`get_results()` was terrible from this point of view). `compute_results()` is called in two places: 
- in `purge_run()` 
- after a run is finished to verify the incrementally updated results.
- Set the `"workers"` and `"cores"` fields equal to zero when the run is finished.
> Small cleanups in the run db.

- server/fishtest/api.py
- server/tests/test_api.py
- server/tests/test_rundb.py
The api's in api.py are a direct connection between the workers and the db. So it makes sense to be very strict in what we accept.
Note: a serious bug was discovered in the handling of optional keys in vtjson. So vtjson should be upgraded to the latest version. Since upgrading is necessary anyway, this PR depends on a previously internal feature of vtjson, namely the possibility to pre-compile a schema.
Validating an update_task api call for an SPRT run takes 0.026ms on an AWS entry level t2.micro using Python 3.11 (without pre-compiling it takes 0.068ms).
> Tighten up the schema in api.py.

- server/fishtest/views.py
This should fix https://github.com/official-stockfish/fishtest/pull/1843#issuecomment-1837540039
> Remove some dead code in tests_modify (views.py).

- server/fishtest/static/js/application.js
Logs users out from other tabs if they try to use them while they have logged-out or lost cookies. Worth noting that the page was already unusable and the user couldn't do actions due to an expired CSRF token.
steps in the issue cannot reproduce the error. I can only see this scenario causing it. Fixes: https://github.com/official-stockfish/fishtest/issues/1839
Needs Dev testing.
> Log out from other tabs.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
To test this PR (on Linux, see below) one may run the worker in one terminal and during compiling send a SIGINT or SIGTERM to the python process from another terminal (e.g. via kill <PID-python>). A worker running master will only stop when the make command finishes. If the worker runs this PR then it will stop immediately and clean up.
This PR currently has no effect on Windows as the mechanism for terminating processes is different. Probably there is also no need for this PR on that OS.
This PR is less general than #1864 but also much more trivial.
> Shut down the worker quickly after receiving SIGINT.

- server/fishtest/templates/tasks.mak
Currently, there is no convenient way to get to the particular worker page to block/unblock after misbehaving workers are spotted in test_view Tasks. You would need to write the URL manually or search for that worker on the home page.
Make the approver-only anchor redirect to the worker management rather than the user page as the user page is irrelevant after we can block only the worker.
> Convenient link to blocked workers

- server/tests/test_run.py
Updated the bench regex pattern to match the correct format of the bench number.
Thanks to @Disservin for reporting the bug.
> Improve bench regex pattern

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Stockfish will use more than one net with
https://github.com/official-stockfish/Stockfish/pull/4915
Get all the couples "option" and "net names" from the output of the
`stockfish uci` command.
Raise worker version to 227 (also server side)
> Generalize the EvalFile net option detection

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
This failure may be intermittent and it currently stops the worker.
> Make "This machine is too slow ..." non-fatal.

- server/fishtest/api.py
- worker/sri.txt
- worker/worker.py
It seems more useful that way...
> Remove the fish.exit file after the worker has stopped.

- server/fishtest/rundb.py
- server/fishtest/views.py
there is no reason to hide them on the first place, and practice shows it's not the ideal thing let alone the net is still available so this is a fake frontend guard.
A follow up fix should be, website server changes after dual net, since the master net is not marked as tested for now.
> Don't hide "non-tested" nets for logged out users

- server/fishtest/actiondb.py
- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/templates/actions.mak
- server/fishtest/userdb.py
This may be used to give internal errors in the logic of Fishtest maximum visibility.
This action is currently used in two places:
- if a finished run does not validate;
- if check_results finds a discrepancy between the incrementally updated results and the computed results in a finished run.
Currently both errors are logged but otherwise they are treated silently.
Another application in the future might be to log certain worker errors which happen before a task is requested (e.g. failure to be able to run cutechess-cli).
While at it, replace all occurences of _validate(), which returns an error string on non-validation, by the more Pythonic validate(), which throws an exception instead.
> Introduce log_message action.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
This strategy ensures that the Events Log receives detailed information,
which assists in identifying the root cause of the issue.
Possible causes could range from an erroneous bench entry on the Fishtest
new run page, a malfunctioning engine, to a worker misconfiguration,
among others.
A WorkerException is still raised immediately.
closes https://github.com/official-stockfish/fishtest/issues/1897
Thanks to @peregrineshahin and @Disservin for bringing this issue to light.
Raise worker version to 231 (also server side)
> Benches both engines prior to raise a RunException

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
This reverts commit 54048a24bfed7795a29bfc06db2992f2e30895cf.
See https://tests.stockfishchess.org/actions?action=failed_task&user=Wencey&text=%22too+slow%22
EDIT: The above query currently (March 26, 2024) generates 149 pages!
> Revert "Make "This machines is too slow ..." non-fatal."

- server/fishtest/rundb.py
Python 3.12 introduced a bug during the interpreter shutdown, see:
- issue https://github.com/python/cpython/pull/104826
- bugfix https://github.com/python/cpython/pull/117029
With Python 3.12.3, this change could potentially be reverted (after testing).
> Mitigate Python 3.12 Shutdown RuntimeError

- server/fishtest/rundb.py
- server/fishtest/schemas.py
Currently version 0!
This is a quick go at versioning the run object to suppress spurious event log messages about validation errors for runs that were created before the schema changed.
Not yet tested but the code is fairly trivial.
This is in connection with the discussion at #1927
> Versioning the run object.

- server/fishtest/actiondb.py
- server/fishtest/schemas.py
The new schema is functionally equivalent to the old schema but the non-validation messages are much better.
Validating
```python
{"action": "failed_task", "message": "It's going well!"}
```
against the old schema may yield (it is not deterministic)
```
action['worker'] is missing and action['worker'] is missing and action['worker'] is missing and action['action']
(value:'failed_task') is not equal to 'system_event' and action['action'] (value:'failed_task') is not equal to 'new_run' and action['action'] (value:'failed_task') is not equal to 'upload_nn' and action['action'] (value:'failed_task') is not equal to 'modify_run' and action['action'] (value:'failed_task') is not equal to 'delete_run' and action['action']
(value:'failed_task') is not equal to 'stop_run' and action['action'] …
```
> Improve the action schema.

- server/fishtest/static/js/application.js
- server/fishtest/templates/tests_view.mak
API limit rate shows `no diff available` then saves that in session storage, this is not intended. this prevents such text to be saved in session storage. TBH 60 requests / hour is not what I expected from GitHub, although rewriting the diff code to the server-side might help a bit it's not the best idea because the server does a lot of requests to GitHub anyways. limit rate could be easily solved once GitHub Auth is introduced (soonTM?).
> Fix a bug in diffs

- server/fishtest/rundb.py
Reverts official-stockfish/fishtest#1925
PROD updated to python 3.12.3 that has the bugfix https://github.com/python/cpython/pull/117029
```python
import threading, time
def main():
threading.Thread(target=bloop).start()
def bloop():
time.sleep(0.5)
threading.Thread(target=print, args=("new thread running",)).start()
main()
```
- python 3.12.3:
```
$ python3 test_interpreter_shutdown.py
new thread running
```
- python 3.12.2:
```
$ python3 test_interpreter_shutdown.py
Exception in thread Thread-1 (bloop):
Traceback (most recent call last):
File "/home/fishtest/.pyenv/versions/3.12.2/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
self.run()
File "/home/fishtest/.pyenv/versions/3.12.2/lib/python3.12/threading.py", line 1010, in run
self._target(*self._args, **self._kwargs) …
```
> Revert "Mitigate Python 3.12 Shutdown RuntimeError"

- server/fishtest/schemas.py
- server/fishtest/views.py
Note that there is some discussion in #1942 about which regex to use for usernames. In this PR, for backward compatibility, I am using a weak regex that matches all current usernames. If a consensus is reached in #1942 then in a future PR the username pattern should be updated accordingly.
> Tighten the runs schema by exhibiting dependencies between flags.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_nn.py
- server/utils/delta_update_users.py
- server/utils/purge_pgn.py
https://pymongo.readthedocs.io/en/stable/examples/datetimes.html#reading-time
"By default all `datetime.datetime` objects returned by PyMongo will be naive but reflect UTC (i.e. the time as stored in MongoDB). By setting the `tz_aware` option on `CodecOptions`, `datetime.datetime` objects will be timezone-aware and have a `tzinfo` property that reflects the UTC timezone."
> Make PyMongo timezone-aware

- server/fishtest/schemas.py
Requires upgrading the vtjson package.
> Enforce tzinfo=timezone.utc in the schemas.

- .github/workflows/worker_posix.yaml
This is the latest runner version supporting python 3.6
> Use macos13 runner in CI

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/util.py
This commit adds a feature that streams PGNs of a run, significantly reducing
the server's CPU/RAM usage. The API now returns a gzipped PGN, constructed by
chaining all the run's gzipped PGNs, which is streamed to the client.
Key changes:
1. update 'api_download_run_pgns' in api.py, which handles the request for
downloading the PGN of the run. It fetches the PGNs using the
'get_run_pgns' method from the RunDb class, and returns a gzipped response
```
wget https://test.stockfishchess.org/api/run_pgns/<run_id>.pgn.gz
```
2. add 'GeneratorAsFileReader' class in util.py that provides a file-like
interface for a generator, enabling chanked reading
3. modify the 'get_run_pgns' method in rundb.py to return a
'GeneratorAsFileReader' object that yields each gzipped PGN file for the run
Note: the …
> Implement bulk streaming of tasks PGNs for a run

- server/utils/purge_pgn.py
In this way we are sure to purge the PGNs even in case of wrong tasks information.
This is the query used in rundb.py
> Use a regex in query to purge PGNs

- server/fishtest/views.py
after updating the number of games the iterations completion can be more than 100% 75k/60k this is because SPSA num of games should not be modifiable after creation
See Also: https://discord.com/channels/435943710472011776/900771437177094156/1234042155346169937
> Fix SPSA iteration mismatch

- server/fishtest/api.py
A client able to decompress on the fly the gzip content stops the download after extracting the first PGN (it expectes to download one file) ignoring the "Content-Length" header.
Drop the "Content-Encoding" header to complete the download of all the PGNs.
> Drop "Content-Encoding" header for run PGNs

- server/fishtest/api.py
- server/fishtest/schemas.py
Requires upgrading the` vtjson` package (which now has the `magic(mime_type)` validation method).
> Force mime type of pgn_zip to be application/gzip in schema.

- server/fishtest/static/js/calc.js
- server/fishtest/templates/tests_run.mak
- server/fishtest/templates/tests_view.mak
This removes the old system-dependent `alert()` usage
> use the custom `alertError` for errors we want to show to the user

- server/fishtest/templates/tests_view.mak
- server/fishtest/templates/user.mak
This allows for users to use their own limited GitHub tokens to avoid exceeding the GitHub rate limit when viewing github diffs (mainly useful to approvers), which is set at 60 requests per hour for unauthenticated users. By using this token, you can surpass the standard rate limit, extending it beyond the 5000 requests per hour limit. You can find more information about GitHub's rate limits here.
It's important to note that this token will not be stored in a database but rather in your local storage. This ensures security and reduces the risk of unauthorized access.
The token should only be granted read-only permissions and limited access. This ensures that it can only be used for viewing content and not for making any modifications or accessing sensitive information.
Instructions:
1- …
> Avoid timeouts for GitHub diffs

- server/fishtest/views.py
I think that this line is actually a noop since it is only invoked if the last_updated field is not present, which cannot happen.
Not tested...
> Do not touch task["last_updated"] in tests_view.

- server/fishtest/rundb.py
This is to debug sequences of rejections such as this one (see #1976)
Apr 24 22:26:50 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
Apr 24 22:28:46 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 50 seconds ago
Apr 24 22:29:42 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 106 seconds ago
Apr 24 22:32:21 tests.stockfishchess.org pserve[24847]: Request_task: There is already a worker running with name "ChessDBCN-11cores-ccd4f156" which sent an update 70 seconds ago
I conjecture …
> Log long worker names when rejecting a duplicate worker name.

- server/fishtest/rundb.py
- server/tests/test_api.py
It may happen that a worker fails to update a task because of server issues. It will retry 5 times and then ask for a new task. But the server will not have marked the original task as inactive. So before this PR the worker will be flagged as a duplicate of itself and will be denied a new task for some time.
In this PR we simply mark the original task as inactive and continue.
> Do not flag a worker as a duplicate of itself.

- server/fishtest/static/js/live_elo.js
This avoids fetching each 20s tabs that are not focused/visible by the user, by making one tab update at a time for multiple Live Elo tabs. on the other hand updates immediately the new tab if it becomes the one in focus. Allowing for less load from the API with a lazy load approach.
> Smarten Live Elo

- server/fishtest/templates/tests_run.mak
This is a suggestion by @Vizvezdenec .. sometimes the user forgets that they need to pick the right TC before editing base branch and base signature, which if they did and then pick the wanted TC then the values they wrote/copied from another place will be overwritten, this solves this by marking `LTC, STC SMP, LTC SMP, VLTC, VLTC SMP` as `don't care`.
> Enhance UX for creating tests.

- server/fishtest/api.py
- server/fishtest/rundb.py
This should make it possible to serve `/api/upload_pgn` from a non-primary instance. See https://github.com/official-stockfish/fishtest/pull/1983#issuecomment-2094916162
> Make validate_request work on non-primary instances.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/templates/tests_run.mak
Simplify the coding of the APIs moving the logic of primary/secondary
instance in the RunDB class.
Drop old debug code.
> Extend `get_run()` to support secondary instances

- server/fishtest/schemas.py
This seems to be equivalent to the regex in master but in principle it does not have to be.
> Validate run_id with ObjectId.is_valid in api_schema.

- server/development.ini
- server/fishtest/__init__.py
- server/fishtest/rundb.py
- server/production.ini
This gets rid of some ugly code in rundb.py.
> Get port and primary_port from the config files development.ini and production.ini (RFC)

- server/fishtest/rundb.py
- server/production.ini
- server/setup.py
Tested working fine with a fleet of 75k cores 10k machines,
Waitress configured with threads=4 and connection_limit=100
HW usage: RAM 72%, primary Waitress instance CPU 85-95%
This is a good compromise for threads "privileged" for "request_task" API, and threads free for any other APIs, while keeping Waitress threads=4.
Raising the number of Waitress threads uses more RAM and can requires lowering the MongoDB cache size to avoid the OOM killer.
see #2003
> Set semaphore to 2 for "request_task" API

- server/fishtest/rundb.py
So a non-primary instance will never accidentally write to the rundb.
> Make buffer() a noop on a non-primary instance.

- server/fishtest/__init__.py
- server/fishtest/rundb.py
- server/fishtest/views.py
We have everywhere replaced
```python
task["active"] = False
```
by
```python
set_inactive(task_id, run)
```
which does the required bookkeeping under the `task_lock`.
The intention is that the `task_lock` will only be held for a very short time. So in `request_task` we only grab it at the moment when we actually add a task to the run (currently it is held during the whole invocation of `request_task`).
If it works then this PR can serve as a model for other types of bookkeeping like the number of committed games.
Other change:
We start the cache timer in `__init__.py` at application start up instead of during the first invocation of `buffer()`.
> Fully dynamic updates of run["cores"] and run["workers"] (RFC)

- server/fishtest/rundb.py
We changed the active_run_locks to be reentrant.
> Use active_run_lock(run) to protect updates of aggregated data.

- server/utils/purge_pgns.py
The new name reflects that we are purging the "pgns" collection. The scheduled task must be updated with the new name.
> Set days_ltc in clear way and rename script

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
this changes slightly how the heartbeat works:
Instead of sending it every 120s regularly, only send it if the last update to the server is 120s ago.
For example, in a case like this:
```
2024-05-19 11:44:59.219186+00:00 : run: 664937bcb8fa20e74c39f42e task: 126 size: 416 tc: 10+0.1 concurrency: 7 threads: 1 [ sprt : 800000 ]
2024-05-19 11:46:58.900077+00:00 :   1.02 ms (s)   152.93 ms (w)  https://tests.stockfishchess.org:443/api/beat
2024-05-19 11:48:55.849837+00:00 :   2.16 ms (s)   144.34 ms (w)  https://tests.stockfishchess.org:443/api/update_task
2024-05-19 11:48:59.073522+00:00 :   1.55 ms (s)   160.57 ms (w)  https://tests.stockfishchess.org:443/api/beat
2024-05-19 11:50:46.055023+00:00 :   2.91 ms (s)   172.30 ms (w)  https://tests.stockfishchess.org:443/api/update_task …
```
> Send heartbeat only when needed

- server/fishtest/templates/tests_view.mak
this gives a warning for mismatching options
a patch with hash=512 vs hash=64 has made its place in Stockfish master
the yellow highlight is for demonstration purposes (done with paint, I don't think we need any).
> Danger alert for mismatching options

- server/fishtest/api.py
- worker/sri.txt
- worker/worker.py
Same behaviour as before except that we now reject clang in case it is older than 8.0 (released 2019), 7.0 wasn't able to compile latest master for me.
> Refactor minimum requirement version for compiler and add logic to clang

- server/fishtest/rundb.py
- server/fishtest/schemas.py
A dead task (a task which has not been updated for 360s) will only be scavenged if it belongs to a run in the cache. However clean runs are evicted from the cache after 300s. So if the run does not get new tasks, for example because it has low priority, the dead tasks remain unscavenged until somebody explicitly looks at the run (this pulls the run back in the cache).
Obviously it is not nice that dead tasks are not scavenged as soon as possible. Moreover the fact that the behavior of the server is affected by executing a GET request is a violation of the HTTP specs.
> Do not evict a run from the cache which has active tasks.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/views.py
This eliminates a race condition between `stop_run()` and `request_task()`.
> Add `run["finished"]=True` to `set_inactive_run()`.

- server/fishtest/rundb.py
Old runs often do not validate due to the existence race conditions in the past.
> Only validate unfinished cache runs

- server/fishtest/rundb.py
With the present code a finished run with `run["cores"]>0` will never be evicted from the cache. This is not a legal condition but it happened in the past because of race conditions.
This explains why #2030 seemed to create more unvalidated runs. The illegal runs become more and more likely to be selected for validation as they are not evicted and eventually dominate the cache.
> Bug fix for #2030

- server/fishtest/rundb.py
This is a PR on top of #2047 
Split the convoluted `flush_buffers()` into three scheduled tasks
- `flush_buffers()`: syncs oldest cache entry (period: 1s)
- `clean_cache()`: evicts old cache entries (period: 60s)
- `scavenge_dead_tasks()`: (period: 60s).
This PR should also fix the deadlock #2041.
> Split `flush_buffers()`

- server/fishtest/rundb.py
- server/fishtest/schemas.py
Many data structure in Fishtest contain references to a run objects. Naively validating such data structures means that we are also validating the embedded run objects, which is wasteful as these are already validated elsewhere.
The latest version of vtjson makes it possible to change subschemas during validation.
In this PR we define the cache_schema as
```python
cache_schema = {
run_id: {
"run": set_label(runs_schema, "runs_schema"),
"is_changed": bool,
"last_sync_time": ufloat,
"last_access_time": ufloat,
},
}
```
and we perform validation via
```
validate(cache_schema, self.run_cache, name="run_cache", subs={"runs_schema": dict})
```
Requires upgrade of vtjson.
> Enhancement of validation.

- server/fishtest/rundb.py
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_api.py
Now it is computed (and cached) at the beginning of request_task. This could possibly lead to variation in the duration of request_task.
Also: general cleanup of request_task.
Also: we now maintain a set of unfinished runs so that it is no longer necessary to access the data base to get this list.
> Update task_runs list via a scheduled task with period 1 min.

- server/fishtest/rundb.py
- server/fishtest/views.py
`update_itp()` is a successor to code that also updated the list of unfinished runs but the latter is now managed dynamically.
Itp values move slowly on the Fishtest time scale and there is no need to micro-manage them.
> Retire `self.update_itp_task.schedule_now()`.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
Update comments about administrative flags.
Also: update schemas to more rigorously reflect this.
Validate whole run in "validate_random_run".
There are some race conditions in Fishtest so this will trigger some (event) log messages. This will help us fix the race conditions.
> Update comments; validate whole runs.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
In this way we guarantee that the schemas in schemas.py are kept up-to-date and hence preserve their documentary value.
Also: switch to string keys for the worker_runs dict. This is what we do elsewhere and it makes the schema more readable:
```python
worker_runs_schema = {
uuid: {
run_id: True,
"last_run": run_id,
}
}
```
Also: retire the separate variable "purge_count" and include it in the "active_run" dict.
Requires upgrade of vtjson for the set datatype used in "unfinished_runs_schema".
> Periodically validate Fishtest's internal data structures.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/fishtest/util.py
Previously the flags `is_green` and `is_yellow` were derived from formatting information in the result of `format_results(run)`. Obviously this is not nice.
> Introduce compute_flags() and validate them.

- server/fishtest/rundb.py
The convention throughout the code base is that `run_id` is a string.
Since a `run_id` and the corresponding ObjectId print in exactly the same way, violating this convention may lead to hard to understand bugs such as this one
https://tests.stockfishchess.org/actions?action=log_message&user=&text=internal
which was introduced in #1993.
> Make new_run return a string instead of an ObjectId.

- server/fishtest/views.py
e.g. https://tests.stockfishchess.org/tests/live_elo/66833b9895b0d1e881e81489 https://tests.stockfishchess.org/tests/live_elo/6683a096c4f539faa03268e5
> return 404 if a non-sprt run_id is abused to be used in a live_elo link

- server/fishtest/schemas.py
This may yield clearer non-validation messages.
> Explicitly declare some schema fields as posix timestamps.

- server/fishtest/__init__.py
From the "better to be safe than sorry" department.
> Fully initialize the rundb object before starting tasks.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
introduce a global_cache to reduce downloads from github and the net server if multiple workers having a shared filesystem are run by one user. This should allow a fleet to run without overloading github.
If the user specifies the path that corresponds to the global cache, the network and the source zipball are cached.  They are used if available, and only downloaded (and stored) if not.
Storing the data in the cache has been done in such a way that it becomes available atomically on most file systems.
> Introduce a worker global cache

- server/fishtest/util.py
- server/fishtest/views.py
the addition of "LTC:" has been overwritten by the green highlighting feature which leaves one source of truth to edit it if needed.
currently this looks old way to catch LTCs, here is a conflict of green highlighting and the added text https://tests.stockfishchess.org/tests/view/65f0ca4f0ec64f0526c46a67
> consistent "LTC:" addition

- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/fishtest/templates/elo_results.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_api.py
Rendered data does not belong in the db.
> Do not put results_info in the db.

- server/fishtest/api.py
- worker/sri.txt
- worker/worker.py
Releases the worker lock before restarting for an update. Fixes #2130
> Fix worker updates

- .github/workflows/worker_msys2.yaml
- .github/workflows/worker_posix.yaml
- AUTHORS
- server/fishtest/api.py
- server/fishtest/rundb.py
- worker/games.py
- worker/sri.txt
- worker/tests/test_worker.py
- worker/worker.py
fixes https://github.com/official-stockfish/fishtest/issues/2106
This PR switches from cutechess-cli to fast-chess.
cutechess-cli has been serving us well in the past years, however, some issues have accumulated, namely the difficulty of compiling cutechess-cli, the observed timeouts at high concurrency and short TC, and e.g. slowness when indexing larger books.  fast-chess https://github.com/Disservin/fast-chess has addressed these issues, and has now probably become mature enough to serve as the game manager for fishtest.
As an example of its ability to deal with short TC and high concurrency:
https://github.com/official-stockfish/fishtest/pull/2119#issuecomment-2571563064
with concurrency 48, and TC 1+0.01s, no timeouts are observed.
fast-chess is built from sources, with the zip …
> Switch from cutechess-cli to fastchess

- server/fishtest/stats/LLRcalc.py
https://github.com/official-stockfish/fishtest/issues/1889
vdbergh
https://github.com/vdbergh) commented [on Jul 23]
https://github.com/official-stockfish/fishtest/issues/1889#issuecomment-2243722730
I finally found time to set up a new website.
> Broken Links fixed in LLRcalc.py

- server/fishtest/schemas.py
See
https://tests.stockfishchess.org/actions?max_actions=1&action=log_message&user=&text=&before=1725836603.523324&run_id=
Probably, in a future PR, we will delegate the purging of the "active_runs" data structure to a scheduled task so that there is no more need for the "purge_count" field.
> Fix benign schema error.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
The update period is 1 minute.
This means that when we build the main page we do not need to pull the tasks from the db, likely resulting in a speedup.
> Update the nps and games_per_minute of a run in a scheduled task.

- server/fishtest/static/js/notifications.js
Increasing the maximum number of tests users can follow from 15 to 20.
So users can keep track of more tests simultaneously, allowing for a more comprehensive overview of ongoing tests.
Also, the previous limit of 15 was arbitrary, and increasing the limit poses no risks. This adjustment aligns with user needs for better monitoring and management of tests.
P.s: The new limit of 20 is also an arbitrary number, but it is better than before, and from my point of view is enough to satisfy users activity. But the limit can be increased further if needed.
> Increasing the maximum number of tests users can follow from 15 to 20

- server/fishtest/rundb.py
- server/fishtest/schemas.py
See
https://tests.stockfishchess.org/api/get_run/677a6ec46b38f4f9629fe598
This run is finished and yet it has nonzero nps and games_per_minute. This is possible if the scheduled task runs at the same time as the finishing of the run. In this PR we fix this and we enforce nps=0.0 and games_per_minute=0.0 in the schema.
> Fix race condition.

- server/fishtest/api.py
- server/tests/test_api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Instead of always waiting for the next update_task, we allow the heart beat api to stop handling a task in the worker.
> Faster worker stop on terminated task.

- AUTHORS
- README.md
Update after the switch from cutechess to fastchess.
Authors data from `git shortlog -s | cut -c8-`
Moved Gary Linscott in first position.
> Update README and AUTHORS

- server/fishtest/api.py
- worker/sri.txt
- worker/worker.py
We use the same mechanism which is used for compiling stockfish.
> Kill worker quickly with "killall python" while building fastchess.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
If we create a new task then we buffer the run with priority 1. In that way it will be the first in line for saving to the db.
There are several reasons for this PR.
- `upload_pgn` is served from a secondary instance. So we want to write the corresponding task to the db as quickly as possible, otherwise the api will fail.
-  If the tasks on the test page are served from a secondary instance then there may be entries in the event log that refer to tasks that have not yet been written to disk, probably baffling the users. So we want to make this interval as short as possible.
> Add priority field to cache.

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
In other words: do not wait for the whole task to finish.
> Make fish.exit quit the worker after the next update_task.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/fishtest/templates/tasks.mak
- server/fishtest/util.py
- server/fishtest/views.py
The main reason for this PR is that currently the residuals are updated in `tests_view`. This is *wrong*. `tests_view` is a GET request. It is not allowed to change the server state. 
So if we want updated residuals then we need to update them during POST requests, such as `update_task` and `failed_task`. However this may be CPU intensive if a fleet of workers disconnects. We could throttle the updates but this requires some extra state that needs to be maintained (the time of  the last update).
So the alternative is to compute the residuals on the fly when they are displayed. This is what this PR does. This solves for example the issue #1948. It should now again be possible to serve the tasks from a secondary instance.
Computing residuals on the fly is not possible for bad tasks. So for …
> Don't save the residuals and their colors in the db.

- server/fishtest/rundb.py
it appears this limit is now less important than it was previously. Gently increase it.
> Increase max core count for SPSA tasks

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
Currently the worker deletes cached binaries on restart. The reason is that the user may have changed compilers, so that new engine binaries would be matched against old engine binaries, built with a different compiler.
In this PR we add compiler+version and a hash of selected environment variables to the engine name so that there is no risk of matching engine binaries built with different compilers, or with  different environment variables.
A possible enhancement (not in this PR) would be to also add the full build command to the engine name so that engine binaries could even be preserved across worker updates (a worker update may change the build command).
> Include compiler and env in engine name. Retire clear_binaries.

- server/fishtest/views.py
It is seems to be no longer necessary as the main page now builds very fast.
This will also solve the glitch than an approved test sometimes still shows on the main page as unapproved (because the main page came from the cache).
> Disable caching the main page.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
If the worker runs out of GitHub api call then the server consults the `worker_runs` data structure to send the worker only runs it has seen before.
However currently this data structure is indexed by `uuid` which does not persist across worker restarts. In this PR we change the index to the worker name, which is persistent.
> Index worker_runs data structure by short_worker_name.

- server/fishtest/api.py
- server/fishtest/rundb.py
Sometimes the worker list on the main page shows a worker seemingly working on two different tasks - which is impossible. This illusion occurs when one of the tasks is a new one and the other task is a finished task by the same worker which has not been written to disk yet. So from the point of view of the db it is still unfinished.
This PR mitigates this issue by buffering a run with finished tasks with priority 1 (note: a run with new tasks is buffered with priority 2, other runs are buffered with priority 0).
Another reason for this PR is that we want to reduce the number of direct buffer calls. This PR moves some buffer calls deeper in the call chain.
> Save a run with finished tasks with higher priority.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_api.py
- server/tests/test_rundb.py
In the second commit in this PR we convert the `priority` argument to `buffer` to use an `Enum` and we retire the positional `flush` argument in favor of `priority=Prio.SAVE_NOW`.
> Move some more buffer calls deeper in the call chain

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
There was an issue in the way fastchess was writing the game's pgn, mainly doubly ambiguous moves were sometimes not doubly disambiguated.
Also extract the fastchess sha into a constant at the top of the file.
Also fixes the warnings mentioned here https://github.com/official-stockfish/fishtest/pull/2169#issuecomment-2588421900
> Update fastchess version

- server/fishtest/static/js/spsa.js
Thanks to @peregrineshahin for suggesting the improvement.
> Use const for variables

- server/fishtest/run_cache.py
- server/fishtest/rundb.py
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_api.py
- server/tests/test_rundb.py
- server/tests/test_users.py
All the methods have been moved to a separate file.
> Refactor run_cache.

- server/fishtest/__init__.py
- server/fishtest/run_cache.py
- server/fishtest/rundb.py
- server/fishtest/scheduler.py
The former comment about deadlock seems outdated to me. Signal handlers run in the main thread and Fishtest executes no code in the main thread once initialization is finished. So signal handlers behave like asynchronous events in the same way as api calls do, and the latter appear currently to be deadlock free.
In a second commit we make a small tweak in the procedure to stop the scheduler.
> Synchronize flush_all().

- server/fishtest/run_cache.py
Currently this is not important since flush_all is only called when quiting Fishtest, but it is a good programming practice to make it self contained.
> Leave the run_cache in a good state after flush_all.

- server/fishtest/rundb.py
no longer grow the number of games per task,
it is no longer needed for fishtest performance
and limits the number of workers that can be assigned e.g. to a progression test.
> Remove old workaround

- server/fishtest/views.py
- server/utils/aws_nets_sync.py
- server/utils/nginx_cidr_builder.py
The VPS now hosts both the fishtest server and the neural networks repository.
Save directly the network file via Pyramid retiring the FastAPI server.
Add helper script to verify and to backup to AWS S3 the network files.
The helper is scheduled to run on cron with a limited environment, it reads
the necessary environment variables directly by the .profile.
> Save network file w/ Pyramid

- server/tests/util.py
Fix the warnings in server tests.
```python
/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/unittest/suite.py:84: ResourceWarning: Unclosed MongoClient opened at:
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
...
File "/home/runner/work/fishtest/fishtest/server/fishtest/rundb.py", line 61, in __init__
self.conn = MongoClient(os.getenv("FISHTEST_HOST") or "localhost")
Call MongoClient.close() to safely shut down your client and free up resources.
return self.run(*args, **kwds)
```
> fix: close test mongodb connection on exit

- server/fishtest/run_cache.py
- server/fishtest/rundb.py
The run cache should be for caching runs. Nothing else.
> Scavenge dead tasks without using the run cache.

- server/fishtest/api.py
- worker/games.py
- worker/packages/__init__.py
- worker/sri.txt
- worker/updater.py
- worker/worker.py
- Update `__init__.py` to lazily load submodules using a lightweight wrapper.
- When a module (e.g. "requests") is not available from the current
environment, the fallback in the "packages" folder is used.
- Adjust `sys.path` only when "requests" is loaded from the fallback location,
ensuring that the package path is appended only when necessary.
- The lazy loading mechanism is compatible with Python 3.6
Raise worker version to 260 (also server side)
> refactor(worker): improve import from "packages"

- server/fishtest/rundb.py
- server/fishtest/static/js/spsa.js
- save only 100 entries in spsa_history
- save the last iteration in spsa_history
- add the start values to the chart
- compute the smoothed %c as percentage of the smoothed data instead than filtering the %c raw data
- refactor dropping not useful global caches and avoiding duplicated code
> fix(spsa): fix and improve chart code

- server/fishtest/api.py
- server/fishtest/rundb.py
This run https://tests.stockfishchess.org/tests/view/67b119e76c6b9e172ad15939?show_task=2 was stopped by the second task. However the other tasks have a more recent `last_updated` field, which is disturbing.
This PR probably fixes this by:
- in `set_inactive_task` we set the `last_updated` field to now;
- in `api_beat`, we only update `last_updated` if the task is active.
> Refine handling of last_updated in stopped run

- server/fishtest/rundb.py
- server/fishtest/views.py
This failed run was revived
https://tests.stockfishchess.org/actions?run_id=67b2f36338b351d1ce6405e1 and then predictably it failed again after some time. With this PR we disallow reviving a failed run.
> Do not revive a failed run.

- server/fishtest/__init__.py
- server/fishtest/routes.py
- server/fishtest/templates/base.mak
- server/fishtest/templates/login.mak
- server/fishtest/templates/signup.mak
- server/fishtest/templates/sprt_calc.mak
- server/fishtest/templates/tests.mak
- server/fishtest/templates/tests_live_elo.mak
- server/fishtest/templates/tests_run.mak
- server/fishtest/templates/tests_view.mak
- server/fishtest/templates/user.mak
Use the pyramid builtin way to write a cache buster by extending QueryStringCacheBuster.
While at it move the routes to a separate file for easier access.
The four individual 
```
config.add_static_view("css", "static/css", cache_max_age=3600)
config.add_static_view("js", "static/js", cache_max_age=3600)
config.add_static_view("img", "static/img", cache_max_age=3600)
config.add_static_view("html", "static/html", cache_max_age=3600)
```
were combined to just
```
config.add_static_view("static", "static", cache_max_age=3600)
```
I don't think this makes a big difference?
> Overhaul cachebuster logic

- server/fishtest/views.py
Since the main page is no longer cached, `chached_flash` has become superfluous.
> Cleanup: retire `cached_flash`.

- server/fishtest/templates/base.mak
- server/fishtest/views.py
This is used in the view `tests_modify` to alert the user that the run will have to be reapproved.
> Create a "warning" queue for flash messages.

- server/fishtest/rundb.py
- server/fishtest/schemas.py
Rather than maintaining a separate data structure per worker, we store the SPSA data of the worker (c,R and flip) in the corresponding task. To save space in the db we delete this data when the task becomes non-active.
We also make sure that the api "request_spsa" is properly synchronized.
> Simplify handling of SPSA.

- server/fishtest/run_cache.py
- server/fishtest/rundb.py
If we don't do this then the spsa_params for the workers may not survive a server restart.
This fixes another issue with #2239.
> Make sure to buffer the run after request_spsa.

- server/fishtest/run_cache.py
- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/fishtest/util.py
In a task we store not only the spsa data but also the number of games in the task when the spsa data was generated.
> Make the new spsa code robust against a server crash

- server/fishtest/rundb.py
- server/fishtest/schemas.py
- server/utils/clone_fish.py
The Binary wrapper (with subtype 0) seems to stem from the days that Python made no distinction between strings and byte arrays. I checked that wrapping a byte array with Binary makes no difference in the resulting bson encoding. Moreover a Binary wrapper is directly decoded as bytes and not as a Binary wrapper.
Solves:
https://tests.stockfishchess.org/actions?max_actions=1&action=log_message&user=&text=&before=1740938754.68217&run_id=
> Do not wrap byte arrays with Binary.

- server/fishtest/__init__.py
- server/fishtest/rundb.py
In this way it is possible to do a very clean shutdown of the server.
> Block all requests after SIGINT or SIGTERM is received.

- server/fishtest/api.py
- server/fishtest/rundb.py
- server/fishtest/spsa_handler.py
- server/fishtest/templates/tests_view.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_rundb.py
SPSA code related code is sprinkled at various places. It would be beneficial to put it in a single place.
In this PR we move the SPSA code in rundb.py to a separate file. Other code will follow in the future. We submit this PR now because it is difficult to continuously rebase a PR that moves code.
> Put SPSA code in a separate file.

- server/fishtest/templates/tests_view.mak
Here is how it looks now:
Before
> Move base diff link to "base branch not same as master" card

- server/fishtest/templates/tests_view.mak
- server/fishtest/views.py
This is part of an attempt to better structure the various bits of information on the test page that may affect the approval decision.
Here is what this PR looks like when all warnings occur:
> Combine all warnings in a single card.

- server/fishtest/api.py
- worker/sri.txt
- worker/worker.py
I propose we update the GCC and Clang minimum required version to 9.3 and 10.0 to slowly force users with very old systems to update their compilers.
gcc 9.3 has been chosen as the minimum version for gcc since it is the at the time of writing the oldest used version (by noob).
clang 10.0 has been chosen since it almost matches the release date of gcc 9.3 (gcc March 12, 2020 vs clang 24 Mar 2020).
At the time of writing there are no active clang contributors.
> Update min GCC to 9.3 and Clang to 10.0

- server/fishtest/views.py
The "Base engine options are not the same..." warning is currently suppressed for SPSA tests.
This hides potential configuration errors (e.g., different Hash values) that can invalidate SPSA results and waste resources.
This should help developers and approvers quickly identify option mismatches (especially Hash) in SPSA tests, improving test validity and preventing wasted resources.
A practical example of where this lack of warning caused confusion can be seen in test:
https://tests.stockfishchess.org/tests/view/67f8f1fc5bd14afa3759ebbe
In this SPSA test, the Hash values were unintentionally different (32 vs 16). This discrepancy was not flagged by the UI warning, delaying its identification by both the submitter and the approver. Had the warning been present for SPSA tests, this common …
> Show engine option mismatch warning also for SPSA tests

- server/fishtest/static/js/spsa_new.js
- server/fishtest/templates/tests_run.mak
The previous version `UHO_4060_v3.epd` contained some duplicates, which have now been removed. See https://github.com/official-stockfish/books/pull/50.
@dav1312 FYI
> update book used for PTs

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/updater.py
- worker/worker.py
For some time now the books repo provides checksums for our books in a json file, and these are now available from the server via the `book_sri` key.
This PR makes the worker check the validity of a book before it is being used.
At the moment the logic is as follows:
* if a book is found, and the checksum fails, we delete the book, download it once and re-test the checksum
* if a book was downloaded and the checksum fails, an error message is printed, but the worker continues as normal
* if we fail to obtain the `book_sri` information from the server, the worker prints an error message and continues as normal
We also raise the "expiration" time of local book files in `updater.py` to 365 days since they were last accessed (up from 30 days).
> Check book checksums

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/updater.py
- worker/worker.py
* use f-strings nearly everywhere in favour of `.format`
* messages to stdout or stderr now ~~always~~in general end with `.` or `...` (unless they end with errors or exceptions or information given after a colon)
* rename variable name parts `bkp` to `backup`
* introduce variable `fastchess_zip`
* some other nonfunctional simplifications
> refactor: use f-strings throughout

- server/fishtest/views.py
See https://github.com/official-stockfish/fishtest/pull/2310#issuecomment-2961779417
A Stockfish developer can change their GitHub username. The old url of the developer fork continues to work and is forwarded to the new url.
However the old username can no longer be used to refer to commits in the fork and this leads to bugs.
In this PR we replace the outdated repo url with the most current one.
> One more fix in dealing with #2309

- server/fishtest/github_api.py
It is already performed deeper in the call chain.
I noticed this because after #2332 suddenly test pages take a long time to load, even when all github api calls are cached. 
In a second commit we remove the explicit invocation of the rate limit api.
> Remove the rate limit check in is_master

- server/fishtest/github_api.py
- server/fishtest/kvstore.py
- server/fishtest/lru_cache.py
- server/fishtest/rundb.py
- server/fishtest/templates/rate_limits.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_run.py
- Always pass exceptions to the caller. There are too many things that can go wrong, to silently suppress such exceptions.
- More idiomatic javascript in rate_limits.mak.
- Home grown LRUCache that better suits our needs. The implementation is a simple wrapper around OrderedDict.
- The cacheing of GitHub api calls is now persistent across server restarts.
- Recent users cannot have DEV repo that is not forked from official-stockfish.
> More refactorings of github_api calls

- server/fishtest/lru_cache.py
Without this, it doesn't actually work...
> Insert move_to_end calls in lru_cache __(get,set)item__()

- server/fishtest/__init__.py
- server/fishtest/github_api.py
- server/fishtest/rundb.py
- server/fishtest/templates/rate_limits.mak
- server/fishtest/util.py
- server/fishtest/views.py
- server/tests/test_run.py
- Install signal handlers also in secondary instances (bugfix). It seems this code was accidentally disabled in the past. The result of this was that stopping secondary instances was no longer recorded in the event log.
- Make sure that `gitub_api.py` is properly initialized before we use it.
- Initialize `github_api.py` in `__init__.py` rather than in the constructor of `rundb`. We do this only in the primary instance.
- Instead of directly importing methods from `github_api.py` (recall that we think of it as a singleton object) we now do `import fishtest.github_api as gh` and then use `gh.<method>`.
- Create a private method `_update_rate_limit` which does the heavy lifting for keeping `_github_rate_limit` up to date.
- Fix a tab error in `rate_limits.mak`.
> Various cleanups

- server/fishtest/rundb.py
- server/fishtest/templates/tests_view.mak
- server/fishtest/views.py
Fishtest keeps track of the official master sha in the variable `gh.official_master_sha`. Unfortunately a left over `rundb.official_master_sha` also exists which is used at a few places instead of the correct `gh.official_master_sha`.
`rundb.official_master_sha` is initialized correctly most of the time, but not updated. This explains why the server suddenly started misbehaving after a master update.
This PR deletes `rundb.official_master_sha`.
> Hopefully fix for #2358

- server/fishtest/__init__.py
- server/fishtest/github_api.py
- server/tests/test_github_api.py
Occasionally there are reports of GitHub API calls that fail and then succeed when repeated. E.g.
https://github.com/official-stockfish/fishtest/pull/2293#issuecomment-2956858006
It would be interesting to know how often this occurs. Therefore we now log such events in the event log. We do this by saving certain error replies in the GH API cache but we do not use these entries afterwards. So there is no negative caching. Not at this time anyway.
It is not obvious how to test this PR in real life, but it is tested in `test_github_not_found()` in `test_github_api.py`.
> Log failing API calls to event log.

- server/fishtest/api.py
This only affects browsers. See
https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS
CORS is already disabled for the actions api.
> Disable CORS for the public get_run api

- server/fishtest/api.py
- worker/games.py
- worker/sri.txt
- worker/worker.py
This should fix #2385 (the cause of that issue remains unclear however).
Note: we no longer delete the pgn file. We rely instead on the trim_files() function which is called when starting a new task.
> Use run_id/task_id in the name of the pgn file
